-----------------------------------------------------
----- APP_PBE.TI_TRAININGS --------------------------
-----------------------------------------------------


MERGE INTO APP_PBE.TI_TRAININGS T
USING (
    SELECT TRAINING_ID, MAX_PARTICIPANTS_COUNT
    FROM (
        SELECT C.TRAINING_ID, C.MAX_PARTICIPANTS_COUNT,
               C.REGISTRATION_DATE,
               rank() over (partition by C.TRAINING_ID, C.MAX_PARTICIPANTS_COUNT order by C.REGISTRATION_DATE desc) rnk
          FROM (
SELECT DISTINCT E.TRAINING_ID, E.REGISTRATION_DATE, E.MAX_PARTICIPANTS_COUNT
FROM APP_PBE.TI_TRAINING_INSTANCES_EXT E
WHERE E.TRAINING_ID IS NOT NULL AND E.REGISTRATION_DATE IS NOT NULL
UNION ALL
SELECT DISTINCT A.TRAINING_ID, A.REGISTRATION_DATE, A.MAX_PARTICIPANTS_COUNT
FROM APP_PBE.TI_TRAINING_INSTANCES_EXT_AUDT A
WHERE A.TRAINING_ID IS NOT NULL  AND A.REGISTRATION_DATE IS NOT NULL
          ) 
        C)
 WHERE rnk = 1) D
 ON (T.ID=D.TRAINING_ID)
 WHEN MATCHED THEN UPDATE
 SET T.MAX_PARTICIPANTS=D.MAX_PARTICIPANTS_COUNT;