-----------------------------------------------------
----- APP_PBE.TI_TRAINING_CATEGORY_PARAMS -----------
-----------------------------------------------------

ALTER TABLE APP_PBE.TI_TRAINING_CATEGORY_PARAMS
 ADD (MAX_PARTICIPANTS  NUMBER(10));

ALTER TABLE APP_PBE.TI_TRAINING_CATEGORY_PARAMS
RENAME COLUMN INDIVIDUAL_PRODUCT_INSTANCE TO MIN_PARTICIPANTS;
