package pl.sodexo.it.gryf.web.ti.response;

public enum ResponseType {
    STALE_USER_DATA, UNAUTHORIZED, VALIDATION_ERROR, VALIDATION_WITH_CONFIRM_ERROR, GENERAL_EXCEPTION, INVALID_OBJECT_ID_EXCEPTION, IND_USER_VERIFICATION_EXCEPTION
}
