CREATE TABLE APP_PBE.PBE_PRD_INST_EVN_TYPE_DICS
(
	PET_CODE VARCHAR2(5) NOT NULL,
	DESCRIPTION VARCHAR2(200),
	ORDINAL NUMBER(10),
	CREATED_USER VARCHAR2(100) NOT NULL,
	CREATED_TIMESTAMP TIMESTAMP(6) NOT NULL,
	MODIFIED_USER VARCHAR2(100),
	MODIFIED_TIMESTAMP TIMESTAMP(6)
)
;

-- uprawnienia
BEGIN
  dbms_output.put_line(SYS.PK_ADMIN.F_GRANT_TO_EAGLE('APP_PBE', 'EAGLE', 'PBE_PRD_INST_EVN_TYPE_DICS', 'ALL'));
  dbms_output.put_line(SYS.PK_ADMIN.F_GRANT_TO_EAGLE('APP_PBE', 'SRV_EE', 'PBE_PRD_INST_EVN_TYPE_DICS', 'ALL'));
  dbms_output.put_line(SYS.PK_ADMIN.F_GRANT_TO_EAGLE('APP_PBE', 'DEVELOPER', 'PBE_PRD_INST_EVN_TYPE_DICS', 'SELECT'));
END;
/

-- Indeksy
CREATE UNIQUE INDEX APP_PBE.PRD_INST_EVN_TYP_DIC_PK ON APP_PBE.PBE_PRD_INST_EVN_TYPE_DICS (PET_CODE);

-- Klucze
ALTER TABLE APP_PBE.PBE_PRD_INST_EVN_TYPE_DICS
 ADD CONSTRAINT PRD_INST_EVN_TYP_DIC_PK
	PRIMARY KEY (PET_CODE)
;

-- Komentarze
COMMENT ON TABLE APP_PBE.PBE_PRD_INST_EVN_TYPE_DICS IS '@Author(Adam Kmieciñski); @Project(GryfBonEl); @Date(2016-10-12);@Purpose(Tabel wartoœci s³ownikowych dla typów wydarzeñ instancji produktów);';

COMMENT ON COLUMN APP_PBE.PBE_PRD_INST_EVN_TYPE_DICS.PET_CODE IS 'Kod s³ownika. Klucz g³ówny';
COMMENT ON COLUMN APP_PBE.PBE_PRD_INST_EVN_TYPE_DICS.DESCRIPTION IS 'Opis wartoœci s³ownikowej';
COMMENT ON COLUMN APP_PBE.PBE_PRD_INST_EVN_TYPE_DICS.ORDINAL IS 'Liczba porz¹dkowa';
COMMENT ON COLUMN APP_PBE.PBE_PRD_INST_EVN_TYPE_DICS.CREATED_USER IS 'Login u¿ytkownika, który utworzy³ rekord';
COMMENT ON COLUMN APP_PBE.PBE_PRD_INST_EVN_TYPE_DICS.CREATED_TIMESTAMP IS 'Data utworzenia rekordu';
COMMENT ON COLUMN APP_PBE.PBE_PRD_INST_EVN_TYPE_DICS.MODIFIED_USER IS 'Login u¿ytkownika, który ostatnio modyfikowa³ rekord';
COMMENT ON COLUMN APP_PBE.PBE_PRD_INST_EVN_TYPE_DICS.MODIFIED_TIMESTAMP IS 'Data ostatniej modyfikacji rekordu';