ALTER TABLE APP_PBE.E_REIMBURSEMENTS
  ADD (
  NAV_EXPORTED VARCHAR2(1) DEFAULT 'N' NOT NULL,
  NAV_EXPORT_DATE DATE NULL
  );

COMMENT ON COLUMN APP_PBE.E_REIMBURSEMENTS.NAV_EXPORTED IS 'Czy rozliczenie zosta³o wyeksportowane do Navision';
COMMENT ON COLUMN APP_PBE.E_REIMBURSEMENTS.NAV_EXPORT_DATE IS 'DATA eksportu do Navision';