CREATE TABLE APP_PBE.TE_IND_USER_IN_ROLES
(
	INU_ID NUMBER NOT NULL,
	TE_ROLE_CODE VARCHAR2(50) NOT NULL
)
;

-- uprawnienia
BEGIN
  dbms_output.put_line(SYS.PK_ADMIN.F_GRANT_TO_EAGLE('APP_PBE', 'EAGLE', 'TE_IND_USER_IN_ROLES', 'ALL'));
  dbms_output.put_line(SYS.PK_ADMIN.F_GRANT_TO_EAGLE('APP_PBE', 'SRV_EE', 'TE_IND_USER_IN_ROLES', 'ALL'));
  dbms_output.put_line(SYS.PK_ADMIN.F_GRANT_TO_EAGLE('APP_PBE', 'DEVELOPER', 'TE_IND_USER_IN_ROLES', 'SELECT'));
END;
/

-- Indeksy
CREATE UNIQUE INDEX APP_PBE.TE_IND_USER_IN_ROLES ON APP_PBE.TE_IND_USER_IN_ROLES (INU_ID,TE_ROLE_CODE);

-- Klucze
ALTER TABLE APP_PBE.TE_IND_USER_IN_ROLES 
 ADD CONSTRAINT TE_IND_USER_IN_ROLES_PK
	PRIMARY KEY (INU_ID,TE_ROLE_CODE)
;

ALTER TABLE APP_PBE.TE_IND_USER_IN_ROLES 
 ADD CONSTRAINT IND_USR_TE_IND_USR_IN_RLS_FK
	FOREIGN KEY (TE_ROLE_CODE) REFERENCES APP_PBE.TE_ROLES (CODE)
;

ALTER TABLE APP_PBE.TE_IND_USER_IN_ROLES 
 ADD CONSTRAINT TE_IND_USER_IN_ROLES_CODE_FK
	FOREIGN KEY (INU_ID) REFERENCES APP_PBE.INDIVIDUAL_USERS (INU_ID)
;

-- Komentarze
COMMENT ON TABLE APP_PBE.TE_IND_USER_IN_ROLES IS '@Author(Adam Kmieciñski); @Project(Gryf-PBE); @Date(2016-10-18) ;@Purpose(Tabela z³¹czeniowa u¿ytkwonika osoby fizycznej z rol¹);';

COMMENT ON COLUMN APP_PBE.TE_IND_USER_IN_ROLES.INU_ID IS 'Unikalne ID u¿ytkownika osoby fizycznej';
COMMENT ON COLUMN APP_PBE.TE_IND_USER_IN_ROLES.TE_ROLE_CODE IS 'Kod roli bezpieczeñstwa osoby fizycznej';