ALTER TABLE APP_PBE.ORDERS ADD (CONTRACT_ID NUMBER);
ALTER TABLE APP_PBE.ORDERS ADD CONSTRAINT ORD_CONT_FK FOREIGN KEY (CONTRACT_ID) REFERENCES APP_PBE.CONTRACTS (ID);
COMMENT ON COLUMN APP_PBE.ORDERS.CONTRACT_ID IS 'Identyfikator umowy';

