ALTER TABLE APP_PBE.E_REIMBURSEMENTS ADD (REJECTION_REASON_ID NUMBER);
ALTER TABLE APP_PBE.E_REIMBURSEMENTS ADD (REJECTION_DETAILS VARCHAR2(4000));
ALTER TABLE APP_PBE.E_REIMBURSEMENTS ADD (REJECTION_DATE DATE);

COMMENT ON COLUMN APP_PBE.E_REIMBURSEMENTS.REJECTION_REASON_ID IS 'ID powodu odrzucenia';
COMMENT ON COLUMN APP_PBE.E_REIMBURSEMENTS.REJECTION_DETAILS IS 'Szczegó³y odrzucenia';
COMMENT ON COLUMN APP_PBE.E_REIMBURSEMENTS.REJECTION_DATE IS 'Data odrzucenia';