CREATE TABLE APP_PBE.PBE_TRAINING_CATEGORY_DICS
(
	TRC_CODE VARCHAR2(5) NOT NULL,
	DESCRIPTION VARCHAR2(200),
	ORDINAL NUMBER(10) NOT NULL,
	CREATED_USER VARCHAR2(100) NOT NULL,
	CREATED_TIMESTAMP TIMESTAMP(6) NOT NULL,
	MODIFIED_USER VARCHAR2(100) NOT NULL,
	MODIFIED_TIMESTAMP TIMESTAMP(6) NOT NULL
);

-- constrainty i indeksy
CREATE UNIQUE INDEX APP_PBE.PBE_TRA_CAT_DIC_PK   
 ON APP_PBE.PBE_TRAINING_CATEGORY_DICS (TRC_CODE);
 
ALTER TABLE APP_PBE.PBE_TRAINING_CATEGORY_DICS 
 ADD CONSTRAINT PBE_TRA_CAT_DIC_PK
	PRIMARY KEY (TRC_CODE);

-- uprawnienia
BEGIN
  dbms_output.put_line(SYS.PK_ADMIN.F_GRANT_TO_EAGLE('APP_PBE', 'EAGLE', 'PBE_TRAINING_CATEGORY_DICS', 'ALL'));
  dbms_output.put_line(SYS.PK_ADMIN.F_GRANT_TO_EAGLE('APP_PBE', 'SRV_EE', 'PBE_TRAINING_CATEGORY_DICS', 'ALL'));
  dbms_output.put_line(SYS.PK_ADMIN.F_GRANT_TO_EAGLE('APP_PBE', 'DEVELOPER', 'PBE_TRAINING_CATEGORY_DICS', 'SELECT'));
END;
/

-- komentarze
COMMENT ON TABLE APP_PBE.PBE_TRAINING_CATEGORY_DICS IS '@Author(Krzysztof Antczak); @Project(Gryf-PBE); @Date(2016-10-25);@Purpose(Tabela s³ownikowa okreœlaj¹ca kategorie szkoleñ);';
COMMENT ON COLUMN APP_PBE.PBE_TRAINING_CATEGORY_DICS.TRC_CODE IS 'Kod bêd¹cy kluczem g³ównym';
COMMENT ON COLUMN APP_PBE.PBE_TRAINING_CATEGORY_DICS.DESCRIPTION IS 'Opis wartoœci s³ownikowej';
COMMENT ON COLUMN APP_PBE.PBE_TRAINING_CATEGORY_DICS.ORDINAL IS 'Liczba porz¹dkowa';
COMMENT ON COLUMN APP_PBE.PBE_TRAINING_CATEGORY_DICS.CREATED_USER IS 'Nazwa u¿ytkownika, który utworzy³ rekord';
COMMENT ON COLUMN APP_PBE.PBE_TRAINING_CATEGORY_DICS.CREATED_TIMESTAMP IS 'Data i czas utworzenia rekordu';
COMMENT ON COLUMN APP_PBE.PBE_TRAINING_CATEGORY_DICS.MODIFIED_USER IS 'Nazwa u¿ytkownika, który ostatnio modyfikowa³ rekord';
COMMENT ON COLUMN APP_PBE.PBE_TRAINING_CATEGORY_DICS.MODIFIED_TIMESTAMP IS 'Data i czas ostatniej modyfikacji rekordu';