CREATE TABLE APP_PBE.E_REIMBURSEMENT_STATUSES
(
	ID VARCHAR2(5) NOT NULL,
	NAME VARCHAR2(200) NOT NULL,
	ORDINAL NUMBER
);

COMMENT ON TABLE APP_PBE.E_REIMBURSEMENT_STATUSES IS '@Author(Adam Kmieciñski); @Project(Gryf-PBE); @Date(2016-11-14);@Purpose(Tabela przechowuj¹ca dane ze statusami e-rozliczenia);';

COMMENT ON COLUMN APP_PBE.E_REIMBURSEMENT_STATUSES.ID IS 'Kod statusu rozliczenia - klucz gówny';
COMMENT ON COLUMN APP_PBE.E_REIMBURSEMENT_STATUSES.NAME IS 'Opis wartoœci s³ownikowej';
COMMENT ON COLUMN APP_PBE.E_REIMBURSEMENT_STATUSES.ORDINAL IS 'Liczba porz¹dkowa';

-- uprawnienia
BEGIN
  dbms_output.put_line(SYS.PK_ADMIN.F_GRANT_TO_EAGLE('APP_PBE', 'EAGLE', 'E_REIMBURSEMENT_STATUSES', 'ALL'));
  dbms_output.put_line(SYS.PK_ADMIN.F_GRANT_TO_EAGLE('APP_PBE', 'SRV_EE', 'E_REIMBURSEMENT_STATUSES', 'ALL'));
  dbms_output.put_line(SYS.PK_ADMIN.F_GRANT_TO_EAGLE('APP_PBE', 'DEVELOPER', 'E_REIMBURSEMENT_STATUSES', 'SELECT'));
END;
/

-- Indeksy
CREATE UNIQUE INDEX APP_PBE.PK_E_REIMBURSEMEN_ST_ID ON APP_PBE.E_REIMBURSEMENT_STATUSES (ID);

ALTER TABLE APP_PBE.E_REIMBURSEMENT_STATUSES
 ADD CONSTRAINT PK_E_REIMBURSEMEN_ST_ID
	PRIMARY KEY (ID);