CREATE TABLE APP_PBE.PBE_PRODUCT_INSTANCE_STATUSES
(
	ID VARCHAR2(5) NOT NULL,
	NAME VARCHAR2(200),
	ORDINAL NUMBER(10)
);

-- uprawnienia
BEGIN
  dbms_output.put_line(SYS.PK_ADMIN.F_GRANT_TO_EAGLE('APP_PBE', 'EAGLE', 'PBE_PRODUCT_INSTANCE_STATUSES', 'ALL'));
  dbms_output.put_line(SYS.PK_ADMIN.F_GRANT_TO_EAGLE('APP_PBE', 'SRV_EE', 'PBE_PRODUCT_INSTANCE_STATUSES', 'ALL'));
  dbms_output.put_line(SYS.PK_ADMIN.F_GRANT_TO_EAGLE('APP_PBE', 'DEVELOPER', 'PBE_PRODUCT_INSTANCE_STATUSES', 'SELECT'));
END;
/

-- Klucze
CREATE UNIQUE INDEX APP_PBE.PRD_INST_ST_DIC_PK ON APP_PBE.PBE_PRODUCT_INSTANCE_STATUSES (ID);
ALTER TABLE APP_PBE.PBE_PRODUCT_INSTANCE_STATUSES ADD CONSTRAINT PRD_INST_ST_DIC_PK PRIMARY KEY (ID);

-- Komentarze
COMMENT ON TABLE APP_PBE.PBE_PRODUCT_INSTANCE_STATUSES IS '@Author(Adam Kmieciñski); @Project(GryfBonEl); @Date(2016-10-12);@Purpose(Tabel wartoœci s³ownikowych dla statusów instancji produktów);';

COMMENT ON COLUMN APP_PBE.PBE_PRODUCT_INSTANCE_STATUSES.ID IS 'Kod s³ownika. Klucz g³ówny';
COMMENT ON COLUMN APP_PBE.PBE_PRODUCT_INSTANCE_STATUSES.NAME IS 'Opis wartoœci s³ownikowej';
COMMENT ON COLUMN APP_PBE.PBE_PRODUCT_INSTANCE_STATUSES.ORDINAL IS 'Liczba porz¹dkowa';