
MERGE INTO EAGLE.ADM_USER_GROUPS ug USING (
  SELECT 
    'GRF_PBE_PRODUCTS_GEN_PRINT_NUM' ID,
    'Generowanie numerów drukowanych dla bonów' NAME,
    'A' STATUS,
    'Generowanie numerów drukowanych dla bonów' DESCRIPTION
  FROM dual
) ins
ON (ug.id = ins.ID)
WHEN MATCHED THEN
  UPDATE SET ug.DESCRIPTION = ins.DESCRIPTION, ug.NAME = ins.NAME
WHEN NOT MATCHED THEN INSERT
  (ID,NAME,STATUS,DESCRIPTION)
  VALUES (ins.ID, ins.NAME, ins.STATUS, ins.DESCRIPTION);

MERGE INTO EAGLE.ADM_GROUPS_IN_ROLES gr_ro USING (
  SELECT 
    'ADM_ADMINISTRACJA' ARO_ID,
    'GRF_PBE_PRODUCTS_GEN_PRINT_NUM' AUG_ID
  FROM dual
) ins
ON (gr_ro.AUG_ID = ins.AUG_ID AND gr_ro.ARO_ID = ins.ARO_ID)
WHEN NOT MATCHED THEN INSERT
  (ARO_ID,AUG_ID)
  VALUES (ins.ARO_ID,ins.AUG_ID);
