CREATE TABLE APP_PBE.PBE_PRODUCT_INSTANCE_POOL_STAS
(
	ID VARCHAR2(10 BYTE) NOT NULL,
	NAME VARCHAR2(200 BYTE),
	ORDINAL NUMBER(10)
);

-- uprawnienia
BEGIN
  dbms_output.put_line(SYS.PK_ADMIN.F_GRANT_TO_EAGLE('APP_PBE', 'EAGLE', 'PBE_PRODUCT_INSTANCE_POOL_STAS', 'ALL'));
  dbms_output.put_line(SYS.PK_ADMIN.F_GRANT_TO_EAGLE('APP_PBE', 'SRV_EE', 'PBE_PRODUCT_INSTANCE_POOL_STAS', 'ALL'));
  dbms_output.put_line(SYS.PK_ADMIN.F_GRANT_TO_EAGLE('APP_PBE', 'DEVELOPER', 'PBE_PRODUCT_INSTANCE_POOL_STAS', 'SELECT'));
END;
/

-- Klucze
CREATE UNIQUE INDEX APP_PBE.PBE_PRD_INS_POL_STA_PK ON APP_PBE.PBE_PRODUCT_INSTANCE_POOL_STAS (ID);
ALTER TABLE APP_PBE.PBE_PRODUCT_INSTANCE_POOL_STAS ADD CONSTRAINT PBE_PRD_INS_POL_STA_PK PRIMARY KEY (ID);

-- Komentarze
COMMENT ON TABLE APP_PBE.PBE_PRODUCT_INSTANCE_POOL_STAS IS '@Author(Adam Kmieciñski); @Project(GryfBonEl); @Date(2016-10-12);@Purpose(Tabel wartoœci s³ownikowych dla statusów instancji puli);';

COMMENT ON COLUMN APP_PBE.PBE_PRODUCT_INSTANCE_POOL_STAS.ID IS 'Kod s³ownika. Klucz g³ówny';
COMMENT ON COLUMN APP_PBE.PBE_PRODUCT_INSTANCE_POOL_STAS.NAME IS 'Opis wartoœci s³ownikowej';
COMMENT ON COLUMN APP_PBE.PBE_PRODUCT_INSTANCE_POOL_STAS.ORDINAL IS 'Liczba porz¹dkowa';