
delete
from APP_PBE.ORDER_FLOW_ELEMENTS_IN_STATUS
where ELEMENT_ID = 'CANDATE_KK';
delete
from APP_PBE.ORDER_FLOW_ST_TRANS_ELEM_FLAGS
where ELEMENT_ID in ('CANDATE_KK', 'CANREAS_KK');

Insert into APP_PBE.ORDER_FLOW_ELEMENTS_IN_STATUS (STATUS_ID,ELEMENT_ID,POS,FLAGS,AUG_ID_REQUIRED,ALLOWED_DELAY_TYPE_ID) values ('NEWKK',       'CANDATE_KK',116, 'IU', null,null);
Insert into APP_PBE.ORDER_FLOW_ELEMENTS_IN_STATUS (STATUS_ID,ELEMENT_ID,POS,FLAGS,AUG_ID_REQUIRED,ALLOWED_DELAY_TYPE_ID) values ('PAIDKK',      'CANDATE_KK',116, 'IU', null,null);
Insert into APP_PBE.ORDER_FLOW_ELEMENTS_IN_STATUS (STATUS_ID,ELEMENT_ID,POS,FLAGS,AUG_ID_REQUIRED,ALLOWED_DELAY_TYPE_ID) values ('CANCELLDKK',  'CANDATE_KK',116, null, null,null);


insert into APP_PBE.ORDER_FLOW_ST_TRANS_ELEM_FLAGS(ORDER_FLOW_ID, STATUS_ID, ACTION_ID, ELEMENT_ID, FLAGS) values (100, 'NEWKK', 10015, 'CANREAS_KK', 'M');
insert into APP_PBE.ORDER_FLOW_ST_TRANS_ELEM_FLAGS(ORDER_FLOW_ID, STATUS_ID, ACTION_ID, ELEMENT_ID, FLAGS) values (100, 'PAIDKK', 10025, 'CANREAS_KK', 'M');

insert into APP_PBE.ORDER_FLOW_ST_TRANS_ELEM_FLAGS(ORDER_FLOW_ID, STATUS_ID, ACTION_ID, ELEMENT_ID, FLAGS) values (100, 'NEWKK', 10015, 'CANDATE_KK', 'M');
insert into APP_PBE.ORDER_FLOW_ST_TRANS_ELEM_FLAGS(ORDER_FLOW_ID, STATUS_ID, ACTION_ID, ELEMENT_ID, FLAGS) values (100, 'PAIDKK', 10025, 'CANDATE_KK', 'M');
