CREATE TABLE APP_PBE.TI_TRAINING_CATEGORIES
(
	ID VARCHAR2(5) NOT NULL,
	NAME VARCHAR2(200),
	ORDINAL NUMBER(10) NOT NULL,
  PARENT_ID VARCHAR2(5),
  CATALOG_ID VARCHAR2(10) NOT NULL
);

-- constrainty i indeksy
CREATE UNIQUE INDEX APP_PBE.TI_TRA_CAT_PK ON APP_PBE.TI_TRAINING_CATEGORIES (ID);
ALTER TABLE APP_PBE.TI_TRAINING_CATEGORIES ADD CONSTRAINT TI_TRA_CAT_PK PRIMARY KEY (ID);
ALTER TABLE APP_PBE.TI_TRAINING_CATEGORIES
 ADD CONSTRAINT TI_TRA_CAT_PARENT_ID_FK
	FOREIGN KEY (PARENT_ID) REFERENCES APP_PBE.TI_TRAINING_CATEGORIES (ID)
;


-- uprawnienia
BEGIN
  dbms_output.put_line(SYS.PK_ADMIN.F_GRANT_TO_EAGLE('APP_PBE', 'EAGLE', 'TI_TRAINING_CATEGORIES', 'ALL'));
  dbms_output.put_line(SYS.PK_ADMIN.F_GRANT_TO_EAGLE('APP_PBE', 'SRV_EE', 'TI_TRAINING_CATEGORIES', 'ALL'));
  dbms_output.put_line(SYS.PK_ADMIN.F_GRANT_TO_EAGLE('APP_PBE', 'DEVELOPER', 'TI_TRAINING_CATEGORIES', 'SELECT'));
END;
/

-- komentarze
COMMENT ON TABLE APP_PBE.TI_TRAINING_CATEGORIES IS '@Author(Krzysztof Antczak); @Project(Gryf-PBE); @Date(2016-10-25);@Purpose(Tabela s³ownikowa okreœlaj¹ca kategorie szkoleñ);';
COMMENT ON COLUMN APP_PBE.TI_TRAINING_CATEGORIES.ID IS 'Kod bêd¹cy kluczem g³ównym';
COMMENT ON COLUMN APP_PBE.TI_TRAINING_CATEGORIES.NAME IS 'Opis wartoœci s³ownikowej';
COMMENT ON COLUMN APP_PBE.TI_TRAINING_CATEGORIES.ORDINAL IS 'Liczba porz¹dkowa';
COMMENT ON COLUMN APP_PBE.TI_TRAINING_CATEGORIES.PARENT_ID IS 'Identyfikator kategorii nadrzêdnej';
COMMENT ON COLUMN APP_PBE.TI_TRAINING_CATEGORIES.CATALOG_ID IS 'Identyfikator katalogu';
