----------------------------
--TRAINING_INSTITUTION_USERS
----------------------------

CREATE SEQUENCE EAGLE.TRIN_USR_SEQ 
   MINVALUE 1 
   MAXVALUE 9999999999999999999999999999 
   INCREMENT BY 1 
   START WITH 1 
   CACHE 20 
   NOORDER NOCYCLE ;

CREATE TABLE APP_PBE.TRAINING_INSTITUTION_USERS(
  ID NUMBER NOT NULL,
  TRAINING_ISTITUTION_ID NUMBER NOT NULL,
  LOGIN VARCHAR2(150) NOT NULL,
  EMAIL VARCHAR2(150) NOT NULL,
  PASSWORD varchar2 (60) NOT NULL,
  LAST_LOGIN_DATE DATE,
  PASSWORD_EXP_DATE DATE,
  IS_ACTIVE varchar2(1 BYTE) DEFAULT 1 NOT NULL,
  VERSION Number,
  CREATED_USER Varchar2(30) NOT NULL,
  CREATED_TIMESTAMP Timestamp(6) NOT NULL,
  MODIFIED_USER Varchar2(30) NOT NULL,
  MODIFIED_TIMESTAMP Timestamp(6) NOT NULL
);

-- uprawnienia
BEGIN
  dbms_output.put_line(SYS.PK_ADMIN.F_GRANT_TO_EAGLE('APP_PBE', 'EAGLE', 'TRAINING_INSTITUTION_USERS', 'ALL')); 
  dbms_output.put_line(SYS.PK_ADMIN.F_GRANT_TO_EAGLE('APP_PBE', 'SRV_EE', 'TRAINING_INSTITUTION_USERS', 'ALL'));   
  dbms_output.put_line(SYS.PK_ADMIN.F_GRANT_TO_EAGLE('APP_PBE', 'DEVELOPER', 'TRAINING_INSTITUTION_USERS', 'SELECT'));      
END;
/
-- Indeksy
CREATE UNIQUE INDEX APP_PBE.TRIN_USR_PK ON APP_PBE.TRAINING_INSTITUTION_USERS (ID);
CREATE UNIQUE INDEX APP_PBE.TRIN_USR_LOGIN_UIDX ON APP_PBE.TRAINING_INSTITUTION_USERS (LOGIN);

-- Klucze
ALTER TABLE APP_PBE.TRAINING_INSTITUTION_USERS ADD CONSTRAINT TRIN_USR_PK PRIMARY KEY (ID);
--FK
ALTER TABLE APP_PBE.TRAINING_INSTITUTION_USERS ADD CONSTRAINT TRIN_USR_TRIN_FK FOREIGN KEY (TRAINING_ISTITUTION_ID) REFERENCES APP_PBE.TRAINING_INSTITUTIONS (ID);

-- Komentarze
COMMENT ON TABLE APP_PBE.TRAINING_INSTITUTION_USERS IS '@Author(Jakub.Bentyn); @Project(Gryf-PBE); @Date(2016-10-05) ;@Purpose(Tabela przechowuj¹ca u¿ytkowników IS);';

COMMENT ON COLUMN APP_PBE.TRAINING_INSTITUTION_USERS.ID IS 'Unikalne ID u¿ytkownika IS nadawane automatycznie. Sekwencja: EAGLE.TRIN_USR_SEQ ';
COMMENT ON COLUMN APP_PBE.TRAINING_INSTITUTION_USERS.LOGIN IS 'Login u¿ytkownika IS'; 
COMMENT ON COLUMN APP_PBE.TRAINING_INSTITUTION_USERS.EMAIL IS 'Adres email u¿ytkownika';
COMMENT ON COLUMN APP_PBE.TRAINING_INSTITUTION_USERS.PASSWORD IS 'Hash has³a'; 
COMMENT ON COLUMN APP_PBE.TRAINING_INSTITUTION_USERS.LAST_LOGIN_DATE IS 'Data ostatniego udanego logowania';
COMMENT ON COLUMN APP_PBE.TRAINING_INSTITUTION_USERS.PASSWORD_EXP_DATE IS 'Data wygaœniêcia has³a';
COMMENT ON COLUMN APP_PBE.TRAINING_INSTITUTION_USERS.IS_ACTIVE IS 'Flaga oznaczaj¹ca czy konto uzytkownika jest aktywne'; 
COMMENT ON COLUMN APP_PBE.TRAINING_INSTITUTION_USERS.VERSION IS 'Kolumna techniczna u¿ywana do mechanizmu Optimistic Lock'; 
COMMENT ON COLUMN APP_PBE.TRAINING_INSTITUTION_USERS.CREATED_USER IS 'Login u¿ytkownika, który utworzy³ rekord'; 
COMMENT ON COLUMN APP_PBE.TRAINING_INSTITUTION_USERS.CREATED_TIMESTAMP IS 'Data utworzenia rekordu'; 
COMMENT ON COLUMN APP_PBE.TRAINING_INSTITUTION_USERS.MODIFIED_USER IS 'Login u¿ytkownika, który ostatnio modyfikowa³ rekord'; 
COMMENT ON COLUMN APP_PBE.TRAINING_INSTITUTION_USERS.MODIFIED_TIMESTAMP IS 'Data ostatniej modyfikacji rekordu'; 

----------------------------
--GRF_ROLES
----------------------------

CREATE TABLE APP_PBE.GRF_ROLES(
  CODE	VARCHAR2(50 BYTE)	NOT NULL,
  DESCRIPTION	VARCHAR2(300 BYTE),
  CONTEXT VARCHAR2(10) NOT NULL
);

BEGIN
  dbms_output.put_line(SYS.PK_ADMIN.F_GRANT_TO_EAGLE('APP_PBE', 'EAGLE', 'GRF_ROLES', 'ALL')); 
  dbms_output.put_line(SYS.PK_ADMIN.F_GRANT_TO_EAGLE('APP_PBE', 'SRV_EE', 'GRF_ROLES', 'ALL'));   
  dbms_output.put_line(SYS.PK_ADMIN.F_GRANT_TO_EAGLE('APP_PBE', 'DEVELOPER', 'GRF_ROLES', 'SELECT'));      
END;
/

-- Indeksy
CREATE UNIQUE INDEX APP_PBE.GRF_ROLES_PK ON APP_PBE.GRF_ROLES (CODE);

--klucze
ALTER TABLE APP_PBE.GRF_ROLES ADD CONSTRAINT GRF_ROLES_PK PRIMARY KEY (CODE);

-- Komentarze
COMMENT ON TABLE APP_PBE.GRF_ROLES IS '@Author(Jakub.Bentyn); @Project(Gryf-PBE); @Date(2016-10-05) ;@Purpose(Tabela przechowuj¹ca role u¿ytkowników IS);';

COMMENT ON COLUMN APP_PBE.GRF_ROLES.CODE IS 'Nazwa roli';  
COMMENT ON COLUMN APP_PBE.GRF_ROLES.DESCRIPTION IS 'Opis roli'; 
COMMENT ON COLUMN APP_PBE.GRF_ROLES.CONTEXT IS 'Kontekst w jakim u¿ywana jest rola. TRIN - kontekst instytucji szkoleniowej'; 
----------------------------
--GRF_PRIVILEGES
----------------------------

CREATE TABLE APP_PBE.GRF_PRIVILEGES(
  CODE	VARCHAR2(50 BYTE)	NOT NULL,
  DESCRIPTION	VARCHAR2(300 BYTE),
  CONTEXT VARCHAR2(10) NOT NULL
);

BEGIN
  dbms_output.put_line(SYS.PK_ADMIN.F_GRANT_TO_EAGLE('APP_PBE', 'EAGLE', 'GRF_PRIVILEGES', 'ALL')); 
  dbms_output.put_line(SYS.PK_ADMIN.F_GRANT_TO_EAGLE('APP_PBE', 'SRV_EE', 'GRF_PRIVILEGES', 'ALL'));   
  dbms_output.put_line(SYS.PK_ADMIN.F_GRANT_TO_EAGLE('APP_PBE', 'DEVELOPER', 'GRF_PRIVILEGES', 'SELECT'));      
END;
/

-- indeksy
CREATE UNIQUE INDEX APP_PBE.GRF_PRIVS_PK ON APP_PBE.GRF_PRIVILEGES (CODE);

-- klucze
ALTER TABLE APP_PBE.GRF_PRIVILEGES ADD CONSTRAINT GRF_PRIVS_PK PRIMARY KEY (CODE);

--komentarze
COMMENT ON TABLE APP_PBE.GRF_PRIVILEGES IS '@Author(Jakub.Bentyn); @Project(Gryf-PBE); @Date(2016-10-05) ;@Purpose(Tabela przechowuj¹ca uprawnienia bezpieczeñstwa uzytkowników IS);';

COMMENT ON COLUMN APP_PBE.GRF_PRIVILEGES.CODE IS 'Nazwa uprawnienia bezpieczeñstwa'; 
COMMENT ON COLUMN APP_PBE.GRF_PRIVILEGES.DESCRIPTION IS 'Opis uprawnienia';
COMMENT ON COLUMN APP_PBE.GRF_PRIVILEGES.CONTEXT IS 'Kontekst w jakim u¿ywana jest przywilej. TRIN - kontekst instytucji szkoleniowej'; 


--------------------
--TRIN_USERS_IN_ROLE
--------------------

CREATE TABLE APP_PBE.TRIN_USERS_IN_ROLE(
  TRIN_USER_ID	NUMBER NOT NULL,	
  TRIN_GRF_ROLE_CODE	VARCHAR2(50 BYTE) NOT NULL	
);

BEGIN
  dbms_output.put_line(SYS.PK_ADMIN.F_GRANT_TO_EAGLE('APP_PBE', 'EAGLE', 'TRIN_USERS_IN_ROLE', 'ALL')); 
  dbms_output.put_line(SYS.PK_ADMIN.F_GRANT_TO_EAGLE('APP_PBE', 'SRV_EE', 'TRIN_USERS_IN_ROLE', 'ALL'));   
  dbms_output.put_line(SYS.PK_ADMIN.F_GRANT_TO_EAGLE('APP_PBE', 'DEVELOPER', 'TRIN_USERS_IN_ROLE', 'SELECT'));      
END;
/
-- indeksy
CREATE UNIQUE INDEX APP_PBE.TRIN_USR_ROLE_PK ON APP_PBE.TRIN_USERS_IN_ROLE (TRIN_USER_ID, TRIN_GRF_ROLE_CODE);

-- Klucze
ALTER TABLE APP_PBE.TRIN_USERS_IN_ROLE ADD CONSTRAINT TRIN_USR_ROLE_PK PRIMARY KEY (TRIN_USER_ID, TRIN_GRF_ROLE_CODE);
--FK
ALTER TABLE APP_PBE.TRIN_USERS_IN_ROLE ADD CONSTRAINT TRIN_USR_ROLE_USER_FK FOREIGN KEY (TRIN_USER_ID) REFERENCES APP_PBE.TRAINING_INSTITUTION_USERS (ID);
ALTER TABLE APP_PBE.TRIN_USERS_IN_ROLE ADD CONSTRAINT TRIN_USR_ROLE_ROLE_FK FOREIGN KEY (TRIN_GRF_ROLE_CODE) REFERENCES APP_PBE.GRF_ROLES (CODE);

--komentarze
COMMENT ON TABLE APP_PBE.TRIN_USERS_IN_ROLE IS '@Author(Jakub.Bentyn); @Project(Gryf-PBE); @Date(2016-10-05) ;@Purpose(Tabela z³aczeniowa ról i  uzytkowników IS);';

COMMENT ON COLUMN APP_PBE.TRIN_USERS_IN_ROLE.TRIN_USER_ID	IS 'Id uzytkownika IS';	
COMMENT ON COLUMN APP_PBE.TRIN_USERS_IN_ROLE.TRIN_GRF_ROLE_CODE	IS 'Kod roli bezpieczeñstwa aplikacji IS';	

--------------------
--GRF_PRIVS_IN_ROLE
--------------------

CREATE TABLE APP_PBE.GRF_PRIVS_IN_ROLE(
  GRF_PRIV_CODE	VARCHAR2(50 BYTE) NOT NULL,	
  GRF_ROLE_CODE	VARCHAR2(50 BYTE) NOT NULL
);

BEGIN
  dbms_output.put_line(SYS.PK_ADMIN.F_GRANT_TO_EAGLE('APP_PBE', 'EAGLE', 'GRF_PRIVS_IN_ROLE', 'ALL')); 
  dbms_output.put_line(SYS.PK_ADMIN.F_GRANT_TO_EAGLE('APP_PBE', 'SRV_EE', 'GRF_PRIVS_IN_ROLE', 'ALL'));   
  dbms_output.put_line(SYS.PK_ADMIN.F_GRANT_TO_EAGLE('APP_PBE', 'DEVELOPER', 'GRF_PRIVS_IN_ROLE', 'SELECT'));      
END;
/

-- Indeksy
CREATE UNIQUE INDEX APP_PBE.GRF_PRIVS_ROLE_PK ON APP_PBE.GRF_PRIVS_IN_ROLE (GRF_PRIV_CODE, GRF_ROLE_CODE);

-- Klucze
ALTER TABLE APP_PBE.GRF_PRIVS_IN_ROLE ADD CONSTRAINT GRF_PRIVS_ROLE_PK PRIMARY KEY (GRF_PRIV_CODE, GRF_ROLE_CODE);
--FK
ALTER TABLE APP_PBE.GRF_PRIVS_IN_ROLE ADD CONSTRAINT PRIVS_ROLE_PRIV_FK FOREIGN KEY (GRF_PRIV_CODE) REFERENCES APP_PBE.GRF_PRIVILEGES (CODE);
ALTER TABLE APP_PBE.GRF_PRIVS_IN_ROLE ADD CONSTRAINT PRIVS_ROLE_ROLE_FK FOREIGN KEY (GRF_ROLE_CODE) REFERENCES APP_PBE.GRF_ROLES (CODE);

--komentarze
COMMENT ON TABLE APP_PBE.GRF_PRIVS_IN_ROLE IS '@Author(Jakub.Bentyn); @Project(Gryf-PBE); @Date(2016-10-05) ;@Purpose(Tabela z³aczeniowa ról i uprawnieñ bezpieczñstwa w aplikacji IS);';

COMMENT ON COLUMN APP_PBE.GRF_PRIVS_IN_ROLE.GRF_PRIV_CODE	IS 'Kod uprawnienia';	
COMMENT ON COLUMN APP_PBE.GRF_PRIVS_IN_ROLE.GRF_ROLE_CODE	IS 'Kod roli';
