

CREATE TABLE APP_PBE.PBE_PRODUCT_INSTANCE_POOL_E
(
	ID NUMBER NOT NULL,
	PRODUCT_INSTANCE_POOL_ID NUMBER(10) NOT NULL,
	TYPE_ID VARCHAR2(10 BYTE) NOT NULL,
	SOURCE_ID VARCHAR2(50 BYTE),
	NUM NUMBER(10),
	VERSION NUMBER NOT NULL,
	CREATED_USER VARCHAR2(100 BYTE) NOT NULL,
	CREATED_TIMESTAMP TIMESTAMP(6) NOT NULL,
	MODIFIED_USER VARCHAR2(100 BYTE) NOT NULL,
	MODIFIED_TIMESTAMP TIMESTAMP(6) NOT NULL
)
;

-- uprawnienia
BEGIN
  dbms_output.put_line(SYS.PK_ADMIN.F_GRANT_TO_EAGLE('APP_PBE', 'EAGLE', 'PBE_PRODUCT_INSTANCE_POOL_E', 'ALL'));
  dbms_output.put_line(SYS.PK_ADMIN.F_GRANT_TO_EAGLE('APP_PBE', 'SRV_EE', 'PBE_PRODUCT_INSTANCE_POOL_E', 'ALL'));
  dbms_output.put_line(SYS.PK_ADMIN.F_GRANT_TO_EAGLE('APP_PBE', 'DEVELOPER', 'PBE_PRODUCT_INSTANCE_POOL_E', 'SELECT'));
END;
/

-- Klucze
CREATE UNIQUE INDEX APP_PBE.PBE_PRD_IN_POL_EVN_PK ON APP_PBE.PBE_PRODUCT_INSTANCE_POOL_E (ID);
ALTER TABLE APP_PBE.PBE_PRODUCT_INSTANCE_POOL_E ADD CONSTRAINT PBE_PRD_IN_POL_EVN_PK PRIMARY KEY (ID);

-- Klucze obce
ALTER TABLE APP_PBE.PBE_PRODUCT_INSTANCE_POOL_E ADD CONSTRAINT PBE_PRD_INS_POL_EVE_FK FOREIGN KEY (PRODUCT_INSTANCE_POOL_ID) REFERENCES APP_PBE.PBE_PRODUCT_INSTANCE_POOLS (ID);
ALTER TABLE APP_PBE.PBE_PRODUCT_INSTANCE_POOL_E ADD CONSTRAINT PBE_PRD_INS_POL_EVE_TYP_FK FOREIGN KEY (TYPE_ID) REFERENCES APP_PBE.PBE_PRODUCT_INSTANCE_POOL_E_T (ID);

-- Komentarze
COMMENT ON TABLE APP_PBE.PBE_PRODUCT_INSTANCE_POOL_E IS '@Author(Adam Kmieciñski); @Project(GryfBonEl); @Date(2016-10-11);@Purpose(Tabela przechowuj¹ca dane instancji produktów);';
COMMENT ON COLUMN APP_PBE.PBE_PRODUCT_INSTANCE_POOL_E.ID IS 'ID zdarzenia instancji puli produktu. Klucz g³ówny';
COMMENT ON COLUMN APP_PBE.PBE_PRODUCT_INSTANCE_POOL_E.PRODUCT_INSTANCE_POOL_ID IS 'ID instancji puli produktów';
COMMENT ON COLUMN APP_PBE.PBE_PRODUCT_INSTANCE_POOL_E.TYPE_ID IS 'Kod rodzaju zdarzenia dla instancji. Wartoœæ s³ownikowa';
COMMENT ON COLUMN APP_PBE.PBE_PRODUCT_INSTANCE_POOL_E.SOURCE_ID IS 'ID obiektu Ÿród³owego dla zdarzenia - powi¹zanie z tabel¹ Ÿród³ow¹ wynika z rodzaju zdarzenia (np wydanie bêdzie zwi¹zane z zamówieniem itp.)';
COMMENT ON COLUMN APP_PBE.PBE_PRODUCT_INSTANCE_POOL_E.NUM IS 'Iloœæ zmienianyhc bonów na puli';
COMMENT ON COLUMN APP_PBE.PBE_PRODUCT_INSTANCE_POOL_E.VERSION IS 'Wersja. Kolumna techniczna u¿ywana do mechanizmu Optimistic Lock';
COMMENT ON COLUMN APP_PBE.PBE_PRODUCT_INSTANCE_POOL_E.CREATED_USER IS 'Login u¿ytkownika, który utworzy³ rekord';
COMMENT ON COLUMN APP_PBE.PBE_PRODUCT_INSTANCE_POOL_E.CREATED_TIMESTAMP IS 'Data utworzenia rekordu';
COMMENT ON COLUMN APP_PBE.PBE_PRODUCT_INSTANCE_POOL_E.MODIFIED_USER IS 'Login u¿ytkownika, który ostatnio modyfikowa³ rekord';
COMMENT ON COLUMN APP_PBE.PBE_PRODUCT_INSTANCE_POOL_E.MODIFIED_TIMESTAMP IS 'Data ostatniej modyfikacji rekordu';