ALTER TABLE APP_PBE.PBE_PRODUCT_INSTANCE_POOLS ADD CONSTRAINT PBE_PRO_INS_POL_PROD_FK FOREIGN KEY (PRD_ID) REFERENCES APP_PBE.PBE_PRODUCTS (PRD_ID);

ALTER TABLE APP_PBE.ORDERS ADD (PBE_PRD_ID VARCHAR2(20  BYTE));
ALTER TABLE APP_PBE.ORDERS ADD CONSTRAINT ORD_PBE_PRD_FK FOREIGN KEY (PBE_PRD_ID) REFERENCES APP_PBE.PBE_PRODUCTS (PRD_ID);
COMMENT ON COLUMN APP_PBE.ORDERS.PBE_PRD_ID IS 'Identyfikator produktu bonu elektornicznego';