

--PBE_PRODUCT_INSTANCE_E_T
update APP_PBE.PBE_PRODUCT_INSTANCE_E_T set ORDINAL = ORDINAL * 10;
insert into APP_PBE.PBE_PRODUCT_INSTANCE_E_T (ID, NAME, ORDINAL, SOURCE_TYPE) values ('REJECTRMB', 'Odrzucenie rozliczenia – zwolnienie bonów', 65, 'APP_PBE.E_REIMBERSMENTS');


--PBE_PRODUCT_INSTANCE_POOL_E_T
update APP_PBE.PBE_PRODUCT_INSTANCE_POOL_E_T set ORDINAL = ORDINAL * 10;
insert into APP_PBE.PBE_PRODUCT_INSTANCE_POOL_E_T (ID, NAME, ORDINAL, SOURCE_TYPE) values ('REJECTRMB', 'Odrzucenie rozliczenia – zwolnienie bonów', 55, 'APP_PBE.E_REIMBERSMENTS');
