CREATE TABLE APP_PBE.EMPLOYMENTS
(
	EMP_ID NUMBER NOT NULL,
	IND_ID NUMBER NOT NULL,
	ENT_ID NUMBER NOT NULL,
	VERSION NUMBER NOT NULL,
	CREATED_USER VARCHAR2(100) NOT NULL,
	CREATED_TIMESTAMP TIMESTAMP(6) NOT NULL,
	MODIFIED_USER VARCHAR2(100) NOT NULL,
	MODIFIED_TIMESTAMP TIMESTAMP(6) NOT NULL
)
;

-- uprawnienia
BEGIN
  dbms_output.put_line(SYS.PK_ADMIN.F_GRANT_TO_EAGLE('APP_PBE', 'EAGLE', 'EMPLOYMENTS', 'ALL'));
  dbms_output.put_line(SYS.PK_ADMIN.F_GRANT_TO_EAGLE('APP_PBE', 'SRV_EE', 'EMPLOYMENTS', 'ALL'));
  dbms_output.put_line(SYS.PK_ADMIN.F_GRANT_TO_EAGLE('APP_PBE', 'DEVELOPER', 'EMPLOYMENTS', 'SELECT'));
END;
/

-- Indeksy
CREATE UNIQUE INDEX APP_PBE.EMP_ID_PK ON APP_PBE.EMPLOYMENTS (EMP_ID);

-- Klucze
ALTER TABLE APP_PBE.EMPLOYMENTS
 ADD CONSTRAINT EMP_ID_PK
	PRIMARY KEY (EMP_ID)
;

ALTER TABLE APP_PBE.EMPLOYMENTS
 ADD CONSTRAINT EMPLOYMENT_ENT_ID_FK
	FOREIGN KEY (ENT_ID) REFERENCES APP_PBE.ENTERPRISES (ID)
;

ALTER TABLE APP_PBE.EMPLOYMENTS
 ADD CONSTRAINT EMPLOYMENT_IND_ID_FK
	FOREIGN KEY (IND_ID) REFERENCES APP_PBE.INDIVIDUALS (ID)
;

-- Komentarze
COMMENT ON TABLE APP_PBE.EMPLOYMENTS IS '@Author(Adam Kmieciñski); @Project(Gryf-PBE); @Date(2016-10-28) ;@Purpose(Tabela reprezentuj¹ca powi¹zania pomiêdzy MŒP a Osobó fizyczn¹);';

COMMENT ON COLUMN APP_PBE.EMPLOYMENTS.EMP_ID IS 'Unikalne ID. Klucz sztuczny';
COMMENT ON COLUMN APP_PBE.EMPLOYMENTS.IND_ID IS 'ID osoby fizycznej';
COMMENT ON COLUMN APP_PBE.EMPLOYMENTS.ENT_ID IS 'ID instytucji szkoleniowej';
COMMENT ON COLUMN APP_PBE.EMPLOYMENTS.VERSION IS 'Wersja. Kolumna techniczna u¿ywana do mechanizmu Optimistic Lock';
COMMENT ON COLUMN APP_PBE.EMPLOYMENTS.CREATED_USER IS 'Login u¿ytkownika, który utworzy³ rekord';
COMMENT ON COLUMN APP_PBE.EMPLOYMENTS.CREATED_TIMESTAMP IS 'Data utworzenia rekordu';
COMMENT ON COLUMN APP_PBE.EMPLOYMENTS.MODIFIED_USER IS 'Login u¿ytkownika, który ostatnio modyfikowa³ rekord';
COMMENT ON COLUMN APP_PBE.EMPLOYMENTS.MODIFIED_TIMESTAMP IS 'Data ostatniej modyfikacji rekordu';