CREATE TABLE APP_PBE.PBE_PRODUCT_EMISSIONS
(
	PRE_ID NUMBER NOT NULL,
	PRD_ID VARCHAR2(20) NOT NULL,
	GRP_ID NUMBER,
	NAME VARCHAR2(100) NOT NULL,
	DESCRIPTION VARCHAR2(200),
	EMISSION_DATE DATE NOT NULL,
	QUANTITY NUMBER(10) NOT NULL,
	VERSION NUMBER NOT NULL,
	CREATED_USER VARCHAR2(100) NOT NULL,
	CREATED_TIMESTAMP TIMESTAMP(6) NOT NULL,
	MODIFIED_USER VARCHAR2(100),
	MODIFIED_TIMESTAMP TIMESTAMP(6)
)
;

-- uprawnienia
BEGIN
  dbms_output.put_line(SYS.PK_ADMIN.F_GRANT_TO_EAGLE('APP_PBE', 'EAGLE', 'PBE_PRODUCT_EMISSIONS', 'ALL'));
  dbms_output.put_line(SYS.PK_ADMIN.F_GRANT_TO_EAGLE('APP_PBE', 'SRV_EE', 'PBE_PRODUCT_EMISSIONS', 'ALL'));
  dbms_output.put_line(SYS.PK_ADMIN.F_GRANT_TO_EAGLE('APP_PBE', 'DEVELOPER', 'PBE_PRODUCT_EMISSIONS', 'SELECT'));
END;
/

-- Indeksy
CREATE UNIQUE INDEX APP_PBE.PBE_PRD_EM_PK ON APP_PBE.PBE_PRODUCT_EMISSIONS (PRE_ID);

-- Klucze
ALTER TABLE APP_PBE.PBE_PRODUCT_EMISSIONS 
 ADD CONSTRAINT PBE_PRD_EM_PK
	PRIMARY KEY (PRE_ID)
;

ALTER TABLE APP_PBE.PBE_PRODUCT_EMISSIONS 
 ADD CONSTRAINT GRT_PRG_FK
	FOREIGN KEY (GRP_ID) REFERENCES APP_PBE.GRANT_PROGRAMS (ID)
;

ALTER TABLE APP_PBE.PBE_PRODUCT_EMISSIONS 
 ADD CONSTRAINT PBE_PRD_FK
	FOREIGN KEY (PRD_ID) REFERENCES APP_PBE.PBE_PRODUCTS (PRD_ID)
;

-- Komentarze
COMMENT ON TABLE APP_PBE.PBE_PRODUCT_EMISSIONS IS '@Author(Adam Kmieciñski); @Project(GryfBonEl); @Date(2016-10-10);@Purpose(Tabela przechowuj¹ca podstawowe dane dotycz¹ce emisji produktów);';

COMMENT ON COLUMN APP_PBE.PBE_PRODUCT_EMISSIONS.PRE_ID IS 'Unikalne ID emisji. Klucz g³ówny';
COMMENT ON COLUMN APP_PBE.PBE_PRODUCT_EMISSIONS.PRD_ID IS 'ID produktu';
COMMENT ON COLUMN APP_PBE.PBE_PRODUCT_EMISSIONS.GRP_ID IS 'ID programu dofinansowania';
COMMENT ON COLUMN APP_PBE.PBE_PRODUCT_EMISSIONS.NAME IS 'Nazwa emisji';
COMMENT ON COLUMN APP_PBE.PBE_PRODUCT_EMISSIONS.DESCRIPTION IS 'Opis emisji';
COMMENT ON COLUMN APP_PBE.PBE_PRODUCT_EMISSIONS.EMISSION_DATE IS 'Data emisji';
COMMENT ON COLUMN APP_PBE.PBE_PRODUCT_EMISSIONS.QUANTITY IS 'Iloœæ wygenerowanych produktów';
COMMENT ON COLUMN APP_PBE.PBE_PRODUCT_EMISSIONS.VERSION IS 'Wersja. Kolumna techniczna u¿ywana do mechanizmu Optimistic Lock';
COMMENT ON COLUMN APP_PBE.PBE_PRODUCT_EMISSIONS.CREATED_USER IS 'Login u¿ytkownika, który utworzy³ rekord';
COMMENT ON COLUMN APP_PBE.PBE_PRODUCT_EMISSIONS.CREATED_TIMESTAMP IS 'Data utworzenia rekordu';
COMMENT ON COLUMN APP_PBE.PBE_PRODUCT_EMISSIONS.MODIFIED_USER IS 'Login u¿ytkownika, który ostatnio modyfikowa³ rekord';
COMMENT ON COLUMN APP_PBE.PBE_PRODUCT_EMISSIONS.MODIFIED_TIMESTAMP IS 'Data ostatniej modyfikacji rekordu';