
--TRAINING_INSTANCE_STATUSES
insert into APP_PBE.TI_TRAINING_INSTANCE_STATUSES (ID, NAME, ORDINAL) values ('RES', 'Zarezerwowane', 1);
insert into APP_PBE.TI_TRAINING_INSTANCE_STATUSES (ID, NAME, ORDINAL) values ('DONE', 'Odbyte', 2);
insert into APP_PBE.TI_TRAINING_INSTANCE_STATUSES (ID, NAME, ORDINAL) values ('REIMB', 'Rozliczone', 3);
insert into APP_PBE.TI_TRAINING_INSTANCE_STATUSES (ID, NAME, ORDINAL) values ('CANCEL', 'Anulowane', 4);


--PBE_PRODUCT_INSTANCE_STATUSES
insert into APP_PBE.PBE_PRODUCT_INSTANCE_STATUSES (ID, NAME, ORDINAL) values ('EMITTED', 'Wyemitowany', 1);
insert into APP_PBE.PBE_PRODUCT_INSTANCE_STATUSES (ID, NAME, ORDINAL) values ('ASSIGNED', 'Przypisane', 2);
insert into APP_PBE.PBE_PRODUCT_INSTANCE_STATUSES (ID, NAME, ORDINAL) values ('RESERVED', 'Zarezerwowany', 3);
insert into APP_PBE.PBE_PRODUCT_INSTANCE_STATUSES (ID, NAME, ORDINAL) values ('USED', 'Wykorzystany', 4);
insert into APP_PBE.PBE_PRODUCT_INSTANCE_STATUSES (ID, NAME, ORDINAL) values ('REIMBD', 'Rozliczony', 5);
insert into APP_PBE.PBE_PRODUCT_INSTANCE_STATUSES (ID, NAME, ORDINAL) values ('EXPIRED', 'Wygas³e', 6);


--PBE_PRODUCT_INSTANCE_E_T
insert into APP_PBE.PBE_PRODUCT_INSTANCE_E_T (ID, NAME, ORDINAL, SOURCE_TYPE) values ('EMISSION', 'Emisja', 1, 'APP_PBE.PBE_PRODUCT_EMISSIONS');
insert into APP_PBE.PBE_PRODUCT_INSTANCE_E_T (ID, NAME, ORDINAL, SOURCE_TYPE) values ('ASSIGNMENT', 'Przypisanie', 2, 'APP_PBE.ORDERS');
insert into APP_PBE.PBE_PRODUCT_INSTANCE_E_T (ID, NAME, ORDINAL, SOURCE_TYPE) values ('RESRVATION', 'Rezerwacja', 3, 'APP_PBE.TRAINING_INSTANCES');
insert into APP_PBE.PBE_PRODUCT_INSTANCE_E_T (ID, NAME, ORDINAL, SOURCE_TYPE) values ('UNRSRVATON', 'Zdjêcie rezerwacji', 4, 'APP_PBE.TRAINING_INSTANCES');
insert into APP_PBE.PBE_PRODUCT_INSTANCE_E_T (ID, NAME, ORDINAL, SOURCE_TYPE) values ('USE', 'Wykorzystanie', 5, 'APP_PBE.TRAINING_INSTANCES');
insert into APP_PBE.PBE_PRODUCT_INSTANCE_E_T (ID, NAME, ORDINAL, SOURCE_TYPE) values ('REIMB', 'Rozliczenie', 6, 'APP_PBE.E_REIMBERSMENTS');
insert into APP_PBE.PBE_PRODUCT_INSTANCE_E_T (ID, NAME, ORDINAL, SOURCE_TYPE) values ('EXPIRATION', 'Wygaœniêcie', 7, 'APP_PBE.E_REIMBERSMENTS');


--PBE_PRODUCT_INSTANCE_POOL_E_T
insert into APP_PBE.PBE_PRODUCT_INSTANCE_POOL_E_T (ID, NAME, ORDINAL, SOURCE_TYPE) values ('ASSIGNMENT', 'Przypisanie', 1, 'APP_PBE.ORDERS');
insert into APP_PBE.PBE_PRODUCT_INSTANCE_POOL_E_T (ID, NAME, ORDINAL, SOURCE_TYPE) values ('RESRVATION', 'Rezerwacja', 2, 'APP_PBE.TRAINING_INSTANCES');
insert into APP_PBE.PBE_PRODUCT_INSTANCE_POOL_E_T (ID, NAME, ORDINAL, SOURCE_TYPE) values ('UNRSRVATON', 'Zdjêcie rezerwacji', 3, 'APP_PBE.TRAINING_INSTANCES');
insert into APP_PBE.PBE_PRODUCT_INSTANCE_POOL_E_T (ID, NAME, ORDINAL, SOURCE_TYPE) values ('USE', 'Wykorzystanie', 4, 'APP_PBE.TRAINING_INSTANCES');
insert into APP_PBE.PBE_PRODUCT_INSTANCE_POOL_E_T (ID, NAME, ORDINAL, SOURCE_TYPE) values ('REIMB', 'Rozliczenie', 5, 'APP_PBE.E_REIMBERSMENTS');
insert into APP_PBE.PBE_PRODUCT_INSTANCE_POOL_E_T (ID, NAME, ORDINAL, SOURCE_TYPE) values ('EXPIRATION', 'Wygaœniêcie', 6, 'APP_PBE.E_REIMBERSMENTS');


