ALTER TABLE APP_PBE.ORDER_INVOICES ADD (INDIVIDUAL_ID NUMBER  NOT NULL);
ALTER TABLE APP_PBE.ORDER_INVOICES ADD CONSTRAINT ORD_INV_IND_FK FOREIGN KEY (INDIVIDUAL_ID) REFERENCES APP_PBE.INDIVIDUALS (ID);
COMMENT ON COLUMN APP_PBE.ORDER_INVOICES.INDIVIDUAL_ID IS 'Identyfikator u¿ytkownika indywidualnego';

ALTER TABLE APP_PBE.ORDER_INVOICES ADD (ENTERPRISE_ID NUMBER);
ALTER TABLE APP_PBE.ORDER_INVOICES ADD CONSTRAINT ORD_INV_ENT_FK FOREIGN KEY (ENTERPRISE_ID) REFERENCES APP_PBE.ENTERPRISES (ID);
COMMENT ON COLUMN APP_PBE.ORDER_INVOICES.ENTERPRISE_ID IS 'Identyfikator MŒP';

ALTER TABLE APP_PBE.ORDER_INVOICES ADD (WUP_DEBT_DOC_NO VARCHAR2(30 BYTE));
COMMENT ON COLUMN APP_PBE.ORDER_INVOICES.WUP_DEBT_DOC_NO IS 'Dodatkowy numer umowy - Numer dokumentu na przysz³e nale¿noœci WUP';