

CREATE TABLE APP_PBE.TI_TRAINING_CATEGORY_CAT_GR_PR
(
  ID NUMBER NOT NULL,
  CATALOG_ID VARCHAR2(10  BYTE) NOT NULL,
  GRANT_PROGRAM_ID NUMBER NOT NULL,
  DATE_FROM DATE,
  DATE_TO DATE
);

-- uprawnienia
BEGIN
  dbms_output.put_line(SYS.PK_ADMIN.F_GRANT_TO_EAGLE('APP_PBE', 'EAGLE', 'TI_TRAINING_CATEGORY_CAT_GR_PR', 'ALL'));
  dbms_output.put_line(SYS.PK_ADMIN.F_GRANT_TO_EAGLE('APP_PBE', 'SRV_EE', 'TI_TRAINING_CATEGORY_CAT_GR_PR', 'ALL'));
  dbms_output.put_line(SYS.PK_ADMIN.F_GRANT_TO_EAGLE('APP_PBE', 'DEVELOPER', 'TI_TRAINING_CATEGORY_CAT_GR_PR', 'SELECT'));
END;
/

-- Klucze
CREATE UNIQUE INDEX APP_PBE.TI_TRA_CAT_CAT_GR_PR_PK ON APP_PBE.TI_TRAINING_CATEGORY_CAT_GR_PR (ID);
ALTER TABLE APP_PBE.TI_TRAINING_CATEGORY_CAT_GR_PR ADD CONSTRAINT TI_TRA_CAT_CAT_GR_PR_PK PRIMARY KEY (ID);

-- Klucze obce
ALTER TABLE APP_PBE.TI_TRAINING_CATEGORY_CAT_GR_PR ADD CONSTRAINT TI_TRA_CAT_CAT_GR_PR_CATAL_FK FOREIGN KEY (CATALOG_ID) REFERENCES APP_PBE.TI_TRAINING_CATEGORY_CAT (ID);
ALTER TABLE APP_PBE.TI_TRAINING_CATEGORY_CAT_GR_PR ADD CONSTRAINT TI_TRA_CAT_CAT_GR_PR_GRA_PR_FK FOREIGN KEY (GRANT_PROGRAM_ID) REFERENCES APP_PBE.GRANT_PROGRAMS (ID);

-- Komentarze
COMMENT ON TABLE APP_PBE.TI_TRAINING_CATEGORY_CAT_GR_PR IS '@Author(Tomasz Bilski); @Project(GryfBonEl); @Date(2016-11-05);@Purpose(Tabel ³¹cz¹ca katalog szkoleñ i program dofinansowania w danych datach);';
COMMENT ON COLUMN APP_PBE.TI_TRAINING_CATEGORY_CAT_GR_PR.ID IS 'Klucz g³ówny';
COMMENT ON COLUMN APP_PBE.TI_TRAINING_CATEGORY_CAT_GR_PR.CATALOG_ID IS 'Indetyfikator katalogu szkoleñ';
COMMENT ON COLUMN APP_PBE.TI_TRAINING_CATEGORY_CAT_GR_PR.GRANT_PROGRAM_ID IS 'Indetyfikator programu dofinansowania';
COMMENT ON COLUMN APP_PBE.TI_TRAINING_CATEGORY_CAT_GR_PR.DATE_FROM IS 'Data od której obowi¹zywuje po³¹czenie';
COMMENT ON COLUMN APP_PBE.TI_TRAINING_CATEGORY_CAT_GR_PR.DATE_TO IS 'Data do której obowi¹zywuje po³¹czenie';

