

--PBE_PRODUCT_INSTANCE_STATUSES
insert into APP_PBE.PBE_PRODUCT_INSTANCE_STATUSES (ID, NAME, ORDINAL) values ('RET', 'Zwrócony', 7);

--PBE_PRODUCT_INSTANCE_E_T
insert into APP_PBE.PBE_PRODUCT_INSTANCE_E_T (ID, NAME, ORDINAL, SOURCE_TYPE) values ('RETURN', 'Zwrot', 90, 'APP_PBE.E_REIMBERSMENTS');

--PBE_PRODUCT_INSTANCE_POOL_E_T
insert into APP_PBE.PBE_PRODUCT_INSTANCE_POOL_E_T (ID, NAME, ORDINAL, SOURCE_TYPE) values ('RETURN', 'Zwrot', 80, 'APP_PBE.E_REIMBERSMENTS');


