CREATE TABLE APP_PBE.E_REIMBURSEMENT_REPORTS
(
  ID NUMBER NOT NULL,
  E_REIMBURSEMENT_ID NUMBER NOT NULL,
  TYPE_NAME VARCHAR(100) NOT NULL,
  FILE_LOCATION VARCHAR2(250) NOT NULL,
  VERSION NUMBER NOT NULL,
  CREATED_USER VARCHAR2(30 BYTE) NOT NULL,
  CREATED_TIMESTAMP TIMESTAMP(6) NOT NULL,
  MODIFIED_USER VARCHAR2(30 BYTE) NOT NULL,
  MODIFIED_TIMESTAMP TIMESTAMP(6) NOT NULL
);

BEGIN
  dbms_output.put_line(SYS.PK_ADMIN.F_GRANT_TO_EAGLE('APP_PBE', 'EAGLE', 'E_REIMBURSEMENT_REPORTS', 'ALL'));
  dbms_output.put_line(SYS.PK_ADMIN.F_GRANT_TO_EAGLE('APP_PBE', 'SRV_EE', 'E_REIMBURSEMENT_REPORTS', 'ALL'));
  dbms_output.put_line(SYS.PK_ADMIN.F_GRANT_TO_EAGLE('APP_PBE', 'DEVELOPER', 'E_REIMBURSEMENT_REPORTS', 'SELECT'));
END;
/

-- Klucze
CREATE UNIQUE INDEX APP_PBE.E_REIMB_REP_PK ON APP_PBE.E_REIMBURSEMENT_REPORTS (ID);
ALTER TABLE APP_PBE.E_REIMBURSEMENT_REPORTS ADD CONSTRAINT E_REIMB_REP_PK PRIMARY KEY (ID);

--KLUCZE OBCE
ALTER TABLE APP_PBE.E_REIMBURSEMENT_REPORTS ADD CONSTRAINT E_REIMB_REP_E_REIMB_FK FOREIGN KEY (E_REIMBURSEMENT_ID) REFERENCES APP_PBE.E_REIMBURSEMENTS (ID);

COMMENT ON TABLE APP_PBE.E_REIMBURSEMENT_REPORTS IS '@Author(Adam Kmieciñski); @Project(GryfBonEl); @Date(2016-12-21);@Purpose(Tabela z raportami wygenerowanymi dla rozliczenia);';
COMMENT ON COLUMN APP_PBE.E_REIMBURSEMENT_REPORTS.ID IS 'Identyfikator klucz sztuczny';
COMMENT ON COLUMN APP_PBE.E_REIMBURSEMENT_REPORTS.E_REIMBURSEMENT_ID IS 'Identyfikator rozliczenia elektronicznego';
COMMENT ON COLUMN APP_PBE.E_REIMBURSEMENT_REPORTS.TYPE_NAME IS 'Identyfikator umowy';
COMMENT ON COLUMN APP_PBE.E_REIMBURSEMENT_REPORTS.FILE_LOCATION IS 'Numer umowy';
COMMENT ON COLUMN APP_PBE.E_REIMBURSEMENT_REPORTS.VERSION IS 'Wersja. Kolumna techniczna u¿ywana do mechanizmu Optimistic Lock';
COMMENT ON COLUMN APP_PBE.E_REIMBURSEMENT_REPORTS.CREATED_USER IS 'Login u¿ytkownika, który utworzy³ rekord';
COMMENT ON COLUMN APP_PBE.E_REIMBURSEMENT_REPORTS.CREATED_TIMESTAMP IS 'Data utworzenia rekordu';
COMMENT ON COLUMN APP_PBE.E_REIMBURSEMENT_REPORTS.MODIFIED_USER IS 'Login u¿ytkownika, który ostatnio modyfikowa³ rekord';
COMMENT ON COLUMN APP_PBE.E_REIMBURSEMENT_REPORTS.MODIFIED_TIMESTAMP IS 'Data ostatniej modyfikacji rekordu';
