-- dodanie nowych uprawnieñ

INSERT INTO EAGLE.ADM_USER_GROUPS VALUES('GRF_PBE_TI_TRAININGS', 'Przegl¹d szkolen', 'A', 'Podgl¹d danych zwi¹zanych ze szkoleniami');
INSERT INTO EAGLE.ADM_USER_GROUPS VALUES('GRF_PBE_TI_TRAININGS_MOD', 'Tworzenie i edycja szkoleñ', 'A', 'Tworzenie i modyfikacja danych dotycz¹cych szkoleñ');

INSERT INTO EAGLE.ADM_USER_GROUPS VALUES('GRF_PBE_ASYNCH_JOBS', 'Przegl¹d zadañ', 'A', 'Podgl¹d danych zwi¹zanych z asynchronicznymi zadaniami');
INSERT INTO EAGLE.ADM_USER_GROUPS VALUES('GRF_PBE_DATA_IMPORT_MOD', 'Tworzenie zadañ importu', 'A', 'Tworzenie zadañ zwi¹zanych z asynchronicznym importem danych z plików');

INSERT INTO EAGLE.ADM_USER_GROUPS VALUES('GRF_INDIVIDUALS', 'Przegl¹d osób fizycznych', 'A', 'Podgl¹d danych zwi¹zanych z osobami fizycznymi');
INSERT INTO EAGLE.ADM_USER_GROUPS VALUES('GRF_INDIVIDUAL_MOD', 'Tworzenie i edycja osób fizycznych', 'A', 'Tworzenie i modyfikacja danych zwi¹zanych z osobami fizycznymi');
INSERT INTO EAGLE.ADM_USER_GROUPS VALUES('GRF_INDIVIDUAL_REPAY_ACC_MOD', 'Zwrot œrodków', 'A', 'Wykonywanie akcji zwrotu œrodków osobie fizycznej');

INSERT INTO EAGLE.ADM_USER_GROUPS VALUES('GRF_PBE_TI_TRAINING_INSTANCES', 'Przegl¹d instancji szkolenia', 'A', 'Podgl¹d danych zwi¹zanych z instancjami szkoleñ');
INSERT INTO EAGLE.ADM_USER_GROUPS VALUES('GRF_PBE_TI_TRAINING_INSTANCES_MOD', 'Edycja instancji szkoleñ', 'A', 'Modyfikacja danych dotycz¹cych instancji szkoleñ');

INSERT INTO EAGLE.ADM_USER_GROUPS VALUES('GRF_PBE_CONTRACTS', 'Przegl¹d umów', 'A', 'Podgl¹d danych zwi¹zanych z umowami');
INSERT INTO EAGLE.ADM_USER_GROUPS VALUES('GRF_PBE_CONTRACTS_MOD', 'Tworzenie i edycja umów', 'A', 'Tworzenie i modyfikacja danych dotycz¹cych umów dla MŒP lub osób fizycznych');

INSERT INTO EAGLE.ADM_USER_GROUPS VALUES('GRF_PBE_ORDERS_CREATE', 'Tworzenie zamówieñ', 'A', 'Tworzenie zamówieñ na podstawie umów');
INSERT INTO EAGLE.ADM_USER_GROUPS VALUES('GRF_PBE_ORDERS_CONFIRM_PAYMENT', 'Weryfikacja p³atnoœci', 'A', 'Weryfikacja p³atnoœci za zamówienia');
INSERT INTO EAGLE.ADM_USER_GROUPS VALUES('GRF_PBE_ORDERS_PROCESS', 'Weryfikacja/Realizacja zamówienia', 'A', 'Weryfikacja i realizacja zamówienia');
INSERT INTO EAGLE.ADM_USER_GROUPS VALUES('GRF_PBE_ORDERS_SEND', 'Wysy³ka zamówienia', 'A', 'Wysy³ka zamówienia');
INSERT INTO EAGLE.ADM_USER_GROUPS VALUES('GRF_PBE_ORDERS_CANCEL', 'Anulowanie zamówienia', 'A', 'Anulowanie zamówienia');

INSERT INTO EAGLE.ADM_USER_GROUPS VALUES('GRF_PBE_E_REIMBURSEMENTS', 'Przegl¹d rozliczeñ elektronicznych', 'A', 'Przegl¹d rozliczeñ zwi¹zanych z rezerwacj¹ szkoleñ');
INSERT INTO EAGLE.ADM_USER_GROUPS VALUES('GRF_PBE_E_REIMBURSEMENTS_MOD', 'Tworzenie i edycja rozliczeñ elektronicznych', 'A', 'Tworzenie i modyfikacja danych dotycz¹cych rozliczeñ elektronicznych');


-- przypisanie nowych uprawnieñ do grupy administracji

INSERT INTO EAGLE.ADM_GROUPS_IN_ROLES VALUES('ADM_ADMINISTRACJA', 'GRF_PBE_TI_TRAININGS');
INSERT INTO EAGLE.ADM_GROUPS_IN_ROLES VALUES('ADM_ADMINISTRACJA', 'GRF_PBE_TI_TRAININGS_MOD');

INSERT INTO EAGLE.ADM_GROUPS_IN_ROLES VALUES('ADM_ADMINISTRACJA', 'GRF_PBE_ASYNCH_JOBS');
INSERT INTO EAGLE.ADM_GROUPS_IN_ROLES VALUES('ADM_ADMINISTRACJA', 'GRF_PBE_DATA_IMPORT_MOD');

INSERT INTO EAGLE.ADM_GROUPS_IN_ROLES VALUES('ADM_ADMINISTRACJA', 'GRF_INDIVIDUALS');
INSERT INTO EAGLE.ADM_GROUPS_IN_ROLES VALUES('ADM_ADMINISTRACJA', 'GRF_INDIVIDUAL_MOD');
INSERT INTO EAGLE.ADM_GROUPS_IN_ROLES VALUES('ADM_ADMINISTRACJA', 'GRF_INDIVIDUAL_REPAY_ACC_MOD');

INSERT INTO EAGLE.ADM_GROUPS_IN_ROLES VALUES('ADM_ADMINISTRACJA', 'GRF_PBE_TI_TRAINING_INSTANCES');
INSERT INTO EAGLE.ADM_GROUPS_IN_ROLES VALUES('ADM_ADMINISTRACJA', 'GRF_PBE_TI_TRAINING_INSTANCES_MOD');

INSERT INTO EAGLE.ADM_GROUPS_IN_ROLES VALUES('ADM_ADMINISTRACJA', 'GRF_PBE_CONTRACTS');
INSERT INTO EAGLE.ADM_GROUPS_IN_ROLES VALUES('ADM_ADMINISTRACJA', 'GRF_PBE_CONTRACTS_MOD');

INSERT INTO EAGLE.ADM_GROUPS_IN_ROLES VALUES('ADM_ADMINISTRACJA', 'GRF_PBE_ORDERS_CREATE');
INSERT INTO EAGLE.ADM_GROUPS_IN_ROLES VALUES('ADM_ADMINISTRACJA', 'GRF_PBE_ORDERS_CONFIRM_PAYMENT');
INSERT INTO EAGLE.ADM_GROUPS_IN_ROLES VALUES('ADM_ADMINISTRACJA', 'GRF_PBE_ORDERS_PROCESS');
INSERT INTO EAGLE.ADM_GROUPS_IN_ROLES VALUES('ADM_ADMINISTRACJA', 'GRF_PBE_ORDERS_SEND');
INSERT INTO EAGLE.ADM_GROUPS_IN_ROLES VALUES('ADM_ADMINISTRACJA', 'GRF_PBE_ORDERS_CANCEL');

INSERT INTO EAGLE.ADM_GROUPS_IN_ROLES VALUES('ADM_ADMINISTRACJA', 'GRF_PBE_E_REIMBURSEMENTS');
INSERT INTO EAGLE.ADM_GROUPS_IN_ROLES VALUES('ADM_ADMINISTRACJA', 'GRF_PBE_E_REIMBURSEMENTS_MOD');