CREATE OR REPLACE TRIGGER APP_PBE.TRG_TI_TRAINING_INST_EXT_AUDIT
AFTER DELETE OR UPDATE ON APP_PBE.TI_TRAINING_INSTANCES_EXT
REFERENCING NEW AS NEW OLD AS OLD FOR EACH ROW
  DECLARE
    v_operation VARCHAR2(1) := 'U';
    v_user      VARCHAR2(30) := USER;
  BEGIN
    IF DELETING
    THEN v_operation := 'D'; END IF;
    IF USER IN ('SRV_EE', 'SRV_EE_TI', 'SRV_EE_IND') AND NOT DELETING
    THEN v_user := :NEW.MODIFIED_USER; END IF; -- w przypadku GRYF-a jest pula połączeń na użytkowniku SRV_EE
    INSERT INTO APP_PBE.TI_TRAINING_INSTANCES_EXT_AUDT (
      TI_EXTERNAL_ID,
      VAT_REG_NUM,
      TI_EXTERNAL_NAME,
      TRAINING_EXTERNAL_ID,
      TRAINING_NAME,
      START_DATE_STR,
      END_DATE_STR,
      PLACE,
      PRICE_STR,
      HOURS_NUMBER_STR,
      HOUR_PRICE_STR,
      TRAINING_CATEGORY_ID,
      CERTIFICATE_REMARK,
      IND_ORDER_EXTERNAL_ID,
      ORD_SEARCH_STRING,
      START_DATE,
      END_DATE,
      PRICE,
      HOURS_NUMBER,
      HOUR_PRICE,
      CREATED_USER,
      CREATED_TIMESTAMP,
      ID,
      TRAINING_ID,
      IMPORT_JOB_ID,
      VERSION,
      MODIFIED_USER,
      MODIFIED_TIMESTAMP,
      AUDIT_USER, AUDIT_TIMESTAMP, AUDIT_OPERATION)
    VALUES (
      :OLD.TI_EXTERNAL_ID,
      :OLD.VAT_REG_NUM,
      :OLD.TI_EXTERNAL_NAME,
      :OLD.TRAINING_EXTERNAL_ID,
      :OLD.TRAINING_NAME,
      :OLD.START_DATE_STR,
      :OLD.END_DATE_STR,
      :OLD.PLACE,
      :OLD.PRICE_STR,
      :OLD.HOURS_NUMBER_STR,
      :OLD.HOUR_PRICE_STR,
      :OLD.TRAINING_CATEGORY_ID,
      :OLD.CERTIFICATE_REMARK,
      :OLD.IND_ORDER_EXTERNAL_ID,
      :OLD.ORD_SEARCH_STRING,
      :OLD.START_DATE,
      :OLD.END_DATE,
      :OLD.PRICE,
      :OLD.HOURS_NUMBER,
      :OLD.HOUR_PRICE,
      :OLD.CREATED_USER,
      :OLD.CREATED_TIMESTAMP,
      :OLD.ID,
      :OLD.TRAINING_ID,
      :OLD.IMPORT_JOB_ID,
      :OLD.VERSION,
      :OLD.MODIFIED_USER,
      :OLD.MODIFIED_TIMESTAMP,
      v_user, SYSTIMESTAMP, v_operation);
    EXCEPTION
    WHEN OTHERS THEN
    EAGLE.PK_ERROR.RAISE_ERROR(sqlcode, sqlerrm, 'TRG_TI_TRAINING_INST_EXT_AUDIT');
  END TRG_TI_TRAINING_INST_EXT_AUDIT;