
Insert into APP_PBE.ORDER_FLOW_ELEMENT_TYPES (ID,DESCRIPTION,COMPONENT_NAME) values ('C_ORDPAY','Element z³o¿ony reprezentuj¹cy listê wp³at. Front: html i JS, Backend: serwisy, DTOsy do obs³ugi elementu z³o¿onego powo³ywane s¹ dynamicznie na podstawie nazwy przechowywanej w kolumnie COMPONENT_NAME','ComplexTypePaymentListInfo');
Insert into APP_PBE.ORDER_FLOW_ELEMENTS (ELEMENT_ID,ELEMENT_NAME,ELEMENT_TYPE_ID,ELEMENT_TYPE_PARAMS,ELEMENT_DESCRIPTION) values ('ORDPAY_KK','Informacje o wp³atach','C_ORDPAY',null,'Element z³o¿ony przetrzymuj¹cy informacje o wp³atach');


Insert into APP_PBE.ORDER_FLOW_ELEMENTS_IN_STATUS (STATUS_ID,ELEMENT_ID,POS,FLAGS,AUG_ID_REQUIRED,ALLOWED_DELAY_TYPE_ID) values ('NEWKK',       'ORDPAY_KK',39, null, null,null);
Insert into APP_PBE.ORDER_FLOW_ELEMENTS_IN_STATUS (STATUS_ID,ELEMENT_ID,POS,FLAGS,AUG_ID_REQUIRED,ALLOWED_DELAY_TYPE_ID) values ('PAIDKK',      'ORDPAY_KK',39, null, null,null);
Insert into APP_PBE.ORDER_FLOW_ELEMENTS_IN_STATUS (STATUS_ID,ELEMENT_ID,POS,FLAGS,AUG_ID_REQUIRED,ALLOWED_DELAY_TYPE_ID) values ('DOCGENKK',    'ORDPAY_KK',39, null, null,null);
Insert into APP_PBE.ORDER_FLOW_ELEMENTS_IN_STATUS (STATUS_ID,ELEMENT_ID,POS,FLAGS,AUG_ID_REQUIRED,ALLOWED_DELAY_TYPE_ID) values ('PROCESSDKK',  'ORDPAY_KK',39, null, null,null);
Insert into APP_PBE.ORDER_FLOW_ELEMENTS_IN_STATUS (STATUS_ID,ELEMENT_ID,POS,FLAGS,AUG_ID_REQUIRED,ALLOWED_DELAY_TYPE_ID) values ('SENTKK',      'ORDPAY_KK',39, null, null,null);
Insert into APP_PBE.ORDER_FLOW_ELEMENTS_IN_STATUS (STATUS_ID,ELEMENT_ID,POS,FLAGS,AUG_ID_REQUIRED,ALLOWED_DELAY_TYPE_ID) values ('EKSPORTKK',   'ORDPAY_KK',39, null, null,null);
Insert into APP_PBE.ORDER_FLOW_ELEMENTS_IN_STATUS (STATUS_ID,ELEMENT_ID,POS,FLAGS,AUG_ID_REQUIRED,ALLOWED_DELAY_TYPE_ID) values ('CANCELLDKK',  'ORDPAY_KK',39, null, null,null);
