CREATE TABLE APP_PBE.PBE_TRAINING
(
	TRA_ID NUMBER(8,2) NOT NULL,
	TRIN_ID NUMBER(8,2) NOT NULL,
	NAME VARCHAR2(200) NOT NULL,
	PRICE NUMBER(10,3) NOT NULL,
	START_DATE DATE NOT NULL,
	END_DATE DATE NOT NULL,
	PLACE VARCHAR2(200) NOT NULL,
	HOURS_NUMBER NUMBER(8,2) NOT NULL,
	HOUR_PRICE NUMBER(10,3) NOT NULL,
	TRC_CODE VARCHAR2(5) NOT NULL,
	CREATED_USER VARCHAR2(100) NOT NULL,
	CREATED_TIMESTAMP TIMESTAMP(6) NOT NULL,
	MODIFIED_USER VARCHAR2(100) NOT NULL,
	MODIFIED_TIMESTAMP TIMESTAMP(6) NOT NULL
);

-- constrainty i indeksy
CREATE UNIQUE INDEX APP_PBE.PBE_TRA_PK   
 ON APP_PBE.PBE_TRAINING (TRA_ID);
 
ALTER TABLE APP_PBE.PBE_TRAINING 
 ADD CONSTRAINT PBE_TRA_PK
	PRIMARY KEY (TRA_ID);
	
ALTER TABLE APP_PBE.PBE_TRAINING 
 ADD CONSTRAINT PBE_TRA_CAT_DIC_FK
	FOREIGN KEY (TRC_CODE) REFERENCES APP_PBE.PBE_TRAINING_CATEGORY_DICS (TRC_CODE);
	
ALTER TABLE APP_PBE.PBE_TRAINING 
 ADD CONSTRAINT PBE_TRIN_FK
	FOREIGN KEY (TRIN_ID) REFERENCES APP_PBE.TRAINING_INSTITUTIONS (ID);

-- uprawnienia
BEGIN
  dbms_output.put_line(SYS.PK_ADMIN.F_GRANT_TO_EAGLE('APP_PBE', 'EAGLE', 'PBE_TRAINING', 'ALL'));
  dbms_output.put_line(SYS.PK_ADMIN.F_GRANT_TO_EAGLE('APP_PBE', 'SRV_EE', 'PBE_TRAINING', 'ALL'));
  dbms_output.put_line(SYS.PK_ADMIN.F_GRANT_TO_EAGLE('APP_PBE', 'DEVELOPER', 'PBE_TRAINING', 'SELECT'));
END;
/

-- komentarze
COMMENT ON TABLE APP_PBE.PBE_TRAINING IS '@Author(Krzysztof Antczak); @Project(Gryf-PBE); @Date(2016-10-25);@Purpose(Tabela przechowuj¹ca dane dotycz¹ce szkoleñ organizowanych przez IS);';
COMMENT ON COLUMN APP_PBE.PBE_TRAINING.TRA_ID IS 'Identyfikator szkolenia';
COMMENT ON COLUMN APP_PBE.PBE_TRAINING.TRIN_ID IS 'Identyfikator instytucji szkoleniowej';
COMMENT ON COLUMN APP_PBE.PBE_TRAINING.NAME IS 'Nazwa szkolenia';
COMMENT ON COLUMN APP_PBE.PBE_TRAINING.PRICE IS 'Cena szkolenia';
COMMENT ON COLUMN APP_PBE.PBE_TRAINING.START_DATE IS 'Data rozpoczêcia szkolenia';
COMMENT ON COLUMN APP_PBE.PBE_TRAINING.END_DATE IS 'Data zakoñczenia szkolenia';
COMMENT ON COLUMN APP_PBE.PBE_TRAINING.PLACE IS 'Miejsce szkolenia';
COMMENT ON COLUMN APP_PBE.PBE_TRAINING.HOURS_NUMBER IS 'Liczba godzin szkolenia';
COMMENT ON COLUMN APP_PBE.PBE_TRAINING.HOUR_PRICE IS 'Cena za godzinê szkolenia';
COMMENT ON COLUMN APP_PBE.PBE_TRAINING.TRC_CODE IS 'Kod kategorii szkolenia';
COMMENT ON COLUMN APP_PBE.PBE_TRAINING.CREATED_USER IS 'Nazwa u¿ytkownika, który utworzy³ rekord';
COMMENT ON COLUMN APP_PBE.PBE_TRAINING.CREATED_TIMESTAMP IS 'Data i czas momentu utworzenia rekordu';
COMMENT ON COLUMN APP_PBE.PBE_TRAINING.MODIFIED_USER IS 'Nazwa u¿ytkownika, który ostatnio modyfikowa³ rekord';
COMMENT ON COLUMN APP_PBE.PBE_TRAINING.MODIFIED_TIMESTAMP IS 'Data i czas ostatniej modyfikacji rekordu';
