INSERT INTO APP_PBE.TI_TRAINING_CATEGORIES (ID, NAME, ORDINAL, PARENT_ID, CATALOG_ID) VALUES ('MOTO', 'Inne certyfikowane - motoryzacja', 5, null, 'CAT_KK');
INSERT INTO APP_PBE.TI_TRAINING_CATEGORY_PARAMS(ID, CATEGORY_ID, GRANT_PROGRAM_ID, PRODUCT_INSTANCE_FOR_HOUR, MAX_PRODUCT_INSTANCE, DATE_FROM, DATE_TO) VALUES (5, 'MOTO', 100, 2, null, null, null);
