


update APP_PBE.ORDER_FLOW_ELEMENTS_IN_STATUS
set FLAGS = 'IU'
where STATUS_ID = 'NEWKK' and ELEMENT_ID in ('CONAMA_KK', 'PAYAMA_KK', 'COND_KK', 'PAYD_KK') ;


insert into APP_PBE.ORDER_FLOW_ST_TRANS_ELEM_FLAGS(ORDER_FLOW_ID, STATUS_ID, ACTION_ID, ELEMENT_ID, FLAGS) values (100, 'NEWKK', 10012, 'CONAMA_KK', 'M');
insert into APP_PBE.ORDER_FLOW_ST_TRANS_ELEM_FLAGS(ORDER_FLOW_ID, STATUS_ID, ACTION_ID, ELEMENT_ID, FLAGS) values (100, 'NEWKK', 10012, 'PAYAMA_KK', 'M');
insert into APP_PBE.ORDER_FLOW_ST_TRANS_ELEM_FLAGS(ORDER_FLOW_ID, STATUS_ID, ACTION_ID, ELEMENT_ID, FLAGS) values (100, 'NEWKK', 10012, 'COND_KK',   'M');
insert into APP_PBE.ORDER_FLOW_ST_TRANS_ELEM_FLAGS(ORDER_FLOW_ID, STATUS_ID, ACTION_ID, ELEMENT_ID, FLAGS) values (100, 'NEWKK', 10012, 'PAYD_KK',   'M');
