alter table APP_PBE.EMAIL_INSTANCES add  DELAY_TIMESTAMP TIMESTAMP(6);
COMMENT ON COLUMN APP_PBE.EMAIL_INSTANCES.DELAY_TIMESTAMP IS 'Data opóŸninia maila - mail bêdzie wys³any po danej dacie';

alter table APP_PBE.EMAIL_TEMPLATES add  EMAIL_TYPE VARCHAR2(4 BYTE) DEFAULT 'text' NOT null;
COMMENT ON COLUMN APP_PBE.EMAIL_TEMPLATES.EMAIL_TYPE IS 'Typ maila: html text';