MERGE INTO APP_PBE.E_REIMBURSEMENT_STATUSES ug USING (
  SELECT
      'RJCT' ID,
      'Odrzucone' NAME,
      null ORDINAL
  FROM dual
) ins
ON ( ug.ID = ins.ID)
WHEN MATCHED THEN
  UPDATE SET ug.NAME = ins.NAME, ug.ORDINAL = ins.ORDINAL
WHEN NOT MATCHED THEN INSERT
  (ID, NAME, ORDINAL)
  VALUES (ins.ID, ins.NAME, ins.ORDINAL);

MERGE INTO APP_PBE.TI_TRAINING_INSTANCE_STATUSES ug USING (
  SELECT
      'NOT_REIMB' ID,
      'Nie rozliczone' NAME,
      5 ORDINAL
  FROM dual
) ins
ON ( ug.ID = ins.ID)
WHEN MATCHED THEN
  UPDATE SET ug.NAME = ins.NAME, ug.ORDINAL = ins.ORDINAL
WHEN NOT MATCHED THEN INSERT
  (ID, NAME, ORDINAL)
  VALUES (ins.ID, ins.NAME, ins.ORDINAL);