INSERT INTO APP_PBE.TI_TRAINING_CATEGORIES VALUES ('JAZ', 'Szkolenie jêzykowe', 1);
INSERT INTO APP_PBE.TI_TRAINING_CATEGORIES VALUES ('KCY', 'Szkolenie z zakresu kompetencji cyfrowych', 2);
INSERT INTO APP_PBE.TI_TRAINING_CATEGORIES VALUES ('INN', 'Inne certyfikowane szkolenie', 3);
INSERT INTO APP_PBE.TI_TRAINING_CATEGORIES VALUES ('EGZ', 'Egzamin', 4);