CREATE TABLE APP_PBE.PBE_PRODUCT_INSTANCE_EVENTS
(
	ID NUMBER NOT NULL,
	PRD_ID VARCHAR2(20) NOT NULL,
	NUM NUMBER(10) NOT NULL,
	TYPE VARCHAR2(50),
	SOURCE_ID VARCHAR2(50),
	VERSION NUMBER NOT NULL,
	CREATED_USER VARCHAR2(100) NOT NULL,
	CREATED_TIMESTAMP TIMESTAMP(6) NOT NULL,
	MODIFIED_USER VARCHAR2(100) NOT NULL,
	MODIFIED_TIMESTAMP TIMESTAMP(6) NOT NULL
)
;

-- uprawnienia
BEGIN
  dbms_output.put_line(SYS.PK_ADMIN.F_GRANT_TO_EAGLE('APP_PBE', 'EAGLE', 'PBE_PRODUCT_INSTANCE_EVENTS', 'ALL'));
  dbms_output.put_line(SYS.PK_ADMIN.F_GRANT_TO_EAGLE('APP_PBE', 'SRV_EE', 'PBE_PRODUCT_INSTANCE_EVENTS', 'ALL'));
  dbms_output.put_line(SYS.PK_ADMIN.F_GRANT_TO_EAGLE('APP_PBE', 'DEVELOPER', 'PBE_PRODUCT_INSTANCE_EVENTS', 'SELECT'));
END;
/

-- Klucze
CREATE UNIQUE INDEX APP_PBE.PBE_PRD_IN_EVN_PK ON APP_PBE.PBE_PRODUCT_INSTANCE_EVENTS (ID);
ALTER TABLE APP_PBE.PBE_PRODUCT_INSTANCE_EVENTS ADD CONSTRAINT PBE_PRD_IN_EVN_PK PRIMARY KEY (ID);

-- Klucze obce
ALTER TABLE APP_PBE.PBE_PRODUCT_INSTANCE_EVENTS ADD CONSTRAINT PBE_PRD_IN_FK FOREIGN KEY (PRD_ID, NUM) REFERENCES APP_PBE.PBE_PRODUCT_INSTANCES (PRD_ID, NUM);
ALTER TABLE APP_PBE.PBE_PRODUCT_INSTANCE_EVENTS ADD CONSTRAINT PBE_PRD_INST_EVN_TYP_FK FOREIGN KEY (TYPE) REFERENCES APP_PBE.PBE_PRODUCT_INSTANCE_EVE_TYPES (ID);

-- Komentarze
COMMENT ON TABLE APP_PBE.PBE_PRODUCT_INSTANCE_EVENTS IS '@Author(Adam Kmieciñski); @Project(GryfBonEl); @Date(2016-10-11);@Purpose(Tabela przechowuj¹ca dane instancji produktów);';
COMMENT ON COLUMN APP_PBE.PBE_PRODUCT_INSTANCE_EVENTS.ID IS 'ID zdarzenia instancji produktu. Klucz g³ówny';
COMMENT ON COLUMN APP_PBE.PBE_PRODUCT_INSTANCE_EVENTS.PRD_ID IS 'ID produktu';
COMMENT ON COLUMN APP_PBE.PBE_PRODUCT_INSTANCE_EVENTS.NUM IS 'Numer instancji produktu';
COMMENT ON COLUMN APP_PBE.PBE_PRODUCT_INSTANCE_EVENTS.TYPE IS 'Kod rodzaju zdarzenia dla instancji. Wartoœæ s³ownikowa';
COMMENT ON COLUMN APP_PBE.PBE_PRODUCT_INSTANCE_EVENTS.SOURCE_ID IS 'ID obiektu Ÿród³owego dla zdarzenia - powi¹zanie z tabel¹ Ÿród³ow¹ wynika z rodzaju zdarzenia (np wydanie bêdzie zwi¹zane z zamówieniem itp.)';
COMMENT ON COLUMN APP_PBE.PBE_PRODUCT_INSTANCE_EVENTS.VERSION IS 'Wersja. Kolumna techniczna u¿ywana do mechanizmu Optimistic Lock';
COMMENT ON COLUMN APP_PBE.PBE_PRODUCT_INSTANCE_EVENTS.CREATED_USER IS 'Login u¿ytkownika, który utworzy³ rekord';
COMMENT ON COLUMN APP_PBE.PBE_PRODUCT_INSTANCE_EVENTS.CREATED_TIMESTAMP IS 'Data utworzenia rekordu';
COMMENT ON COLUMN APP_PBE.PBE_PRODUCT_INSTANCE_EVENTS.MODIFIED_USER IS 'Login u¿ytkownika, który ostatnio modyfikowa³ rekord';
COMMENT ON COLUMN APP_PBE.PBE_PRODUCT_INSTANCE_EVENTS.MODIFIED_TIMESTAMP IS 'Data ostatniej modyfikacji rekordu';