-- PRIV & ROLE
INSERT INTO APP_PBE.TE_PRIVILEGES (CODE,DESCRIPTION,CONTEXT) VALUES('IND_DESKTOP_PRIV','Przywilej pozwalajacy na wejœcie na panel u¿ytkownika dla osoby fizycznej','IND');
INSERT INTO APP_PBE.TE_ROLES(CODE,DESCRIPTION,CONTEXT)VALUES('IND_DESKTOP_ROLE','Rola pozwalaj¹ca  na wejœcie na panel u¿ytkownika dla osoby fizycznej','IND');
INSERT INTO APP_PBE.TE_PRIV_IN_ROLES (TE_PRIV_CODE, TE_ROLE_CODE) VALUES('IND_DESKTOP_PRIV','IND_DESKTOP_ROLE');

INSERT INTO APP_PBE.TE_PRIVILEGES (CODE,DESCRIPTION,CONTEXT) VALUES('TI_MAIN_PRIV','Przywilej pozwalaj¹cy na wejœcie do aplikacji','TI');
INSERT INTO APP_PBE.TE_ROLES(CODE,DESCRIPTION,CONTEXT)VALUES('TI_MAIN_ROLE','Rola pozwalaj¹ca na wejœcie do aplikacji','TI');
INSERT INTO APP_PBE.TE_PRIV_IN_ROLES (TE_PRIV_CODE, TE_ROLE_CODE) VALUES('TI_MAIN_PRIV','TI_MAIN_ROLE');