
ALTER TABLE APP_FIN.INVOICES_ARCHIVE ADD DOCUMENT_SOURCE_SYSTEM VARCHAR2(1) DEFAULT 'E' NOT NULL;
COMMENT ON COLUMN APP_FIN.INVOICES_ARCHIVE.DOCUMENT_SOURCE_SYSTEM IS 'Jakie jest Ÿród³o wpisu: E - program C#, G - Gryf';

BEGIN
  dbms_output.put_line(SYS.PK_ADMIN.F_GRANT_TO_EAGLE('APP_FIN', 'SRV_EE', 'INVOICES_ARCHIVE', 'SELECT'));
  dbms_output.put_line(SYS.PK_ADMIN.F_GRANT_TO_EAGLE('APP_FIN', 'SRV_EE', 'INVOICES_ARCHIVE', 'INSERT'));
  dbms_output.put_line(SYS.PK_ADMIN.F_GRANT_TO_EAGLE('EAGLE', 'SRV_EE', 'IAR_SEQ', 'SELECT'));
END;
/

