-- Part 2:


ALTER TABLE APP_PBE.TI_TRAINING_INSTANCES_EXT
  ADD ID NUMBER(10);


ALTER TABLE APP_PBE.TI_TRAINING_INSTANCES_EXT
  ADD
  TRAINING_ID NUMBER;


COMMENT ON COLUMN APP_PBE.TI_TRAINING_INSTANCES_EXT.TRAINING_ID IS 'ID szkolenia';

ALTER TABLE APP_PBE.TI_TRAINING_INSTANCES_EXT
  ADD
  CONSTRAINT PBE_TTIE_INS_TRA_FK
  FOREIGN KEY (TRAINING_ID)
  REFERENCES APP_PBE.TI_TRAININGS (ID)
  ENABLE VALIDATE;

ALTER TABLE APP_PBE.TI_TRAINING_INSTANCES_EXT
  ADD IMPORT_JOB_ID NUMBER;

COMMENT ON COLUMN APP_PBE.TI_TRAINING_INSTANCES_EXT.TRAINING_ID IS 'ID job, w ramach którego nastąpił import';

ALTER TABLE APP_PBE.TI_TRAINING_INSTANCES_EXT
  ADD
  CONSTRAINT PBE_TTIE_ASYN_JOB_FK
  FOREIGN KEY (IMPORT_JOB_ID)
  REFERENCES APP_PBE.ASYNCH_JOBS (ID)
  ENABLE VALIDATE;


ALTER TABLE APP_PBE.TI_TRAINING_INSTANCES_EXT
  ADD
  VERSION NUMBER;

COMMENT ON COLUMN APP_PBE.TI_TRAINING_INSTANCES_EXT.TRAINING_ID IS 'Numer wersji rekordu';


ALTER TABLE APP_PBE.TI_TRAINING_INSTANCES_EXT
  ADD -- NOT NULL
  MODIFIED_USER VARCHAR2(100 BYTE);


ALTER TABLE APP_PBE.TI_TRAINING_INSTANCES_EXT
  ADD -- NOT NULL
  MODIFIED_TIMESTAMP TIMESTAMP(6);


DECLARE
  v_x VARCHAR2(100);
BEGIN
  v_x := SYS.PK_ADMIN.F_GRANT_TO_EAGLE('APP_PBE', 'SRV_EE', 'TI_TRAINING_INSTANCES_EXT', 'ALL');
  dbms_output.put_line(v_x);
END;

