ALTER TABLE APP_PBE.PBE_PRODUCT_INSTANCE_POOLS ADD (RETURNED_NUM NUMBER(10));
UPDATE APP_PBE.PBE_PRODUCT_INSTANCE_POOLS SET RETURNED_NUM = 0;
ALTER TABLE APP_PBE.PBE_PRODUCT_INSTANCE_POOLS MODIFY RETURNED_NUM NOT NULL;
COMMENT ON COLUMN APP_PBE.PBE_PRODUCT_INSTANCE_POOLS.RETURNED_NUM IS 'Iloœæ zwróconych bonów';