ALTER TABLE APP_PBE.ORDER_INVOICES ADD (INDIVIDUAL_ID NUMBER);
ALTER TABLE APP_PBE.ORDER_INVOICES ADD CONSTRAINT ORD_INV_IND_FK FOREIGN KEY (INDIVIDUAL_ID) REFERENCES APP_PBE.INDIVIDUALS (ID);
COMMENT ON COLUMN APP_PBE.ORDER_INVOICES.INDIVIDUAL_ID IS 'Identyfikator u¿ytkownika indywidualnego';

update APP_PBE.ORDER_INVOICES oi set oi.INDIVIDUAL_ID = (select c.INDIVIDUAL_ID
                                                         from APP_PBE.CONTRACTS c
                                                           inner join APP_PBE.ORDERS o on c.id = o.contract_id
                                                         where o.id = oi.order_id)
where INDIVIDUAL_ID is null;

ALTER TABLE    APP_PBE.ORDER_INVOICES MODIFY INDIVIDUAL_ID  not null;


ALTER TABLE APP_PBE.ORDER_INVOICES ADD (ENTERPRISE_ID NUMBER);
ALTER TABLE APP_PBE.ORDER_INVOICES ADD CONSTRAINT ORD_INV_ENT_FK FOREIGN KEY (ENTERPRISE_ID) REFERENCES APP_PBE.ENTERPRISES (ID);
COMMENT ON COLUMN APP_PBE.ORDER_INVOICES.ENTERPRISE_ID IS 'Identyfikator MŒP';

ALTER TABLE APP_PBE.ORDER_INVOICES ADD (WUP_DEBT_DOC_NO VARCHAR2(30 BYTE));
COMMENT ON COLUMN APP_PBE.ORDER_INVOICES.WUP_DEBT_DOC_NO IS 'Dodatkowy numer umowy - Numer dokumentu na przysz³e nale¿noœci WUP';