ALTER TABLE APP_PBE.E_RMBS_ATTACHMENTS
  ADD (
  DOCUMENT_DATE DATE
  );

COMMENT ON COLUMN APP_PBE.E_RMBS_ATTACHMENTS.DOCUMENT_DATE IS 'Data dokumentu';


ALTER TABLE APP_PBE.CORRECTION_ATTACHMENTS
  ADD (
  OLD_DOCUMENT_DATE DATE
  );

COMMENT ON COLUMN APP_PBE.CORRECTION_ATTACHMENTS.OLD_DOCUMENT_DATE IS 'Pierwotna data dokumentu za³¹cznika, który zmieniliœmy w ramach korekty';

