CREATE TABLE APP_PBE.PBE_PRODUCT_INSTANCES
(
	PRD_ID VARCHAR2(20 BYTE) NOT NULL,
	NUM NUMBER(10) NOT NULL,
	STATUS_ID VARCHAR2(10 BYTE) NOT NULL,
	EXPIRY_DATE DATE,
	PRINT_NUM VARCHAR2(50 BYTE),
	CRC NUMBER(10),
	PRODUCT_EMISSION_ID VARCHAR2(20 BYTE),
  PRODUCT_INSTANCE_POOL_ID  NUMBER,
  PRODUCT_INSTANCE_POOL_USE_ID  NUMBER,
	ORDER_ID NUMBER,
	E_REIMBURSMENT_ID NUMBER,
	VERSION NUMBER NOT NULL,
	CREATED_USER VARCHAR2(100 BYTE) NOT NULL,
	CREATED_TIMESTAMP TIMESTAMP(6) NOT NULL,
	MODIFIED_USER VARCHAR2(100 BYTE) NOT NULL,
	MODIFIED_TIMESTAMP TIMESTAMP(6) NOT NULL
)
;

-- uprawnienia
BEGIN
  dbms_output.put_line(SYS.PK_ADMIN.F_GRANT_TO_EAGLE('APP_PBE', 'EAGLE', 'PBE_PRODUCT_INSTANCES', 'ALL'));
  dbms_output.put_line(SYS.PK_ADMIN.F_GRANT_TO_EAGLE('APP_PBE', 'SRV_EE', 'PBE_PRODUCT_INSTANCES', 'ALL'));
  dbms_output.put_line(SYS.PK_ADMIN.F_GRANT_TO_EAGLE('APP_PBE', 'DEVELOPER', 'PBE_PRODUCT_INSTANCES', 'SELECT'));
END;
/

-- Klucze g³ówny
CREATE UNIQUE INDEX APP_PBE.PBE_PRD_IN_PK ON APP_PBE.PBE_PRODUCT_INSTANCES (PRD_ID, NUM);
ALTER TABLE APP_PBE.PBE_PRODUCT_INSTANCES ADD CONSTRAINT PBE_PRD_IN_PK PRIMARY KEY (PRD_ID, NUM);

-- Klucze obce
ALTER TABLE APP_PBE.PBE_PRODUCT_INSTANCES ADD CONSTRAINT PBE_PRD_PRD_FK FOREIGN KEY (PRD_ID) REFERENCES APP_PBE.PBE_PRODUCTS (PRD_ID);
ALTER TABLE APP_PBE.PBE_PRODUCT_INSTANCES ADD CONSTRAINT PBE_PRD_EM_FK FOREIGN KEY (PRODUCT_EMISSION_ID) REFERENCES APP_PBE.PBE_PRODUCT_EMISSIONS (ID);
ALTER TABLE APP_PBE.PBE_PRODUCT_INSTANCES ADD CONSTRAINT PB_PRD_INST_ST_DIC_FK FOREIGN KEY (STATUS_ID) REFERENCES APP_PBE.PBE_PRODUCT_INSTANCE_STATUSES (ID);
ALTER TABLE APP_PBE.PBE_PRODUCT_INSTANCES ADD CONSTRAINT PBE_PRD_INS_PRD_INS_POL_FK FOREIGN KEY (PRODUCT_INSTANCE_POOL_ID) REFERENCES APP_PBE.PBE_PRODUCT_INSTANCE_POOLS (ID);
ALTER TABLE APP_PBE.PBE_PRODUCT_INSTANCES ADD CONSTRAINT PBE_PRD_INS_PRD_INS_POL_USE_FK FOREIGN KEY (PRODUCT_INSTANCE_POOL_USE_ID) REFERENCES APP_PBE.PBE_PRODUCT_INSTANCE_POOL_USES (ID);

-- Komentarze
COMMENT ON TABLE APP_PBE.PBE_PRODUCT_INSTANCES IS '@Author(Adam Kmieciñski); @Project(GryfBonEl); @Date(2016-10-11);@Purpose(Tabela przechowuj¹ca dane instancji produktów);';

COMMENT ON COLUMN APP_PBE.PBE_PRODUCT_INSTANCES.PRD_ID IS 'ID produktu. Kolumna z³o¿onego klucza g³ównego';
COMMENT ON COLUMN APP_PBE.PBE_PRODUCT_INSTANCES.NUM IS 'Numer instancji produktu. Kolumna z³o¿onego klucza g³ównego';
COMMENT ON COLUMN APP_PBE.PBE_PRODUCT_INSTANCES.PRODUCT_EMISSION_ID IS 'ID emisji produktu';
COMMENT ON COLUMN APP_PBE.PBE_PRODUCT_INSTANCES.PRODUCT_INSTANCE_POOL_ID IS 'ID puli instancji produktów do której dany produkt nale¿y';
COMMENT ON COLUMN APP_PBE.PBE_PRODUCT_INSTANCES.PRODUCT_INSTANCE_POOL_USE_ID IS 'ID wykorzystania puli instancji produktów w której dany produkt bêdzie wykorzystywany (rozliczany)';
COMMENT ON COLUMN APP_PBE.PBE_PRODUCT_INSTANCES.ORDER_ID IS 'Indetyfikator zamówienia';
COMMENT ON COLUMN APP_PBE.PBE_PRODUCT_INSTANCES.E_REIMBURSMENT_ID IS 'Identyfikator rozliczenia';
COMMENT ON COLUMN APP_PBE.PBE_PRODUCT_INSTANCES.STATUS_ID IS 'Kod statusu instancji. Wartoœæ s³ownikowa';
COMMENT ON COLUMN APP_PBE.PBE_PRODUCT_INSTANCES.EXPIRY_DATE IS 'Data wygaœniecia';
COMMENT ON COLUMN APP_PBE.PBE_PRODUCT_INSTANCES.PRINT_NUM IS 'Number drukowany produktu';
COMMENT ON COLUMN APP_PBE.PBE_PRODUCT_INSTANCES.CRC IS 'Wyszczególniona liczba kontrolna w numerze drukowanym produktu';
COMMENT ON COLUMN APP_PBE.PBE_PRODUCT_INSTANCES.VERSION IS 'Wersja. Kolumna techniczna u¿ywana do mechanizmu Optimistic Lock';
COMMENT ON COLUMN APP_PBE.PBE_PRODUCT_INSTANCES.CREATED_USER IS 'Login u¿ytkownika, który utworzy³ rekord';
COMMENT ON COLUMN APP_PBE.PBE_PRODUCT_INSTANCES.CREATED_TIMESTAMP IS 'Data utworzenia rekordu';
COMMENT ON COLUMN APP_PBE.PBE_PRODUCT_INSTANCES.MODIFIED_USER IS 'Login u¿ytkownika, który ostatnio modyfikowa³ rekord';
COMMENT ON COLUMN APP_PBE.PBE_PRODUCT_INSTANCES.MODIFIED_TIMESTAMP IS 'Data ostatniej modyfikacji rekordu';
