

INSERT INTO APP_PBE.TI_TRAINING_CATEGORY_CAT (ID, NAME, ORDINAL) VALUES ('CAT_KK', 'Katalog szkoleñ - Kierunek Kariera', 4);


INSERT INTO APP_PBE.TI_TRAINING_CATEGORY_CAT_GR_PR (ID, CATALOG_ID, GRANT_PROGRAM_ID, DATE_FROM, DATE_TO) VALUES (1, 'CAT_KK', 100, null, null);

INSERT INTO APP_PBE.TI_TRAINING_CATEGORY_PARAMS (ID, CATEGORY_ID, GRANT_PROGRAM_ID, PRODUCT_INSTANCE_FOR_HOUR, DATE_FROM, DATE_TO) values (1, 'JAZ', 100, 1, null, null);
INSERT INTO APP_PBE.TI_TRAINING_CATEGORY_PARAMS (ID, CATEGORY_ID, GRANT_PROGRAM_ID, PRODUCT_INSTANCE_FOR_HOUR, DATE_FROM, DATE_TO) values (2, 'KCY', 100, 2, null, null);
INSERT INTO APP_PBE.TI_TRAINING_CATEGORY_PARAMS (ID, CATEGORY_ID, GRANT_PROGRAM_ID, PRODUCT_INSTANCE_FOR_HOUR, DATE_FROM, DATE_TO) values (3, 'INN', 100, 3, null, null);
INSERT INTO APP_PBE.TI_TRAINING_CATEGORY_PARAMS (ID, CATEGORY_ID, GRANT_PROGRAM_ID, PRODUCT_INSTANCE_FOR_HOUR, DATE_FROM, DATE_TO) values (4, 'EGZ', 100, null, null, null);

