


CREATE TABLE APP_PBE.PBE_PRODUCT_INSTANCE_POOLS
(
	ID NUMBER NOT NULL,
	STATUS_ID VARCHAR2(10 BYTE) NOT NULL,
	EXPIRY_DATE DATE NOT NULL,
	All_NUM NUMBER(10) NOT NULL,
	AVAILABLE_NUM NUMBER(10) NOT NULL,
	RESERVED_NUM NUMBER(10) NOT NULL,
	USED_NUM NUMBER(10) NOT NULL,
	REMBURS_NUM NUMBER(10) NOT NULL,
	INDIVIDUAL_ID NUMBER NOT NULL,
	ORDER_ID NUMBER NOT NULL,
	PRD_ID VARCHAR2(20  BYTE) NOT NULL,
	VERSION NUMBER NOT NULL,
	CREATED_USER VARCHAR2(30 BYTE) NOT NULL,
	CREATED_TIMESTAMP TIMESTAMP(6) NOT NULL,
	MODIFIED_USER VARCHAR2(30 BYTE) NOT NULL,
	MODIFIED_TIMESTAMP TIMESTAMP(6) NOT NULL
);


-- uprawnienia
BEGIN
  dbms_output.put_line(SYS.PK_ADMIN.F_GRANT_TO_EAGLE('APP_PBE', 'EAGLE', 'PBE_PRODUCT_INSTANCE_POOLS', 'ALL'));
  dbms_output.put_line(SYS.PK_ADMIN.F_GRANT_TO_EAGLE('APP_PBE', 'SRV_EE', 'PBE_PRODUCT_INSTANCE_POOLS', 'ALL'));
  dbms_output.put_line(SYS.PK_ADMIN.F_GRANT_TO_EAGLE('APP_PBE', 'DEVELOPER', 'PBE_PRODUCT_INSTANCE_POOLS', 'SELECT'));
END;
/

-- Klucze
CREATE UNIQUE INDEX APP_PBE.PBE_PRD_INS_POL_PK ON APP_PBE.PBE_PRODUCT_INSTANCE_POOLS (ID);
ALTER TABLE APP_PBE.PBE_PRODUCT_INSTANCE_POOLS ADD CONSTRAINT PBE_PRD_INS_POL_PK PRIMARY KEY (ID);

--Indeksy
CREATE UNIQUE INDEX APP_PBE.PBE_PRD_INS_POL_ORD_IDX ON APP_PBE.PBE_PRODUCT_INSTANCE_POOLS (ORDER_ID);

-- Klucze obce (dla kolumny PRD_ID w pliku PRODUCT_CONSTRAINTS)
ALTER TABLE APP_PBE.PBE_PRODUCT_INSTANCE_POOLS ADD CONSTRAINT PBE_PRO_INS_POL_IND_FK FOREIGN KEY (INDIVIDUAL_ID) REFERENCES APP_PBE.INDIVIDUALS (ID);
ALTER TABLE APP_PBE.PBE_PRODUCT_INSTANCE_POOLS ADD CONSTRAINT PBE_PRO_INS_POL_ORD_FK FOREIGN KEY (ORDER_ID) REFERENCES APP_PBE.ORDERS (ID);
ALTER TABLE APP_PBE.PBE_PRODUCT_INSTANCE_POOLS ADD CONSTRAINT PBE_PRO_INS_POL_STAT_FK FOREIGN KEY (STATUS_ID) REFERENCES APP_PBE.PBE_PRODUCT_INSTANCE_POOL_STAS (ID);


-- Komentarze
COMMENT ON TABLE APP_PBE.PBE_PRODUCT_INSTANCE_POOLS IS '@Author(Tomasz Bilski); @Project(GryfBonEl); @Date(2016-11-05);@Purpose(Tabela przechowuj¹ca dane instancji puli produktów);';
COMMENT ON COLUMN APP_PBE.PBE_PRODUCT_INSTANCE_POOLS.ID IS 'ID zdarzenia instancji puli produktu. Klucz g³ówny';
COMMENT ON COLUMN APP_PBE.PBE_PRODUCT_INSTANCE_POOLS.ALL_NUM IS 'Iloœæ wszystkich bonów w ramach puli';
COMMENT ON COLUMN APP_PBE.PBE_PRODUCT_INSTANCE_POOLS.AVAILABLE_NUM IS 'Iloœæ dostêpnych bonów w ramach puli';
COMMENT ON COLUMN APP_PBE.PBE_PRODUCT_INSTANCE_POOLS.RESERVED_NUM IS 'Iloœæ zarezerwowanych bonów (szkolenie zosta³o zg³oszone ale nie odbyte) w ramach puli';
COMMENT ON COLUMN APP_PBE.PBE_PRODUCT_INSTANCE_POOLS.USED_NUM IS 'Iloœæ wykorzystanych bonów (szkolenie zosta³o odbyte ale nie rozliczone) w ramach puli';
COMMENT ON COLUMN APP_PBE.PBE_PRODUCT_INSTANCE_POOLS.REMBURS_NUM IS 'Iloœæ rozliczonych bonów (szkolenie zosta³o rozlicozne) w ramach puli';
COMMENT ON COLUMN APP_PBE.PBE_PRODUCT_INSTANCE_POOLS.INDIVIDUAL_ID IS 'Identyfikator u¿ytkownika do którego przydzielona jest pula bonów';
COMMENT ON COLUMN APP_PBE.PBE_PRODUCT_INSTANCE_POOLS.ORDER_ID IS 'Identyfikator zamówienia na dan¹ pulê bonów';
COMMENT ON COLUMN APP_PBE.PBE_PRODUCT_INSTANCE_POOLS.PRD_ID IS 'Identyfikator produktu';
COMMENT ON COLUMN APP_PBE.PBE_PRODUCT_INSTANCE_POOLS.VERSION IS 'Wersja. Kolumna techniczna u¿ywana do mechanizmu Optimistic Lock';
COMMENT ON COLUMN APP_PBE.PBE_PRODUCT_INSTANCE_POOLS.CREATED_USER IS 'Login u¿ytkownika, który utworzy³ rekord';
COMMENT ON COLUMN APP_PBE.PBE_PRODUCT_INSTANCE_POOLS.CREATED_TIMESTAMP IS 'Data utworzenia rekordu';
COMMENT ON COLUMN APP_PBE.PBE_PRODUCT_INSTANCE_POOLS.MODIFIED_USER IS 'Login u¿ytkownika, który ostatnio modyfikowa³ rekord';
COMMENT ON COLUMN APP_PBE.PBE_PRODUCT_INSTANCE_POOLS.MODIFIED_TIMESTAMP IS 'Data ostatniej modyfikacji rekordu';
