CREATE TABLE APP_PBE.PBE_PRODUCTS
(
	PRD_ID VARCHAR2(20) NOT NULL,
	PRT_TYPE VARCHAR2(10 BYTE) NOT NULL,
	GRO_ID NUMBER,
	NAME VARCHAR2(100) NOT NULL,
	VALUE NUMBER(10,3),
	EXPIRY_DATE DATE,
	CREATION_DATE DATE NOT NULL,
	DESCRIPTION VARCHAR2(200)
)
;

-- uprawnienia
BEGIN
  dbms_output.put_line(SYS.PK_ADMIN.F_GRANT_TO_EAGLE('APP_PBE', 'EAGLE', 'PBE_PRODUCTS', 'ALL'));
  dbms_output.put_line(SYS.PK_ADMIN.F_GRANT_TO_EAGLE('APP_PBE', 'SRV_EE', 'PBE_PRODUCTS', 'ALL'));
  dbms_output.put_line(SYS.PK_ADMIN.F_GRANT_TO_EAGLE('APP_PBE', 'DEVELOPER', 'PBE_PRODUCTS', 'SELECT'));
  dbms_output.put_line(SYS.PK_ADMIN.F_GRANT_TO_EAGLE('APP_STC', 'APP_PBE', 'PRODUCT_TYPES', 'REFERENCES'));
END;
/

-- Indeksy
CREATE UNIQUE INDEX APP_PBE.PBE_PRODUCT_PK ON APP_PBE.PBE_PRODUCTS (PRD_ID);

-- Klucze
ALTER TABLE APP_PBE.PBE_PRODUCTS 
 ADD CONSTRAINT PBE_PRODUCT_PK
	PRIMARY KEY (PRD_ID)
;

ALTER TABLE APP_PBE.PBE_PRODUCTS 
 ADD CONSTRAINT GRANT_OWNER_FK
	FOREIGN KEY (GRO_ID) REFERENCES APP_PBE.GRANT_OWNERS (ID)
;

ALTER TABLE APP_PBE.PBE_PRODUCTS 
 ADD CONSTRAINT PBE_PRD_TYPE_FK
	FOREIGN KEY (PRT_TYPE) REFERENCES APP_STC.PRODUCT_TYPES (TYPE)
;

-- Komentarze
COMMENT ON TABLE APP_PBE.PBE_PRODUCTS IS '@Author(Adam Kmieciñski); @Project(GryfBonEl); @Date(2016-10-10);@Purpose(Tabela przechowuj¹ca definicje produktów);';

COMMENT ON COLUMN APP_PBE.PBE_PRODUCTS.PRD_ID IS 'Unikalne ID produktu. Klucz g³ówny. ';
COMMENT ON COLUMN APP_PBE.PBE_PRODUCTS.PRT_TYPE IS 'ID typu produktu';
COMMENT ON COLUMN APP_PBE.PBE_PRODUCTS.GRO_ID IS 'ID w³aœciciela wniosku';
COMMENT ON COLUMN APP_PBE.PBE_PRODUCTS.NAME IS 'Nazwa produktu';
COMMENT ON COLUMN APP_PBE.PBE_PRODUCTS.VALUE IS 'Nomina³ produktu';
COMMENT ON COLUMN APP_PBE.PBE_PRODUCTS.EXPIRY_DATE IS 'Data wygaœniêcia wa¿noœci produktu';
COMMENT ON COLUMN APP_PBE.PBE_PRODUCTS.CREATION_DATE IS 'Data utworzenia produktu';
COMMENT ON COLUMN APP_PBE.PBE_PRODUCTS.DESCRIPTION IS 'Opis produktu';