
ALTER TABLE APP_PBE.IMPORT_DATA_ROWS ADD CONSTRAINT IMP_DAT_ROW_CON_FK FOREIGN KEY (CONTRACT_ID) REFERENCES APP_PBE.CONTRACTS (ID);
ALTER TABLE APP_PBE.IMPORT_DATA_ROWS ADD CONSTRAINT IMP_DAT_ROW_IND_FK FOREIGN KEY (INDIVIDUAL_ID) REFERENCES APP_PBE.INDIVIDUALS (ID);
ALTER TABLE APP_PBE.IMPORT_DATA_ROWS ADD CONSTRAINT IMP_DAT_ROW_ENT_FK FOREIGN KEY (ENTERPRISE_ID) REFERENCES APP_PBE.ENTERPRISES (ID);
ALTER TABLE APP_PBE.IMPORT_DATA_ROWS ADD CONSTRAINT IMP_DAT_ROW_ORD_FK FOREIGN KEY (ORDER_ID) REFERENCES APP_PBE.ORDERS (ID);
ALTER TABLE APP_PBE.IMPORT_DATA_ROWS ADD CONSTRAINT IMP_DAT_ROW_TRA_INSTI_FK FOREIGN KEY (TRAINING_INSTITUTION_ID) REFERENCES APP_PBE.TRAINING_INSTITUTIONS (ID);
ALTER TABLE APP_PBE.IMPORT_DATA_ROWS ADD CONSTRAINT IMP_DAT_ROW_TRA_FK FOREIGN KEY (TRAINING_ID) REFERENCES APP_PBE.TI_TRAININGS (ID);
ALTER TABLE APP_PBE.IMPORT_DATA_ROWS ADD CONSTRAINT IMP_DAT_ROW_TRA_INSTA_FK FOREIGN KEY (TRAINING_INSTANCE_ID) REFERENCES APP_PBE.TI_TRAINING_INSTANCES (ID);


