MERGE INTO APP_PBE.ATTACHMENT_TYPES ug USING (
  SELECT
    'INVOICE' CODE,
    'Faktura' NAME,
    1 ORDINAL,
    4194304 MAX_BYTES_PER_FILE,
    null MAX_FILES_PER_TYPE
  FROM dual
) ins
ON (ug.CODE = ins.CODE)
WHEN MATCHED THEN
  UPDATE SET ug.NAME = ins.NAME, ug.ORDINAL = ins.ORDINAL, ug.MAX_BYTES_PER_FILE = ins.MAX_BYTES_PER_FILE, ug.MAX_FILES_PER_TYPE = ins.MAX_FILES_PER_TYPE
WHEN NOT MATCHED THEN INSERT
  (CODE, NAME, ORDINAL, MAX_BYTES_PER_FILE, MAX_FILES_PER_TYPE)
  VALUES (ins.CODE, ins.NAME, ins.ORDINAL, ins.MAX_BYTES_PER_FILE, ins.MAX_FILES_PER_TYPE);

MERGE INTO APP_PBE.ATTACHMENT_TYPES ug USING (
  SELECT
    'ATTEST' CODE,
    'Zaœwiadczenie o ukoñczeniu szkolenia' NAME,
    2 ORDINAL,
    4194304 MAX_BYTES_PER_FILE,
    null MAX_FILES_PER_TYPE
  FROM dual
) ins
ON (ug.CODE = ins.CODE)
WHEN MATCHED THEN
  UPDATE SET ug.NAME = ins.NAME, ug.ORDINAL = ins.ORDINAL, ug.MAX_BYTES_PER_FILE = ins.MAX_BYTES_PER_FILE, ug.MAX_FILES_PER_TYPE = ins.MAX_FILES_PER_TYPE
WHEN NOT MATCHED THEN INSERT
  (CODE, NAME, ORDINAL, MAX_BYTES_PER_FILE, MAX_FILES_PER_TYPE)
  VALUES (ins.CODE, ins.NAME, ins.ORDINAL, ins.MAX_BYTES_PER_FILE, ins.MAX_FILES_PER_TYPE);

MERGE INTO APP_PBE.ATTACHMENT_TYPES ug USING (
  SELECT
    'CERT' CODE,
    'Certyfikat / zaœwiadczenie zdania egzaminu' NAME,
    3 ORDINAL,
    4194304 MAX_BYTES_PER_FILE,
    null MAX_FILES_PER_TYPE
  FROM dual
) ins
ON (ug.CODE = ins.CODE)
WHEN MATCHED THEN
  UPDATE SET ug.NAME = ins.NAME, ug.ORDINAL = ins.ORDINAL, ug.MAX_BYTES_PER_FILE = ins.MAX_BYTES_PER_FILE, ug.MAX_FILES_PER_TYPE = ins.MAX_FILES_PER_TYPE
WHEN NOT MATCHED THEN INSERT
  (CODE, NAME, ORDINAL, MAX_BYTES_PER_FILE, MAX_FILES_PER_TYPE)
  VALUES (ins.CODE, ins.NAME, ins.ORDINAL, ins.MAX_BYTES_PER_FILE, ins.MAX_FILES_PER_TYPE);

MERGE INTO APP_PBE.ATTACHMENT_TYPES ug USING (
  SELECT
    'DIFF' CODE,
    'Inne' NAME,
    3 ORDINAL,
    4194304 MAX_BYTES_PER_FILE,
    null MAX_FILES_PER_TYPE
  FROM dual
) ins
ON (ug.CODE = ins.CODE)
WHEN MATCHED THEN
  UPDATE SET ug.NAME = ins.NAME, ug.ORDINAL = ins.ORDINAL, ug.MAX_BYTES_PER_FILE = ins.MAX_BYTES_PER_FILE, ug.MAX_FILES_PER_TYPE = ins.MAX_FILES_PER_TYPE
WHEN NOT MATCHED THEN INSERT
  (CODE, NAME, ORDINAL, MAX_BYTES_PER_FILE, MAX_FILES_PER_TYPE)
  VALUES (ins.CODE, ins.NAME, ins.ORDINAL, ins.MAX_BYTES_PER_FILE, ins.MAX_FILES_PER_TYPE);

MERGE INTO APP_PBE.GRANT_PROGRAM_ATTACH_REQ ug USING (
  SELECT
      (SELECT ID FROM APP_PBE.GRANT_PROGRAMS WHERE upper(PROGRAM_NAME) = upper('Kierunek Kariera')) GRANT_PROGRAM_ID,
      'INVOICE' ATTACH_TYPE,
      (SELECT START_DATE FROM APP_PBE.GRANT_PROGRAMS WHERE upper(PROGRAM_NAME) = upper('Kierunek Kariera'))  DATE_FROM,
      null DATE_TO
  FROM dual
) ins
ON (ug.ATTACH_TYPE = ins.ATTACH_TYPE AND ug.GRANT_PROGRAM_ID = ins.GRANT_PROGRAM_ID)
WHEN MATCHED THEN
  UPDATE SET ug.DATE_FROM = ins.DATE_FROM, ug.DATE_TO = ins.DATE_TO
WHEN NOT MATCHED THEN INSERT
  (GRANT_PROGRAM_ID, ATTACH_TYPE, DATE_FROM, DATE_TO)
  VALUES (ins.GRANT_PROGRAM_ID, ins.ATTACH_TYPE, ins.DATE_FROM, ins.DATE_TO);

MERGE INTO APP_PBE.GRANT_PROGRAM_ATTACH_REQ ug USING (
  SELECT
      (SELECT ID FROM APP_PBE.GRANT_PROGRAMS WHERE upper(PROGRAM_NAME) = upper('Kierunek Kariera')) GRANT_PROGRAM_ID,
      'ATTEST' ATTACH_TYPE,
      (SELECT START_DATE FROM APP_PBE.GRANT_PROGRAMS WHERE upper(PROGRAM_NAME) = upper('Kierunek Kariera'))  DATE_FROM,
      null DATE_TO
  FROM dual
) ins
ON (ug.ATTACH_TYPE = ins.ATTACH_TYPE AND ug.GRANT_PROGRAM_ID = ins.GRANT_PROGRAM_ID)
WHEN MATCHED THEN
  UPDATE SET ug.DATE_FROM = ins.DATE_FROM, ug.DATE_TO = ins.DATE_TO
WHEN NOT MATCHED THEN INSERT
  (GRANT_PROGRAM_ID, ATTACH_TYPE, DATE_FROM, DATE_TO)
  VALUES (ins.GRANT_PROGRAM_ID, ins.ATTACH_TYPE, ins.DATE_FROM, ins.DATE_TO);

MERGE INTO APP_PBE.GRANT_PROGRAM_ATTACH_REQ ug USING (
  SELECT
      (SELECT ID FROM APP_PBE.GRANT_PROGRAMS WHERE upper(PROGRAM_NAME) = upper('Kierunek Kariera')) GRANT_PROGRAM_ID,
      'CERT' ATTACH_TYPE,
      (SELECT START_DATE FROM APP_PBE.GRANT_PROGRAMS WHERE upper(PROGRAM_NAME) = upper('Kierunek Kariera'))  DATE_FROM,
      null DATE_TO
  FROM dual
) ins
ON (ug.ATTACH_TYPE = ins.ATTACH_TYPE AND ug.GRANT_PROGRAM_ID = ins.GRANT_PROGRAM_ID)
WHEN MATCHED THEN
  UPDATE SET ug.DATE_FROM = ins.DATE_FROM, ug.DATE_TO = ins.DATE_TO
WHEN NOT MATCHED THEN INSERT
  (GRANT_PROGRAM_ID, ATTACH_TYPE, DATE_FROM, DATE_TO)
  VALUES (ins.GRANT_PROGRAM_ID, ins.ATTACH_TYPE, ins.DATE_FROM, ins.DATE_TO);

