INSERT INTO APP_PBE.TI_TRAINING_CATEGORIES VALUES ('JAZ', 'Szkolenie jêzykowe', 1);
INSERT INTO APP_PBE.TI_TRAINING_CATEGORIES VALUES ('KCY', 'Szkolenie z zakresu kompetencji cyfrowych', 2);
INSERT INTO APP_PBE.TI_TRAINING_CATEGORIES VALUES ('INN', 'Inne certyfikowane szkolenie', 3);
INSERT INTO APP_PBE.TI_TRAINING_CATEGORIES VALUES ('EGZ', 'Egzamin', 4);

INSERT INTO APP_PBE.TI_TRAINING_CATEGORY_CAT (ID, NAME, ORDINAL) VALUES ('CAT_KK', 'Katalog szkoleñ - Kierunek Kariera', 4);

INSERT INTO APP_PBE.TI_TRAINING_CATEGORY_CAT_GR_PR (ID, CATALOG_ID, GRANT_PROGRAM_ID, DATE_FROM, DATE_TO) VALUES (1, 'CAT_KK', 100, null, null);

MERGE INTO APP_PBE.TI_TRAINING_CATEGORY_PARAMS ug USING (
  SELECT
    'JAZ' CATEGORY_ID,
    (SELECT ID FROM APP_PBE.GRANT_PROGRAMS WHERE upper(PROGRAM_NAME) = upper('Kierunek Kariera')) GRANT_PROGRAM_ID,
    1 PRODUCT_INSTANCE_FOR_HOUR,
    null MAX_PRODUCT_INSTANCE,
    (SELECT START_DATE FROM APP_PBE.GRANT_PROGRAMS WHERE upper(PROGRAM_NAME) = upper('Kierunek Kariera'))  DATE_FROM,
    null DATE_TO
  FROM dual
) ins
ON (ug.CATEGORY_ID = ins.CATEGORY_ID AND ug.GRANT_PROGRAM_ID = ins.GRANT_PROGRAM_ID)
WHEN MATCHED THEN
  UPDATE SET ug.PRODUCT_INSTANCE_FOR_HOUR = ins.PRODUCT_INSTANCE_FOR_HOUR, ug.MAX_PRODUCT_INSTANCE = ins.MAX_PRODUCT_INSTANCE, ug.DATE_FROM = ins.DATE_FROM, ug.DATE_TO = ins.DATE_TO
WHEN NOT MATCHED THEN INSERT
  (ID, CATEGORY_ID, GRANT_PROGRAM_ID, PRODUCT_INSTANCE_FOR_HOUR, MAX_PRODUCT_INSTANCE, DATE_FROM, DATE_TO)
  VALUES (1, ins.CATEGORY_ID, ins.GRANT_PROGRAM_ID, ins.PRODUCT_INSTANCE_FOR_HOUR, ins.MAX_PRODUCT_INSTANCE, ins.DATE_FROM, ins.DATE_TO);

MERGE INTO APP_PBE.TI_TRAINING_CATEGORY_PARAMS ug USING (
  SELECT
    'KCY' CATEGORY_ID,
    (SELECT ID FROM APP_PBE.GRANT_PROGRAMS WHERE upper(PROGRAM_NAME) = upper('Kierunek Kariera')) GRANT_PROGRAM_ID,
    2 PRODUCT_INSTANCE_FOR_HOUR,
    null MAX_PRODUCT_INSTANCE,
    (SELECT START_DATE FROM APP_PBE.GRANT_PROGRAMS WHERE upper(PROGRAM_NAME) = upper('Kierunek Kariera'))  DATE_FROM,
    null DATE_TO
  FROM dual
) ins
ON (ug.CATEGORY_ID = ins.CATEGORY_ID AND ug.GRANT_PROGRAM_ID = ins.GRANT_PROGRAM_ID)
WHEN MATCHED THEN
  UPDATE SET ug.PRODUCT_INSTANCE_FOR_HOUR = ins.PRODUCT_INSTANCE_FOR_HOUR, ug.MAX_PRODUCT_INSTANCE = ins.MAX_PRODUCT_INSTANCE, ug.DATE_FROM = ins.DATE_FROM, ug.DATE_TO = ins.DATE_TO
WHEN NOT MATCHED THEN INSERT
  (ID, CATEGORY_ID, GRANT_PROGRAM_ID, PRODUCT_INSTANCE_FOR_HOUR, MAX_PRODUCT_INSTANCE, DATE_FROM, DATE_TO)
  VALUES (2, ins.CATEGORY_ID, ins.GRANT_PROGRAM_ID, ins.PRODUCT_INSTANCE_FOR_HOUR, ins.MAX_PRODUCT_INSTANCE, ins.DATE_FROM, ins.DATE_TO);

MERGE INTO APP_PBE.TI_TRAINING_CATEGORY_PARAMS ug USING (
  SELECT
    'INN' CATEGORY_ID,
    (SELECT ID FROM APP_PBE.GRANT_PROGRAMS WHERE upper(PROGRAM_NAME) = upper('Kierunek Kariera')) GRANT_PROGRAM_ID,
    3 PRODUCT_INSTANCE_FOR_HOUR,
    null MAX_PRODUCT_INSTANCE,
    (SELECT START_DATE FROM APP_PBE.GRANT_PROGRAMS WHERE upper(PROGRAM_NAME) = upper('Kierunek Kariera'))  DATE_FROM,
    null DATE_TO
  FROM dual
) ins
ON (ug.CATEGORY_ID = ins.CATEGORY_ID AND ug.GRANT_PROGRAM_ID = ins.GRANT_PROGRAM_ID)
WHEN MATCHED THEN
  UPDATE SET ug.PRODUCT_INSTANCE_FOR_HOUR = ins.PRODUCT_INSTANCE_FOR_HOUR, ug.MAX_PRODUCT_INSTANCE = ins.MAX_PRODUCT_INSTANCE, ug.DATE_FROM = ins.DATE_FROM, ug.DATE_TO = ins.DATE_TO
WHEN NOT MATCHED THEN INSERT
  (ID, CATEGORY_ID, GRANT_PROGRAM_ID, PRODUCT_INSTANCE_FOR_HOUR, MAX_PRODUCT_INSTANCE, DATE_FROM, DATE_TO)
  VALUES (3, ins.CATEGORY_ID, ins.GRANT_PROGRAM_ID, ins.PRODUCT_INSTANCE_FOR_HOUR, ins.MAX_PRODUCT_INSTANCE, ins.DATE_FROM, ins.DATE_TO);

MERGE INTO APP_PBE.TI_TRAINING_CATEGORY_PARAMS ug USING (
  SELECT
    'EGZ' CATEGORY_ID,
    (SELECT ID FROM APP_PBE.GRANT_PROGRAMS WHERE upper(PROGRAM_NAME) = upper('Kierunek Kariera')) GRANT_PROGRAM_ID,
    null PRODUCT_INSTANCE_FOR_HOUR,
    40 MAX_PRODUCT_INSTANCE,
    (SELECT START_DATE FROM APP_PBE.GRANT_PROGRAMS WHERE upper(PROGRAM_NAME) = upper('Kierunek Kariera'))  DATE_FROM,
    null DATE_TO
  FROM dual
) ins
ON (ug.CATEGORY_ID = ins.CATEGORY_ID AND ug.GRANT_PROGRAM_ID = ins.GRANT_PROGRAM_ID)
WHEN MATCHED THEN
  UPDATE SET ug.PRODUCT_INSTANCE_FOR_HOUR = ins.PRODUCT_INSTANCE_FOR_HOUR, ug.MAX_PRODUCT_INSTANCE = ins.MAX_PRODUCT_INSTANCE, ug.DATE_FROM = ins.DATE_FROM, ug.DATE_TO = ins.DATE_TO
WHEN NOT MATCHED THEN INSERT
  (ID, CATEGORY_ID, GRANT_PROGRAM_ID, PRODUCT_INSTANCE_FOR_HOUR, MAX_PRODUCT_INSTANCE, DATE_FROM, DATE_TO)
  VALUES (4, ins.CATEGORY_ID, ins.GRANT_PROGRAM_ID, ins.PRODUCT_INSTANCE_FOR_HOUR, ins.MAX_PRODUCT_INSTANCE, ins.DATE_FROM, ins.DATE_TO);

