

CREATE TABLE APP_PBE.ORDER_FLOW_ST_TRANS_ELEM_FLAGS(
  ORDER_FLOW_ID NUMBER NOT NULL,
  STATUS_ID	VARCHAR2(10 BYTE) NOT NULL,
  ACTION_ID	NUMBER NOT NULL,
  ELEMENT_ID	VARCHAR2(10 BYTE) NOT NULL,
  FLAGS	VARCHAR2(3 BYTE)
);

-- uprawnienia
BEGIN
  dbms_output.put_line(SYS.PK_ADMIN.F_GRANT_TO_EAGLE('APP_PBE', 'EAGLE', 'ORDER_FLOW_ST_TRANS_ELEM_FLAGS', 'ALL'));
  dbms_output.put_line(SYS.PK_ADMIN.F_GRANT_TO_EAGLE('APP_PBE', 'SRV_EE', 'ORDER_FLOW_ST_TRANS_ELEM_FLAGS', 'ALL'));
  dbms_output.put_line(SYS.PK_ADMIN.F_GRANT_TO_EAGLE('APP_PBE', 'DEVELOPER', 'ORDER_FLOW_ST_TRANS_ELEM_FLAGS', 'SELECT'));
END;
/


-- Klucze
CREATE UNIQUE INDEX APP_PBE.ORDER_FLOW_ST_TRANS_EL_FL_PK ON APP_PBE.ORDER_FLOW_ST_TRANS_ELEM_FLAGS (ORDER_FLOW_ID, STATUS_ID, ACTION_ID, ELEMENT_ID);
ALTER TABLE APP_PBE.ORDER_FLOW_ST_TRANS_ELEM_FLAGS ADD CONSTRAINT ORDER_FLOW_ST_TRANS_EL_FL_PK PRIMARY KEY (ORDER_FLOW_ID, STATUS_ID, ACTION_ID, ELEMENT_ID);

ALTER TABLE APP_PBE.ORDER_FLOW_ST_TRANS_ELEM_FLAGS ADD CONSTRAINT ORD_FLO_ST_TRA_EL_FL_TRAN_FK FOREIGN KEY (ORDER_FLOW_ID, STATUS_ID, ACTION_ID)
REFERENCES APP_PBE.ORDER_FLOW_STATUS_TRANSITIONS (ORDER_FLOW_ID, STATUS_ID, ACTION_ID);
ALTER TABLE APP_PBE.ORDER_FLOW_ST_TRANS_ELEM_FLAGS ADD CONSTRAINT ORD_FLO_ST_TRA_EL_FL_EINSTA_FK FOREIGN KEY (STATUS_ID, ELEMENT_ID)
REFERENCES APP_PBE.ORDER_FLOW_ELEMENTS_IN_STATUS (STATUS_ID, ELEMENT_ID);





-- Komentarze
COMMENT ON TABLE APP_PBE.ORDER_FLOW_ST_TRANS_ELEM_FLAGS IS '@Author(Tomasz Bilski); @Project(GryfBonEl); @Date(2017-05-21);@Purpose(Flagi (np. wymagalnoœæ) elementów/pól zamówieñ dla przejœæ miêdzy statusami (podczas wywo³ania konkretnej akcji - przycisku na formatce));';
COMMENT ON COLUMN APP_PBE.ORDER_FLOW_ST_TRANS_ELEM_FLAGS.ORDER_FLOW_ID IS 'ID przep³ywu zamówienia';
COMMENT ON COLUMN APP_PBE.ORDER_FLOW_ST_TRANS_ELEM_FLAGS.STATUS_ID IS 'ID statusu';
COMMENT ON COLUMN APP_PBE.ORDER_FLOW_ST_TRANS_ELEM_FLAGS.ACTION_ID IS 'ID akcji';
COMMENT ON COLUMN APP_PBE.ORDER_FLOW_ST_TRANS_ELEM_FLAGS.ELEMENT_ID IS 'ID elementu';
COMMENT ON COLUMN APP_PBE.ORDER_FLOW_ST_TRANS_ELEM_FLAGS.FLAGS IS 'Flagi dotycz¹ce elementu (g³ównie zwi¹zane z atrybutami). Mo¿na zastosowaæ superpozycjê flag:
I - Insertable,
U - Updateable,
M - Mandatory,
w przypadku braku flagi zak³adamy, ¿e atrybut jest read only.
';

