
ALTER TABLE APP_PBE.PBE_PRODUCT_INSTANCES DISABLE CONSTRAINT PBE_PRD_EM_FK;

UPDATE APP_PBE.PBE_PRODUCT_EMISSIONS E
SET  E.ID = 1
WHERE E.ID = 'KK_BON_ELE_EMIS_01';

UPDATE APP_PBE.PBE_PRODUCT_EMISSIONS E
SET  E.ID = 2
WHERE E.ID = 'KK_BON_ELE_EMIS_02';


UPDATE APP_PBE.PBE_PRODUCT_INSTANCES E
SET E.PRODUCT_EMISSION_ID = 1 
WHERE E.PRODUCT_EMISSION_ID = 'KK_BON_ELE_EMIS_01';

UPDATE APP_PBE.PBE_PRODUCT_INSTANCES E
SET E.PRODUCT_EMISSION_ID = 2 
WHERE E.PRODUCT_EMISSION_ID = 'KK_BON_ELE_EMIS_02';


ALTER TABLE APP_PBE.PBE_PRODUCT_INSTANCES DROP CONSTRAINT PBE_PRD_EM_FK;

ALTER TABLE APP_PBE.PBE_PRODUCT_EMISSIONS DISABLE CONSTRAINT PBE_PRD_EM_PK;

ALTER TABLE APP_PBE.PBE_PRODUCT_EMISSIONS ADD ID_TMP NUMBER(10);

UPDATE APP_PBE.PBE_PRODUCT_EMISSIONS SET ID_TMP = ID;

ALTER TABLE APP_PBE.PBE_PRODUCT_EMISSIONS MODIFY ID NULL;

UPDATE APP_PBE.PBE_PRODUCT_EMISSIONS SET ID = NULL;

ALTER TABLE APP_PBE.PBE_PRODUCT_EMISSIONS MODIFY ID NUMBER(10);

UPDATE APP_PBE.PBE_PRODUCT_EMISSIONS SET ID = ID_TMP;

COMMIT;

ALTER TABLE APP_PBE.PBE_PRODUCT_EMISSIONS DROP COLUMN ID_TMP;


ALTER INDEX APP_PBE.PBE_PRD_EM_PK REBUILD;

ALTER TABLE APP_PBE.PBE_PRODUCT_EMISSIONS ENABLE CONSTRAINT PBE_PRD_EM_PK;


ALTER TABLE APP_PBE.PBE_PRODUCT_INSTANCES ADD PRODUCT_EMISSION_ID_TMP NUMBER(10);

UPDATE APP_PBE.PBE_PRODUCT_INSTANCES I SET I.PRODUCT_EMISSION_ID_TMP = I.PRODUCT_EMISSION_ID;

UPDATE APP_PBE.PBE_PRODUCT_INSTANCES I SET I.PRODUCT_EMISSION_ID = NULL;

COMMIT;

ALTER TABLE APP_PBE.PBE_PRODUCT_INSTANCES MODIFY PRODUCT_EMISSION_ID NUMBER(10);

UPDATE APP_PBE.PBE_PRODUCT_INSTANCES I SET I.PRODUCT_EMISSION_ID = I.PRODUCT_EMISSION_ID_TMP;

COMMIT;

ALTER TABLE APP_PBE.PBE_PRODUCT_INSTANCES ADD (
  CONSTRAINT PBE_PRD_EM_FK 
  FOREIGN KEY (PRODUCT_EMISSION_ID) 
  REFERENCES APP_PBE.PBE_PRODUCT_EMISSIONS (ID)
  ENABLE VALIDATE
  );

ALTER TABLE APP_PBE.PBE_PRODUCT_INSTANCES DROP COLUMN PRODUCT_EMISSION_ID_TMP;


-----------------------------
-- STATUSY
-----------------------------


ALTER TABLE APP_PBE.PBE_PRODUCT_INSTANCES DROP    
  CONSTRAINT PB_PRD_INST_ST_DIC_FK ;

UPDATE APP_PBE.PBE_PRODUCT_INSTANCE_STATUSES S
SET  S.ID = SUBSTR(S.ID,1,3);

UPDATE APP_PBE.PBE_PRODUCT_INSTANCE_STATUSES S
SET  S.ID = 'RMB'
WHERE S.ID = 'REI';


UPDATE APP_PBE.PBE_PRODUCT_INSTANCES I
SET    I.STATUS_ID = SUBSTR(I.STATUS_ID,1,3); 

UPDATE APP_PBE.PBE_PRODUCT_INSTANCES I
SET    I.STATUS_ID = 'RMB'
WHERE  I.STATUS_ID = 'REI';

COMMIT;

ALTER TABLE APP_PBE.PBE_PRODUCT_INSTANCE_STATUSES MODIFY ID VARCHAR2(3);

ALTER TABLE APP_PBE.PBE_PRODUCT_INSTANCES MODIFY STATUS_ID VARCHAR2(3);

ALTER TABLE APP_PBE.PBE_PRODUCT_INSTANCES ADD    
  CONSTRAINT PB_PRD_INST_ST_DIC_FK 
  FOREIGN KEY (STATUS_ID) 
  REFERENCES APP_PBE.PBE_PRODUCT_INSTANCE_STATUSES (ID)
  ENABLE VALIDATE;


-----------------------------
-- STATUSY
-----------------------------


ALTER TABLE APP_PBE.PBE_PRODUCTS ADD   LAST_INSTANCE_NUM NUMBER(10);

COMMENT ON COLUMN APP_PBE.PBE_PRODUCTS.LAST_INSTANCE_NUM IS 'Numer ostatniej wygenerowanej instancji (APP_PBE.PBE_PRODUCT_INSTANCES.NUM)'; 

UPDATE APP_PBE.PBE_PRODUCTS P SET LAST_INSTANCE_NUM = (SELECT NVL(MAX(I.NUM),0) FROM APP_PBE.PBE_PRODUCT_INSTANCES I WHERE I.PRD_ID= P.PRD_ID);

ALTER TABLE APP_PBE.PBE_PRODUCTS MODIFY  LAST_INSTANCE_NUM NOT NULL;
