CREATE TABLE APP_PBE.E_REIMBURSEMENT_EMAILS
(
  ID NUMBER NOT NULL,
  E_REIMBURSEMENT_ID NUMBER NOT NULL,
  EMAIL_INSTANCE_ID NUMBER,
  EMAIL_TYPE VARCHAR2(30) NOT NULL,
  EMAILS_TO VARCHAR2(100) NOT NULL,
  EMAIL_SUBJECT VARCHAR2(200) NOT NULL,
  EMAIL_BODY VARCHAR2(500) NOT NULL,
  VERSION NUMBER NOT NULL,
  CREATED_USER VARCHAR2(100) NOT NULL,
  CREATED_TIMESTAMP TIMESTAMP(6) NOT NULL,
  MODIFIED_USER VARCHAR2(100) NOT NULL,
  MODIFIED_TIMESTAMP TIMESTAMP(6) NOT NULL
);

BEGIN
  dbms_output.put_line(SYS.PK_ADMIN.F_GRANT_TO_EAGLE('APP_PBE', 'EAGLE', 'E_REIMBURSEMENT_EMAILS', 'ALL'));
  dbms_output.put_line(SYS.PK_ADMIN.F_GRANT_TO_EAGLE('APP_PBE', 'SRV_EE', 'E_REIMBURSEMENT_EMAILS', 'ALL'));
  dbms_output.put_line(SYS.PK_ADMIN.F_GRANT_TO_EAGLE('APP_PBE', 'DEVELOPER', 'E_REIMBURSEMENT_EMAILS', 'SELECT'));
END;
/

-- Klucze
CREATE UNIQUE INDEX APP_PBE.E_REIMB_MAIL_PK ON APP_PBE.E_REIMBURSEMENT_EMAILS (ID);
ALTER TABLE APP_PBE.E_REIMBURSEMENT_EMAILS ADD CONSTRAINT E_REIMB_MAIL_PK PRIMARY KEY (ID);

--KLUCZE OBCE
ALTER TABLE APP_PBE.E_REIMBURSEMENT_EMAILS ADD CONSTRAINT E_REIMB_MAIL_E_REIMB_FK FOREIGN KEY (E_REIMBURSEMENT_ID) REFERENCES APP_PBE.E_REIMBURSEMENTS (ID);
ALTER TABLE APP_PBE.E_REIMBURSEMENT_EMAILS ADD CONSTRAINT E_REIMB_MAIL_MAIL_INST_FK FOREIGN KEY (EMAIL_INSTANCE_ID) REFERENCES APP_PBE.EMAIL_INSTANCES (ID);

COMMENT ON TABLE APP_PBE.E_REIMBURSEMENT_EMAILS IS '@Author(Adam Kmieciñski); @Project(GryfBonEl); @Date(2016-12-21);@Purpose(Tabela z mailami wys³anymi z poziomu rozliczenia);';
COMMENT ON COLUMN APP_PBE.E_REIMBURSEMENT_EMAILS.ID IS 'Identyfikator klucz sztuczny';
COMMENT ON COLUMN APP_PBE.E_REIMBURSEMENT_EMAILS.E_REIMBURSEMENT_ID IS 'Identyfikator rozliczenia elektronicznego';
COMMENT ON COLUMN APP_PBE.E_REIMBURSEMENT_EMAILS.EMAIL_INSTANCE_ID IS 'Identyfikator instancji maila';
COMMENT ON COLUMN APP_PBE.E_REIMBURSEMENT_EMAILS.EMAIL_TYPE IS 'Typ maila';
COMMENT ON COLUMN APP_PBE.E_REIMBURSEMENT_EMAILS.EMAILS_TO IS 'Adresy e-mail do';
COMMENT ON COLUMN APP_PBE.E_REIMBURSEMENT_EMAILS.EMAIL_SUBJECT IS 'Temat maila';
COMMENT ON COLUMN APP_PBE.E_REIMBURSEMENT_EMAILS.EMAIL_BODY IS 'Treœæ maila';
COMMENT ON COLUMN APP_PBE.E_REIMBURSEMENT_EMAILS.VERSION IS 'Wersja. Kolumna techniczna u¿ywana do mechanizmu Optimistic Lock';
COMMENT ON COLUMN APP_PBE.E_REIMBURSEMENT_EMAILS.CREATED_USER IS 'Login u¿ytkownika, który utworzy³ rekord';
COMMENT ON COLUMN APP_PBE.E_REIMBURSEMENT_EMAILS.CREATED_TIMESTAMP IS 'Data utworzenia rekordu';
COMMENT ON COLUMN APP_PBE.E_REIMBURSEMENT_EMAILS.MODIFIED_USER IS 'Login u¿ytkownika, który ostatnio modyfikowa³ rekord';
COMMENT ON COLUMN APP_PBE.E_REIMBURSEMENT_EMAILS.MODIFIED_TIMESTAMP IS 'Data ostatniej modyfikacji rekordu';
