

CREATE TABLE APP_PBE.TI_TRAINING_CATEGORY_CAT
(
	ID VARCHAR2(10 BYTE) NOT NULL,
	NAME VARCHAR2(100 BYTE) NOT NULL,
	ORDINAL NUMBER(10) NOT NULL
);

-- uprawnienia
BEGIN
  dbms_output.put_line(SYS.PK_ADMIN.F_GRANT_TO_EAGLE('APP_PBE', 'EAGLE', 'TI_TRAINING_CATEGORY_CAT', 'ALL'));
  dbms_output.put_line(SYS.PK_ADMIN.F_GRANT_TO_EAGLE('APP_PBE', 'SRV_EE', 'TI_TRAINING_CATEGORY_CAT', 'ALL'));
  dbms_output.put_line(SYS.PK_ADMIN.F_GRANT_TO_EAGLE('APP_PBE', 'DEVELOPER', 'TI_TRAINING_CATEGORY_CAT', 'SELECT'));
END;
/

-- Klucze
CREATE UNIQUE INDEX APP_PBE.TI_TRA_CAT_CAT_PK ON APP_PBE.TI_TRAINING_CATEGORY_CAT (ID);
ALTER TABLE APP_PBE.TI_TRAINING_CATEGORY_CAT ADD CONSTRAINT TI_TRA_CAT_CAT_PK PRIMARY KEY (ID);

-- Komentarze
COMMENT ON TABLE APP_PBE.TI_TRAINING_CATEGORY_CAT IS '@Author(Tomasz Bilski); @Project(GryfBonEl); @Date(2016-11-05);@Purpose(Tabel wartoœci s³ownikowych dla katalogów);';
COMMENT ON COLUMN APP_PBE.TI_TRAINING_CATEGORY_CAT.ID IS 'Kod s³ownika. Klucz g³ówny';
COMMENT ON COLUMN APP_PBE.TI_TRAINING_CATEGORY_CAT.NAME IS 'Opis wartoœci s³ownikowej';
COMMENT ON COLUMN APP_PBE.TI_TRAINING_CATEGORY_CAT.ORDINAL IS 'Liczba porz¹dkowa';
