CREATE TABLE APP_PBE.E_REIMBURSEMENT_INVOICES
(
  ID NUMBER NOT NULL,
  E_REIMBURSEMENT_ID NUMBER NOT NULL,
  INVOICE_ID NUMBER NOT NULL,
  INVOICE_NUMBER VARCHAR2(30 BYTE) NOT NULL,
  INVOICE_TYPE VARCHAR2(20 BYTE) NOT NULL,
  INVOICE_DATE DATE NOT NULL,
  VERSION NUMBER NOT NULL,
  CREATED_USER VARCHAR2(30 BYTE) NOT NULL,
  CREATED_TIMESTAMP TIMESTAMP(6) NOT NULL,
  MODIFIED_USER VARCHAR2(30 BYTE) NOT NULL,
  MODIFIED_TIMESTAMP TIMESTAMP(6) NOT NULL
);

BEGIN
  dbms_output.put_line(SYS.PK_ADMIN.F_GRANT_TO_EAGLE('APP_PBE', 'EAGLE', 'E_REIMBURSEMENT_INVOICES', 'ALL'));
  dbms_output.put_line(SYS.PK_ADMIN.F_GRANT_TO_EAGLE('APP_PBE', 'SRV_EE', 'E_REIMBURSEMENT_INVOICES', 'ALL'));
  dbms_output.put_line(SYS.PK_ADMIN.F_GRANT_TO_EAGLE('APP_PBE', 'DEVELOPER', 'E_REIMBURSEMENT_INVOICES', 'SELECT'));
  dbms_output.put_line(SYS.PK_ADMIN.F_GRANT_TO_EAGLE('APP_FIN', 'APP_PBE', 'INVOICES', 'REFERENCES'));
END;
/

-- Klucze
CREATE UNIQUE INDEX APP_PBE.E_REIMB_INV_PK ON APP_PBE.E_REIMBURSEMENT_INVOICES (ID);
ALTER TABLE APP_PBE.E_REIMBURSEMENT_INVOICES ADD CONSTRAINT E_REIMB_INV_PK PRIMARY KEY (ID);

--KLUCZE OBCE
ALTER TABLE APP_PBE.E_REIMBURSEMENT_INVOICES ADD CONSTRAINT E_REIMB_INV_E_REIMB_FK FOREIGN KEY (E_REIMBURSEMENT_ID) REFERENCES APP_PBE.E_REIMBURSEMENTS (ID);
ALTER TABLE APP_PBE.E_REIMBURSEMENT_INVOICES ADD CONSTRAINT E_REIMB_INV_E_INV_FK FOREIGN KEY (INVOICE_ID) REFERENCES APP_FIN.INVOICES (ID);

COMMENT ON TABLE APP_PBE.E_REIMBURSEMENT_INVOICES IS '@Author(Andrzej Dziobek); @Project(GryfBonEl); @Date(2016-12-09);@Purpose(Tabela ??cz?ca rozliczenia elektroniczne z fakturami);';
COMMENT ON COLUMN APP_PBE.E_REIMBURSEMENT_INVOICES.ID IS 'Identyfikato klucz sztuczny';
COMMENT ON COLUMN APP_PBE.E_REIMBURSEMENT_INVOICES.E_REIMBURSEMENT_ID IS 'Identyfikator rozliczenia elektronicznego';
COMMENT ON COLUMN APP_PBE.E_REIMBURSEMENT_INVOICES.INVOICE_ID IS 'Identyfikator umowy';
COMMENT ON COLUMN APP_PBE.E_REIMBURSEMENT_INVOICES.INVOICE_NUMBER IS 'Numer umowy';
COMMENT ON COLUMN APP_PBE.E_REIMBURSEMENT_INVOICES.INVOICE_TYPE IS 'Typ umowy';
COMMENT ON COLUMN APP_PBE.E_REIMBURSEMENT_INVOICES.INVOICE_DATE IS 'Data umowy';
COMMENT ON COLUMN APP_PBE.E_REIMBURSEMENT_INVOICES.VERSION IS 'Wersja. Kolumna techniczna u?ywana do mechanizmu Optimistic Lock';
COMMENT ON COLUMN APP_PBE.E_REIMBURSEMENT_INVOICES.CREATED_USER IS 'Login u?ytkownika, kt?ry utworzy? rekord';
COMMENT ON COLUMN APP_PBE.E_REIMBURSEMENT_INVOICES.CREATED_TIMESTAMP IS 'Data utworzenia rekordu';
COMMENT ON COLUMN APP_PBE.E_REIMBURSEMENT_INVOICES.MODIFIED_USER IS 'Login u?ytkownika, kt?ry ostatnio modyfikowa? rekord';
COMMENT ON COLUMN APP_PBE.E_REIMBURSEMENT_INVOICES.MODIFIED_TIMESTAMP IS 'Data ostatniej modyfikacji rekordu';
