ALTER TABLE APP_PBE.E_REIMBURSEMENT_REPORTS ADD (E_REIMB_INV_ID NUMBER);

ALTER TABLE APP_PBE.E_REIMBURSEMENT_REPORTS ADD CONSTRAINT E_REIMB_INV_ID_FK FOREIGN KEY (E_REIMB_INV_ID) REFERENCES APP_PBE.E_REIMBURSEMENT_INVOICES (ID);

COMMENT ON COLUMN APP_PBE.E_REIMBURSEMENT_REPORTS.E_REIMB_INV_ID IS 'ID dokumentu ksiêgowego powi¹zanego z tym raportem';