CREATE TABLE APP_PBE.GRANT_PROGRAM_ATTACH_REQ
(
	GRANT_PROGRAM_ID NUMBER NOT NULL,    -- Program dofinansowania. Klucz obcy do APP_PBE.GRANT_PROGRAMS
	ATTACH_TYPE VARCHAR2(10) NOT NULL,    -- Typ dokumentu. Klucz obcy do tabeli APP_PBE.ATTACHMENT_TYPES
	DATE_FROM DATE,    -- Data od obowi¹zywania wymagalnoœci typu dokumentu
	DATE_TO DATE    -- Data do obowi¹zywania wymagalnoœci typu dokumentu
);

-- uprawnienia
BEGIN
  dbms_output.put_line(SYS.PK_ADMIN.F_GRANT_TO_EAGLE('APP_PBE', 'EAGLE', 'GRANT_PROGRAM_ATTACH_REQ', 'ALL'));
  dbms_output.put_line(SYS.PK_ADMIN.F_GRANT_TO_EAGLE('APP_PBE', 'SRV_EE', 'GRANT_PROGRAM_ATTACH_REQ', 'ALL'));
  dbms_output.put_line(SYS.PK_ADMIN.F_GRANT_TO_EAGLE('APP_PBE', 'DEVELOPER', 'GRANT_PROGRAM_ATTACH_REQ', 'SELECT'));
END;
/

ALTER TABLE APP_PBE.GRANT_PROGRAM_ATTACH_REQ
 ADD CONSTRAINT GR_PR_ATT_REQ_ATT_TYPE_FK
	FOREIGN KEY (ATTACH_TYPE) REFERENCES APP_PBE.ATTACHMENT_TYPES (CODE);

ALTER TABLE APP_PBE.GRANT_PROGRAM_ATTACH_REQ
 ADD CONSTRAINT GR_PR_ATT_REQ_GR_PR_FK
	FOREIGN KEY (GRANT_PROGRAM_ID) REFERENCES APP_PBE.GRANT_PROGRAMS (ID);

COMMENT ON TABLE APP_PBE.GRANT_PROGRAM_ATTACH_REQ IS '@Author(Adam Kmieciñski); @Project(Gryf-PBE); @Date(2016-11-22);@Purpose(Tabela przechowuj¹ca wymagane dokumenty dla programu dofinansowania);';

COMMENT ON COLUMN APP_PBE.GRANT_PROGRAM_ATTACH_REQ.GRANT_PROGRAM_ID IS 'Program dofinansowania. Klucz obcy do APP_PBE.GRANT_PROGRAMS';
COMMENT ON COLUMN APP_PBE.GRANT_PROGRAM_ATTACH_REQ.ATTACH_TYPE IS 'Typ dokumentu. Klucz obcy do tabeli APP_PBE.ATTACHMENT_TYPES';
COMMENT ON COLUMN APP_PBE.GRANT_PROGRAM_ATTACH_REQ.DATE_FROM IS 'Data od obowi¹zywania wymagalnoœci typu dokumentu';
COMMENT ON COLUMN APP_PBE.GRANT_PROGRAM_ATTACH_REQ.DATE_TO IS 'Data do obowi¹zywania wymagalnoœci typu dokumentu';

