
ALTER TABLE APP_PBE.PBE_PRODUCT_INSTANCE_E DROP COLUMN VERSION;
ALTER TABLE APP_PBE.PBE_PRODUCT_INSTANCE_E DROP COLUMN MODIFIED_TIMESTAMP;
ALTER TABLE APP_PBE.PBE_PRODUCT_INSTANCE_E DROP COLUMN MODIFIED_USER;


ALTER TABLE APP_PBE.PBE_PRODUCT_INSTANCE_POOL_E DROP COLUMN VERSION;
ALTER TABLE APP_PBE.PBE_PRODUCT_INSTANCE_POOL_E DROP COLUMN MODIFIED_TIMESTAMP;
ALTER TABLE APP_PBE.PBE_PRODUCT_INSTANCE_POOL_E DROP COLUMN MODIFIED_USER;
