ALTER TABLE APP_PBE.TRAINING_INSTITUTION_USERS
	ADD (LAST_LOGIN_FAILURE_DATE DATE,
	 LOGIN_FAILURE_ATTEMPTS NUMBER(1) DEFAULT 0);


ALTER TABLE APP_PBE.TRAINING_INSTITUTION_USERS
	RENAME COLUMN LAST_LOGIN_DATE TO LAST_LOGIN_SUCCESS_DATE;