CREATE TABLE APP_PBE.PBE_PRODUCT_EMISSIONS
(
	ID VARCHAR2(20 BYTE) NOT NULL,
	PRD_ID VARCHAR2(20 BYTE) NOT NULL,
	GRANT_PROGRAM_ID NUMBER NOT NULL,
	NAME VARCHAR2(100 BYTE) NOT NULL,
	DESCRIPTION VARCHAR2(200 BYTE),
	EMISSION_DATE DATE NOT NULL,
	QUANTITY NUMBER(10) NOT NULL
);

-- uprawnienia
BEGIN
  dbms_output.put_line(SYS.PK_ADMIN.F_GRANT_TO_EAGLE('APP_PBE', 'EAGLE', 'PBE_PRODUCT_EMISSIONS', 'ALL'));
  dbms_output.put_line(SYS.PK_ADMIN.F_GRANT_TO_EAGLE('APP_PBE', 'SRV_EE', 'PBE_PRODUCT_EMISSIONS', 'ALL'));
  dbms_output.put_line(SYS.PK_ADMIN.F_GRANT_TO_EAGLE('APP_PBE', 'DEVELOPER', 'PBE_PRODUCT_EMISSIONS', 'SELECT'));
END;
/

-- Klucz g³ówny
CREATE UNIQUE INDEX APP_PBE.PBE_PRD_EM_PK ON APP_PBE.PBE_PRODUCT_EMISSIONS (ID);
ALTER TABLE APP_PBE.PBE_PRODUCT_EMISSIONS ADD CONSTRAINT PBE_PRD_EM_PK PRIMARY KEY (ID);

-- Klucze obce
ALTER TABLE APP_PBE.PBE_PRODUCT_EMISSIONS ADD CONSTRAINT GRT_PRG_FK FOREIGN KEY (GRANT_PROGRAM_ID) REFERENCES APP_PBE.GRANT_PROGRAMS (ID);
ALTER TABLE APP_PBE.PBE_PRODUCT_EMISSIONS ADD CONSTRAINT PBE_PRD_FK FOREIGN KEY (PRD_ID) REFERENCES APP_PBE.PBE_PRODUCTS (PRD_ID);

-- Komentarze
COMMENT ON TABLE APP_PBE.PBE_PRODUCT_EMISSIONS IS '@Author(Adam Kmieciñski); @Project(GryfBonEl); @Date(2016-10-10);@Purpose(Tabela przechowuj¹ca podstawowe dane dotycz¹ce emisji produktów);';
COMMENT ON COLUMN APP_PBE.PBE_PRODUCT_EMISSIONS.ID IS 'Unikalne ID emisji. Klucz g³ówny';
COMMENT ON COLUMN APP_PBE.PBE_PRODUCT_EMISSIONS.PRD_ID IS 'ID produktu';
COMMENT ON COLUMN APP_PBE.PBE_PRODUCT_EMISSIONS.GRANT_PROGRAM_ID IS 'ID programu dofinansowania';
COMMENT ON COLUMN APP_PBE.PBE_PRODUCT_EMISSIONS.NAME IS 'Nazwa emisji';
COMMENT ON COLUMN APP_PBE.PBE_PRODUCT_EMISSIONS.DESCRIPTION IS 'Opis emisji';
COMMENT ON COLUMN APP_PBE.PBE_PRODUCT_EMISSIONS.EMISSION_DATE IS 'Data emisji';
COMMENT ON COLUMN APP_PBE.PBE_PRODUCT_EMISSIONS.QUANTITY IS 'Iloœæ wygenerowanych produktów';