CREATE TABLE APP_PBE.PBE_PRODUCT_INSTANCES
(
	PRD_ID VARCHAR2(20) NOT NULL,
	PRI_NUMBER NUMBER(10) NOT NULL,
	ORD_ID NUMBER,
	PRE_ID NUMBER,
	RMS_ID NUMBER,
	PIS_CODE VARCHAR2(5),
	PRINT_NUMBER VARCHAR2(50),
	CRC NUMBER(10),
	VERSION NUMBER NOT NULL,
	CREATED_USER VARCHAR2(100) NOT NULL,
	CREATED_TIMESTAMP TIMESTAMP(6) NOT NULL,
	MODIFIED_USER VARCHAR2(100),
	MODIFIED_TIMESTAMP TIMESTAMP(6)
)
;

-- uprawnienia
BEGIN
  dbms_output.put_line(SYS.PK_ADMIN.F_GRANT_TO_EAGLE('APP_PBE', 'EAGLE', 'PBE_PRODUCT_INSTANCES', 'ALL'));
  dbms_output.put_line(SYS.PK_ADMIN.F_GRANT_TO_EAGLE('APP_PBE', 'SRV_EE', 'PBE_PRODUCT_INSTANCES', 'ALL'));
  dbms_output.put_line(SYS.PK_ADMIN.F_GRANT_TO_EAGLE('APP_PBE', 'DEVELOPER', 'PBE_PRODUCT_INSTANCES', 'SELECT'));
END;
/

-- Indeksy
CREATE UNIQUE INDEX APP_PBE.PBE_PRD_IN_PK ON APP_PBE.PBE_PRODUCT_INSTANCES (PRI_NUMBER,PRD_ID);

-- Klucze
ALTER TABLE APP_PBE.PBE_PRODUCT_INSTANCES 
 ADD CONSTRAINT PBE_PRD_IN_PK
	PRIMARY KEY (PRI_NUMBER,PRD_ID)
;

ALTER TABLE APP_PBE.PBE_PRODUCT_INSTANCES 
 ADD CONSTRAINT ORDERS_FK
	FOREIGN KEY (ORD_ID) REFERENCES APP_PBE.ORDERS (ID)
;

ALTER TABLE APP_PBE.PBE_PRODUCT_INSTANCES 
 ADD CONSTRAINT PBE_PRD_EM_FK
	FOREIGN KEY (PRE_ID) REFERENCES APP_PBE.PBE_PRODUCT_EMISSIONS (PRE_ID)
;

ALTER TABLE APP_PBE.PBE_PRODUCT_INSTANCES 
 ADD CONSTRAINT PBE_PRD_PRD_INS_FK
	FOREIGN KEY (PRD_ID) REFERENCES APP_PBE.PBE_PRODUCTS (PRD_ID)
;

ALTER TABLE APP_PBE.PBE_PRODUCT_INSTANCES 
 ADD CONSTRAINT PB_PRD_INST_ST_DIC_FK
	FOREIGN KEY (PIS_CODE) REFERENCES APP_PBE.PBE_PRD_INST_STATUS_DICS (PIS_CODE)
;

ALTER TABLE APP_PBE.PBE_PRODUCT_INSTANCES 
 ADD CONSTRAINT REIMBURSEMENTS_FK
	FOREIGN KEY (RMS_ID) REFERENCES APP_PBE.REIMBURSEMENTS (ID)
;

-- Komentarze
COMMENT ON TABLE APP_PBE.PBE_PRODUCT_INSTANCES IS '@Author(Adam Kmieciñski); @Project(GryfBonEl); @Date(2016-10-11);@Purpose(Tabela przechowuj¹ca dane instancji produktów);';

COMMENT ON COLUMN APP_PBE.PBE_PRODUCT_INSTANCES.PRD_ID IS 'ID produktu. Kolumna z³o¿onego klucza g³ównego';
COMMENT ON COLUMN APP_PBE.PBE_PRODUCT_INSTANCES.PRI_NUMBER IS 'Numer instancji produktu. Kolumna z³o¿onego klucza g³ównego';
COMMENT ON COLUMN APP_PBE.PBE_PRODUCT_INSTANCES.ORD_ID IS 'ID zamówienia';
COMMENT ON COLUMN APP_PBE.PBE_PRODUCT_INSTANCES.PRE_ID IS 'ID emisji produktu';
COMMENT ON COLUMN APP_PBE.PBE_PRODUCT_INSTANCES.RMS_ID IS 'ID rozliczenia';
COMMENT ON COLUMN APP_PBE.PBE_PRODUCT_INSTANCES.PIS_CODE IS 'Kod statusu instancji. Wartoœæ s³ownikowa';
COMMENT ON COLUMN APP_PBE.PBE_PRODUCT_INSTANCES.PRINT_NUMBER IS 'Number drukowany produktu';
COMMENT ON COLUMN APP_PBE.PBE_PRODUCT_INSTANCES.CRC IS 'Wyszczególniona liczba kontrolna w numerze drukowanym produktu';
COMMENT ON COLUMN APP_PBE.PBE_PRODUCT_INSTANCES.VERSION IS 'Wersja. Kolumna techniczna u¿ywana do mechanizmu Optimistic Lock';
COMMENT ON COLUMN APP_PBE.PBE_PRODUCT_INSTANCES.CREATED_USER IS 'Login u¿ytkownika, który utworzy³ rekord';
COMMENT ON COLUMN APP_PBE.PBE_PRODUCT_INSTANCES.CREATED_TIMESTAMP IS 'Data utworzenia rekordu';
COMMENT ON COLUMN APP_PBE.PBE_PRODUCT_INSTANCES.MODIFIED_USER IS 'Login u¿ytkownika, który ostatnio modyfikowa³ rekord';
COMMENT ON COLUMN APP_PBE.PBE_PRODUCT_INSTANCES.MODIFIED_TIMESTAMP IS 'Data ostatniej modyfikacji rekordu';