
-------------------------------------------------------------------
-----------------------ASYNCH_JOBS----------------------------
-------------------------------------------------------------------

CREATE TABLE APP_PBE.ASYNCH_JOBS
(
  ID NUMBER NOT NULL,
  TYPE VARCHAR2(20 BYTE) NOT NULL,
  PARAMS VARCHAR2(500 BYTE),
  DESCRIPTION VARCHAR2(1000 BYTE),
  STATUS VARCHAR2(5 BYTE) NOT NULL,
  NEXT_START_TIMESTAMP TIMESTAMP(6),
  ORDER_ID NUMBER,
  VERSION NUMBER NOT NULL,
  CREATED_USER VARCHAR2(30 BYTE) NOT NULL,
  CREATED_TIMESTAMP TIMESTAMP(6) NOT NULL,
  MODIFIED_USER VARCHAR2(30 BYTE) NOT NULL,
  MODIFIED_TIMESTAMP TIMESTAMP(6) NOT NULL
);

-- uprawnienia
BEGIN
  dbms_output.put_line(SYS.PK_ADMIN.F_GRANT_TO_EAGLE('APP_PBE', 'EAGLE', 'ASYNCH_JOBS', 'ALL'));
  dbms_output.put_line(SYS.PK_ADMIN.F_GRANT_TO_EAGLE('APP_PBE', 'SRV_EE', 'ASYNCH_JOBS', 'ALL'));
  dbms_output.put_line(SYS.PK_ADMIN.F_GRANT_TO_EAGLE('APP_PBE', 'DEVELOPER', 'ASYNCH_JOBS', 'SELECT'));
  dbms_output.put_line(SYS.PK_ADMIN.F_GRANT_TO_EAGLE('APP_STC', 'APP_PBE', 'ASYNCH_JOBS', 'REFERENCES'));
END;
/

-- Klucze
CREATE UNIQUE INDEX APP_PBE.ASYN_JOB_PK ON APP_PBE.ASYNCH_JOBS (ID);
ALTER TABLE APP_PBE.ASYNCH_JOBS ADD CONSTRAINT ASYN_JOB_PK_PK PRIMARY KEY (ID);

--OBCE
ALTER TABLE APP_PBE.ASYNCH_JOBS ADD CONSTRAINT ASY_JOB_ORD_FK FOREIGN KEY (ORDER_ID) REFERENCES APP_PBE.ORDERS (ID);


-- Komentarze
COMMENT ON TABLE APP_PBE.ASYNCH_JOBS IS '@Author(Tomasz Bilski); @Project(GryfBonEl); @Date(2016-12-02);@Purpose(Tabela przechowuj¹ca informacje o zadaniach asynchronicznych);';
COMMENT ON COLUMN APP_PBE.ASYNCH_JOBS.ID IS 'Indetyfikator klucz sztuczny';
COMMENT ON COLUMN APP_PBE.ASYNCH_JOBS.TYPE IS 'Typ zadania asynchronicznego';
COMMENT ON COLUMN APP_PBE.ASYNCH_JOBS.PARAMS IS 'Parametry zadnia asyncronicznego w formacje <param_key1>=<param_value1>;<param_key2>=<param_value2>';
COMMENT ON COLUMN APP_PBE.ASYNCH_JOBS.DESCRIPTION IS 'OPisa zadnia';
COMMENT ON COLUMN APP_PBE.ASYNCH_JOBS.STATUS IS 'Status';
COMMENT ON COLUMN APP_PBE.ASYNCH_JOBS.NEXT_START_TIMESTAMP IS 'Data nastepnego wykonania je¿eli null to od razu';
COMMENT ON COLUMN APP_PBE.ASYNCH_JOBS.ORDER_ID IS 'Idnetyfikator zamóienia';
COMMENT ON COLUMN APP_PBE.ASYNCH_JOBS.VERSION IS 'Kolumna techniczna u¿ywana do mechanizmu Optimistic Lock';
COMMENT ON COLUMN APP_PBE.ASYNCH_JOBS.CREATED_USER IS 'Login u¿ytkownika, który utworzy³ rekord';
COMMENT ON COLUMN APP_PBE.ASYNCH_JOBS.CREATED_TIMESTAMP IS 'Data utworzenia rekordu';
COMMENT ON COLUMN APP_PBE.ASYNCH_JOBS.MODIFIED_USER IS 'Login u¿ytkownika, który ostatnio modyfikowa³ rekord';
COMMENT ON COLUMN APP_PBE.ASYNCH_JOBS.MODIFIED_TIMESTAMP IS 'Data ostatniej modyfikacji rekordu';




CREATE SEQUENCE EAGLE.ASYN_JOB_SEQ
MINVALUE 1
MAXVALUE 9999999999999999999999999999
INCREMENT BY 1
START WITH 1
CACHE 20
NOORDER NOCYCLE;

-- uprawnienia
BEGIN
  dbms_output.put_line(SYS.PK_ADMIN.F_GRANT_TO_EAGLE('EAGLE', 'SRV_EE', 'ASYN_JOB_SEQ', 'ALL'));
  dbms_output.put_line(SYS.PK_ADMIN.F_GRANT_TO_EAGLE('EAGLE', 'DEVELOPER', 'ASYN_JOB_SEQ', 'SELECT'));
END;
/

-------------------------------------------------------------------
-----------------------IMPORT_DATA_ROWS----------------------------
-------------------------------------------------------------------

CREATE TABLE APP_PBE.IMPORT_DATA_ROWS
(
  ID NUMBER NOT NULL,
  IMPORT_JOB_ID NUMBER NOT NULL,
  ROW_NUM NUMBER(10) NOT NULL,
  DESCRIPTION VARCHAR2(1000 BYTE),
  STATUS VARCHAR2(5 BYTE) NOT NULL,
  VERSION NUMBER NOT NULL,
  CREATED_USER VARCHAR2(30 BYTE) NOT NULL,
  CREATED_TIMESTAMP TIMESTAMP(6) NOT NULL,
  MODIFIED_USER VARCHAR2(30 BYTE) NOT NULL,
  MODIFIED_TIMESTAMP TIMESTAMP(6) NOT NULL
);

-- uprawnienia
BEGIN
  dbms_output.put_line(SYS.PK_ADMIN.F_GRANT_TO_EAGLE('APP_PBE', 'EAGLE', 'IMPORT_DATA_ROWS', 'ALL'));
  dbms_output.put_line(SYS.PK_ADMIN.F_GRANT_TO_EAGLE('APP_PBE', 'SRV_EE', 'IMPORT_DATA_ROWS', 'ALL'));
  dbms_output.put_line(SYS.PK_ADMIN.F_GRANT_TO_EAGLE('APP_PBE', 'DEVELOPER', 'IMPORT_DATA_ROWS', 'SELECT'));
  dbms_output.put_line(SYS.PK_ADMIN.F_GRANT_TO_EAGLE('APP_STC', 'APP_PBE', 'IMPORT_DATA_ROWS', 'REFERENCES'));
END;
/

-- Klucze
CREATE UNIQUE INDEX APP_PBE.IMP_DATA_ROWS_PK ON APP_PBE.IMPORT_DATA_ROWS (ID);
ALTER TABLE APP_PBE.IMPORT_DATA_ROWS ADD CONSTRAINT IMP_DATA_ROWS_PK PRIMARY KEY (ID);

-- Unikaty
ALTER TABLE APP_PBE.IMPORT_DATA_ROWS ADD CONSTRAINT IMP_DATA_ROWS_JOBROW_UIX UNIQUE (IMPORT_JOB_ID, ROW_NUM);

-- Klucze obce
--ALTER TABLE APP_PBE.ASYNCH_JOBS ADD CONSTRAINT IMP_DATA_ROWS_ASYN_JOB_FK FOREIGN KEY (IMPORT_JOB_ID) REFERENCES APP_PBE.ASYNCH_JOBS (ID);




-- Komentarze
COMMENT ON TABLE APP_PBE.IMPORT_DATA_ROWS IS '@Author(Tomasz Bilski); @Project(GryfBonEl); @Date(2016-12-02);@Purpose(Tabela przechowuj¹ca informacje o imporcie danego wiersza z pliku);';
COMMENT ON COLUMN APP_PBE.IMPORT_DATA_ROWS.ID IS 'Indetyfikator klucz sztuczny';
COMMENT ON COLUMN APP_PBE.IMPORT_DATA_ROWS.IMPORT_JOB_ID IS 'Indetyfikator zlecenia importu pliku';
COMMENT ON COLUMN APP_PBE.IMPORT_DATA_ROWS.ROW_NUM IS 'Numer wiersza';
COMMENT ON COLUMN APP_PBE.IMPORT_DATA_ROWS.DESCRIPTION IS 'Opis';
COMMENT ON COLUMN APP_PBE.IMPORT_DATA_ROWS.STATUS IS 'Status';
COMMENT ON COLUMN APP_PBE.IMPORT_DATA_ROWS.VERSION IS 'Kolumna techniczna u¿ywana do mechanizmu Optimistic Lock';
COMMENT ON COLUMN APP_PBE.IMPORT_DATA_ROWS.CREATED_USER IS 'Login u¿ytkownika, który utworzy³ rekord';
COMMENT ON COLUMN APP_PBE.IMPORT_DATA_ROWS.CREATED_TIMESTAMP IS 'Data utworzenia rekordu';
COMMENT ON COLUMN APP_PBE.IMPORT_DATA_ROWS.MODIFIED_USER IS 'Login u¿ytkownika, który ostatnio modyfikowa³ rekord';
COMMENT ON COLUMN APP_PBE.IMPORT_DATA_ROWS.MODIFIED_TIMESTAMP IS 'Data ostatniej modyfikacji rekordu';

-------------------------------------------------------------------
-----------------------IMPORT_DATA_ROW_ERRORS----------------------
-------------------------------------------------------------------


CREATE TABLE APP_PBE.IMPORT_DATA_ROW_ERRORS
(
  ID NUMBER NOT NULL,
  IMPORT_DATA_ROW_ID NUMBER NOT NULL,
  PATH VARCHAR2(100 BYTE),
  MESSAGE VARCHAR2(1000 BYTE) NOT NULL,
  VERSION NUMBER NOT NULL,
  CREATED_USER VARCHAR2(30 BYTE) NOT NULL,
  CREATED_TIMESTAMP TIMESTAMP(6) NOT NULL,
  MODIFIED_USER VARCHAR2(30 BYTE) NOT NULL,
  MODIFIED_TIMESTAMP TIMESTAMP(6) NOT NULL
);

-- uprawnienia
BEGIN
  dbms_output.put_line(SYS.PK_ADMIN.F_GRANT_TO_EAGLE('APP_PBE', 'EAGLE', 'IMPORT_DATA_ROW_ERRORS', 'ALL'));
  dbms_output.put_line(SYS.PK_ADMIN.F_GRANT_TO_EAGLE('APP_PBE', 'SRV_EE', 'IMPORT_DATA_ROW_ERRORS', 'ALL'));
  dbms_output.put_line(SYS.PK_ADMIN.F_GRANT_TO_EAGLE('APP_PBE', 'DEVELOPER', 'IMPORT_DATA_ROW_ERRORS', 'SELECT'));
  dbms_output.put_line(SYS.PK_ADMIN.F_GRANT_TO_EAGLE('APP_STC', 'APP_PBE', 'IMPORT_DATA_ROW_ERRORS', 'REFERENCES'));
END;
/

-- Klucze
CREATE UNIQUE INDEX APP_PBE.IMP_DAT_ROW_ERR_PK ON APP_PBE.IMPORT_DATA_ROW_ERRORS (ID);
ALTER TABLE APP_PBE.IMPORT_DATA_ROW_ERRORS ADD CONSTRAINT IMP_DAT_ROW_ERR_PK PRIMARY KEY (ID);

-- Klucze obce
ALTER TABLE APP_PBE.IMPORT_DATA_ROW_ERRORS ADD CONSTRAINT IMP_DAT_ROW_ERR_ROW_FK FOREIGN KEY (IMPORT_DATA_ROW_ID) REFERENCES APP_PBE.IMPORT_DATA_ROWS (ID);

-- Komentarze
COMMENT ON TABLE APP_PBE.IMPORT_DATA_ROW_ERRORS IS '@Author(Tomasz Bilski); @Project(GryfBonEl); @Date(2016-12-02);@Purpose(Tabela przechowuj¹ca informacje o b³êdach biznesowych w czasie importu);';
COMMENT ON COLUMN APP_PBE.IMPORT_DATA_ROW_ERRORS.ID IS 'Indetyfikator klucz sztuczny';
COMMENT ON COLUMN APP_PBE.IMPORT_DATA_ROW_ERRORS.IMPORT_DATA_ROW_ID IS 'Indetyfikator wczytywanego wiersza';
COMMENT ON COLUMN APP_PBE.IMPORT_DATA_ROW_ERRORS.PATH IS 'Opis b³êdu na którym wystapi³ b³ad';
COMMENT ON COLUMN APP_PBE.IMPORT_DATA_ROW_ERRORS.MESSAGE IS 'Opis b³êdu';
COMMENT ON COLUMN APP_PBE.IMPORT_DATA_ROW_ERRORS.VERSION IS 'Kolumna techniczna u¿ywana do mechanizmu Optimistic Lock';
COMMENT ON COLUMN APP_PBE.IMPORT_DATA_ROW_ERRORS.CREATED_USER IS 'Login u¿ytkownika, który utworzy³ rekord';
COMMENT ON COLUMN APP_PBE.IMPORT_DATA_ROW_ERRORS.CREATED_TIMESTAMP IS 'Data utworzenia rekordu';
COMMENT ON COLUMN APP_PBE.IMPORT_DATA_ROW_ERRORS.MODIFIED_USER IS 'Login u¿ytkownika, który ostatnio modyfikowa³ rekord';
COMMENT ON COLUMN APP_PBE.IMPORT_DATA_ROW_ERRORS.MODIFIED_TIMESTAMP IS 'Data ostatniej modyfikacji rekordu';