ALTER TABLE ${gryf.schema}.TI_TRAINING_INSTANCES
ADD (PRODUCT_INSTANCE_CALC_FOR_HOUR VARCHAR2(10 BYTE));

COMMENT ON COLUMN 
${gryf.schema}.TI_TRAINING_INSTANCES.PRODUCT_INSTANCE_CALC_FOR_HOUR IS 
'Liczba bonów, które rozliczają jedną godzinę szkolenia';