ALTER TABLE ${gryf.schema}.TI_TRAINING_CATEGORY_PARAMS
ADD (PRODUCT_INSTANCE_CALC_TYPE VARCHAR2(10 BYTE));

ALTER TABLE ${gryf.schema}.TI_TRAINING_CATEGORY_PARAMS
ADD 
FOREIGN KEY
  (PRODUCT_INSTANCE_CALC_TYPE)
REFERENCES
  ${gryf.schema}.TI_TRAINING_PRD_INS_CALC_TYPES
  (ID)
ENABLE
VALIDATE;

COMMENT ON COLUMN 
${gryf.schema}.TI_TRAINING_CATEGORY_PARAMS.PRODUCT_INSTANCE_CALC_TYPE IS 
'Identyfikator sposobu rozliczania bonow';
