
MERGE INTO ${gryf.schema}.TI_TRAINING_INSTANCES tti
     USING (SELECT DISTINCT TI.ID, TCP.PRODUCT_INSTANCE_FOR_HOUR
              FROM ${gryf.schema}.TI_TRAINING_INSTANCES ti
                   JOIN ${gryf.schema}.TI_TRAININGS T ON T.ID = TI.TRAINING_ID
                   JOIN ${gryf.schema}.TI_TRAINING_CATEGORY_PARAMS tcp
                      ON TCP.CATEGORY_ID = T.TRAINING_CATEGORY_ID) A
        ON (tti.id = A.id)
WHEN MATCHED
THEN
   UPDATE SET TTI.PRODUCT_INSTANCE_CALC_FOR_HOUR = A.PRODUCT_INSTANCE_FOR_HOUR;