CREATE OR REPLACE TRIGGER APP_PBE.TRG_PBE_PRODUCT_EMISSIONS_AUD
AFTER DELETE OR UPDATE ON APP_PBE.PBE_PRODUCT_EMISSIONS
REFERENCING NEW AS NEW OLD AS OLD FOR EACH ROW
DECLARE
  v_operation  VARCHAR2(1) := 'U';
  v_user       VARCHAR2(100) := USER;
BEGIN
 IF DELETING THEN v_operation := 'D'; END IF;

  INSERT INTO APP_PBE.PBE_PRODUCT_EMISSIONS_AUDIT (
    ID,
    PRD_ID,
    GRANT_PROGRAM_ID,
    NAME,
    DESCRIPTION,
    EMISSION_DATE,
    QUANTITY,
    AUDIT_USER,AUDIT_TIMESTAMP,AUDIT_OPERATION)
  VALUES (
    :OLD.ID,
    :OLD.PRD_ID,
    :OLD.GRANT_PROGRAM_ID,
    :OLD.NAME,
    :OLD.DESCRIPTION,
    :OLD.EMISSION_DATE,
    :OLD.QUANTITY,
    v_user, SYSTIMESTAMP, v_operation );
EXCEPTION
  WHEN OTHERS THEN
    EAGLE.PK_ERROR.RAISE_ERROR(sqlcode,sqlerrm,'TRG_PBE_PRODUCT_EMISSIONS_AUD');
END TRG_PBE_PRODUCT_EMISSIONS_AUD;
/