CREATE OR REPLACE TRIGGER APP_PBE.TRG_ENTERPRISES_AUDIT
AFTER DELETE OR UPDATE ON APP_PBE.ENTERPRISES
REFERENCING NEW AS NEW OLD AS OLD FOR EACH ROW
DECLARE
  v_operation  VARCHAR2(1) := 'U';
  v_user       VARCHAR2(30) := USER;
BEGIN
 IF DELETING THEN v_operation := 'D'; END IF;
 IF USER in ( 'SRV_EE', 'SRV_EE_TI', 'SRV_EE_IND' ) AND NOT DELETING THEN v_user := :NEW.MODIFIED_USER; END IF; -- w przypadku GRYF-a jest pula połączeń na użytkowniku SRV_EE
  INSERT INTO APP_PBE.ENTERPRISES_AUDIT (
    ID,
    ACCOUNT_REPAYMENT,
    ZIP_CODE_INVOICE,
    ZIP_CODE_CORR,
    NAME,
    VAT_REG_NUM,
    ADDRESS_INVOICE,
    ADDRESS_CORR,
    REMARKS,
    VERSION,
    CREATED_USER,
    CREATED_TIMESTAMP,
    MODIFIED_USER,
    MODIFIED_TIMESTAMP,
    AUDIT_USER,AUDIT_TIMESTAMP,AUDIT_OPERATION)
  VALUES (
    :OLD.ID,
    :OLD.ACCOUNT_REPAYMENT,
    :OLD.ZIP_CODE_INVOICE,
    :OLD.ZIP_CODE_CORR,
    :OLD.NAME,
    :OLD.VAT_REG_NUM,
    :OLD.ADDRESS_INVOICE,
    :OLD.ADDRESS_CORR,
    :OLD.REMARKS,
    :OLD.VERSION,
    :OLD.CREATED_USER,
    :OLD.CREATED_TIMESTAMP,
    :OLD.MODIFIED_USER,
    :OLD.MODIFIED_TIMESTAMP,
    v_user, SYSTIMESTAMP, v_operation );
EXCEPTION
  WHEN OTHERS THEN
    EAGLE.PK_ERROR.RAISE_ERROR(sqlcode,sqlerrm,'TRG_ENTERPRISES_AUDIT');
END TRG_ENTERPRISES_AUDIT;
------------------- TRIGGER END ------------------------
/