-----------------------------------------------------
----- APP_PBE.E_REIMBURSEMENT_LINES ----------------
-----------------------------------------------------


CREATE TABLE APP_PBE.E_REIMBURSEMENT_LINES
(
  ID                           NUMBER           NOT NULL,
  E_REIMBURSMENT_ID            NUMBER,
  ORDER_ID     NUMBER,
  USED_NUM         NUMBER(10),
  OWN_CONTRIBUTION_PERCENTAGE  NUMBER(8,2),
  IND_SUBSIDY_PERCENTAGE  NUMBER(8,2),
  SXO_TI_AMOUNT_DUE_TOTAL  NUMBER(8,4),
  SXO_IND_AMOUNT_DUE_TOTAL  NUMBER(8,4),
  IND_OWN_CONTRIBUTION_USED  NUMBER(8,4),
  IND_SUBSIDY_VALUE  NUMBER(8,4),
  VERSION                      NUMBER           NOT NULL,
  CREATED_USER                 VARCHAR2(100 BYTE) NOT NULL,
  CREATED_TIMESTAMP            TIMESTAMP(6)     NOT NULL,
  MODIFIED_USER                VARCHAR2(100 BYTE) NOT NULL,
  MODIFIED_TIMESTAMP           TIMESTAMP(6)     NOT NULL
)
TABLESPACE APP_PBE
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING
NOCOMPRESS
NOCACHE
MONITORING;


CREATE UNIQUE INDEX APP_PBE.PK_E_REIMBURSEMENT_LINES_ID ON APP_PBE.E_REIMBURSEMENT_LINES
(ID)
LOGGING
TABLESPACE APP_PBE
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


ALTER TABLE APP_PBE.E_REIMBURSEMENT_LINES ADD (
  CONSTRAINT PK_E_REIMBURSEMENT_LINES_ID
  PRIMARY KEY
  (ID)
  USING INDEX APP_PBE.PK_E_REIMBURSEMENT_LINES_ID
  ENABLE VALIDATE);


BEGIN
  dbms_output.put_line(SYS.PK_ADMIN.F_GRANT_TO_EAGLE('APP_PBE', 'SRV_EE', 'E_REIMBURSEMENT_LINES', 'ALL'));
  dbms_output.put_line(SYS.PK_ADMIN.F_GRANT_TO_EAGLE('APP_PBE', 'EAGLE', 'E_REIMBURSEMENT_LINES', 'ALL'));
  dbms_output.put_line(SYS.PK_ADMIN.F_GRANT_TO_EAGLE('APP_PBE', 'SRV_EE_IND', 'E_REIMBURSEMENT_LINES', 'ALL'));
  dbms_output.put_line(SYS.PK_ADMIN.F_GRANT_TO_EAGLE('APP_PBE', 'SRV_EE_TI', 'E_REIMBURSEMENT_LINES', 'ALL'));
  dbms_output.put_line(SYS.PK_ADMIN.F_GRANT_TO_EAGLE('APP_PBE', 'DEVELOPER', 'E_REIMBURSEMENT_LINES', 'SELECT'));
END;