CREATE USER srv_ee_ind
IDENTIFIED BY "srv_ee_ind"
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TMP
PROFILE DEFAULT
ACCOUNT UNLOCK;
GRANT CONNECT TO srv_ee_ind;


CREATE USER srv_ee_ti
IDENTIFIED BY "srv_ee_ti"
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TMP
PROFILE DEFAULT
ACCOUNT UNLOCK;
GRANT CONNECT TO srv_ee_ti;


create or replace TRIGGER SRV_EE_TI.LOGON_ALTER_SESSION_TRG
AFTER LOGON ON SRV_EE_TI.SCHEMA
  BEGIN
    EXECUTE IMMEDIATE 'ALTER SESSION SET NLS_LANGUAGE = ''POLISH''';
    EXECUTE IMMEDIATE 'ALTER SESSION SET NLS_TERRITORY = ''POLAND''';
  END;


create or replace TRIGGER SRV_EE_IND.LOGON_ALTER_SESSION_TRG
AFTER LOGON ON SRV_EE_IND.SCHEMA
  BEGIN
    EXECUTE IMMEDIATE 'ALTER SESSION SET NLS_LANGUAGE = ''POLISH''';
    EXECUTE IMMEDIATE 'ALTER SESSION SET NLS_TERRITORY = ''POLAND''';
  END;