-- PBE_PRODUCT_INSTANCES
UPDATE APP_PBE.PBE_PRODUCT_INSTANCES SET MODIFIED_USER = 'system' WHERE MODIFIED_USER IS NULL;
UPDATE APP_PBE.PBE_PRODUCT_INSTANCES SET MODIFIED_TIMESTAMP = SYSDATE WHERE MODIFIED_TIMESTAMP IS NULL;

-- PBE_PRODUCT_INSTANCE_EVENTS
UPDATE APP_PBE.PBE_PRODUCT_INSTANCE_EVENTS SET MODIFIED_USER = 'system' WHERE MODIFIED_USER IS NULL;
UPDATE APP_PBE.PBE_PRODUCT_INSTANCE_EVENTS SET MODIFIED_TIMESTAMP = SYSDATE WHERE MODIFIED_TIMESTAMP IS NULL;

-- PBE_PRODUCT_EMISSIONS
UPDATE APP_PBE.PBE_PRODUCT_EMISSIONS SET MODIFIED_USER = 'system' WHERE MODIFIED_USER IS NULL;
UPDATE APP_PBE.PBE_PRODUCT_EMISSIONS SET MODIFIED_TIMESTAMP = SYSDATE WHERE MODIFIED_TIMESTAMP IS NULL;

-- PBE_PRD_INST_STATUS_DICS
UPDATE APP_PBE.PBE_PRD_INST_STATUS_DICS SET MODIFIED_USER = 'system' WHERE MODIFIED_USER IS NULL;
UPDATE APP_PBE.PBE_PRD_INST_STATUS_DICS SET MODIFIED_TIMESTAMP = SYSDATE WHERE MODIFIED_TIMESTAMP IS NULL;

-- PBE_PRD_INST_EVN_TYPE_DICS
UPDATE APP_PBE.PBE_PRD_INST_EVN_TYPE_DICS SET MODIFIED_USER = 'system' WHERE MODIFIED_USER IS NULL;
UPDATE APP_PBE.PBE_PRD_INST_EVN_TYPE_DICS SET MODIFIED_TIMESTAMP = SYSDATE WHERE MODIFIED_TIMESTAMP IS NULL;

-- INDIVIDUAL_USERS
UPDATE APP_PBE.INDIVIDUAL_USERS SET MODIFIED_USER = 'system' WHERE MODIFIED_USER IS NULL;
UPDATE APP_PBE.INDIVIDUAL_USERS SET MODIFIED_TIMESTAMP = SYSDATE WHERE MODIFIED_TIMESTAMP IS NULL;