drop sequence EAGLE.ind_seq;

CREATE SEQUENCE EAGLE.ind_seq
MINVALUE 1
MAXVALUE 9999999999999999999999999999
INCREMENT BY 1
START WITH 1500
CACHE 20
NOORDER NOCYCLE;

-- uprawnienia
BEGIN
  dbms_output.put_line(SYS.PK_ADMIN.F_GRANT_TO_EAGLE('EAGLE', 'SRV_EE', 'ASYN_JOB_SEQ', 'ALL'));
  dbms_output.put_line(SYS.PK_ADMIN.F_GRANT_TO_EAGLE('EAGLE', 'DEVELOPER', 'ASYN_JOB_SEQ', 'SELECT'));
END;
/