INSERT INTO APP_PBE.TI_TRAININGS (ID, EXTERNAL_ID, TRAINING_INSTITUTION_ID, NAME, PRICE, START_DATE, END_DATE, PLACE, HOURS_NUMBER, HOUR_PRICE, TRAINING_CATEGORY_ID, REIMBURSMENT_CONDITIONS, ACTIVE, DEACTIVATE_DATE, DEACTIVATE_JOB_ID, VERSION, CREATED_USER, CREATED_TIMESTAMP, MODIFIED_USER, MODIFIED_TIMESTAMP)
VALUES(EAGLE.TI_TRA_SEQ.nextval, null, 1080, 'Szkolenie z zakresu pakietu Office', 3000,
  to_date('2016-12-25', 'yyyy-MM-dd'), to_date('2017-01-05', 'yyyy-MM-dd'), 'Warszawa', 30, 50, 'KCY', 'Posiadanie certyfikatu programisty', 'Y', null, null, 1, 'system', SYSDATE, 'system', SYSDATE);

INSERT INTO APP_PBE.TI_TRAININGS (ID, EXTERNAL_ID, TRAINING_INSTITUTION_ID, NAME, PRICE, START_DATE, END_DATE, PLACE, HOURS_NUMBER, HOUR_PRICE, TRAINING_CATEGORY_ID, REIMBURSMENT_CONDITIONS, ACTIVE, DEACTIVATE_DATE, DEACTIVATE_JOB_ID, VERSION, CREATED_USER, CREATED_TIMESTAMP, MODIFIED_USER, MODIFIED_TIMESTAMP)
VALUES(EAGLE.TI_TRA_SEQ.nextval, null, 1104, 'Kurs jêzyka angielskiego - Poziom C1', 2500,
  to_date('2016-09-11', 'yyyy-MM-dd'), to_date('2016-09-13', 'yyyy-MM-dd'), 'Gdynia', 30, 50, 'JAZ', 'Posiadanie certyfikatu kierowcy', 'Y', null, null, 1, 'system', SYSDATE, 'system', SYSDATE);

INSERT INTO APP_PBE.TI_TRAININGS (ID, EXTERNAL_ID, TRAINING_INSTITUTION_ID, NAME, PRICE, START_DATE, END_DATE, PLACE, HOURS_NUMBER, HOUR_PRICE, TRAINING_CATEGORY_ID, REIMBURSMENT_CONDITIONS, ACTIVE, DEACTIVATE_DATE, DEACTIVATE_JOB_ID, VERSION, CREATED_USER, CREATED_TIMESTAMP, MODIFIED_USER, MODIFIED_TIMESTAMP)
VALUES(EAGLE.TI_TRA_SEQ.nextval, null, 1004, 'Szkolenie kandydatów na egzaminatorów WORD', 8000,
  to_date('2016-05-10', 'yyyy-MM-dd'), to_date('2016-08-10', 'yyyy-MM-dd'), 'Kraków', 30, 50, 'INN', 'Posiadanie certyfikatu rajdowca', 'Y', null, null, 1, 'system', SYSDATE, 'system', SYSDATE);