-- PRIV & ROLE
INSERT INTO APP_PBE.TE_PRIVILEGES (CODE,DESCRIPTION,CONTEXT) VALUES('IND_TEST_PRIV','Przywilej testowy dla osoby fizycznej','IND');
INSERT INTO APP_PBE.TE_ROLES(CODE,DESCRIPTION,CONTEXT)VALUES('IND_TEST_ROLE','Rola testowa dla osoby fizycznej','IND');

INSERT INTO APP_PBE.TE_PRIV_IN_ROLES (TE_PRIV_CODE, TE_ROLE_CODE) VALUES('IND_TEST_PRIV','IND_TEST_ROLE');

-- USER
-- user testowy  
-- login : ind_usr_test
-- pass: ind_usr_test

DECLARE
IND_ID number;
INU_ID number;
CONTACT_ID number;
BEGIN

IND_ID := EAGLE.IND_SEQ.nextval;
INU_ID := EAGLE.IND_USR_SEQ.nextval;
CONTACT_ID := EAGLE.PK_SEQ.nextval;

  Insert into APP_PBE.INDIVIDUALS (ID,CODE,ACCOUNT_PAYMENT,ACCOUNT_REPAYMENT,ZIP_CODE_INVOICE,ZIP_CODE_CORR,FIRST_NAME,LAST_NAME,PESEL,SEX,DOCUMENT_NUMBER,DOCUMENT_TYPE,ADDRESS_INVOICE,ADDRESS_CORR,REMARKS,VERSION,CREATED_USER,CREATED_TIMESTAMP,MODIFIED_USER,MODIFIED_TIMESTAMP,ENTERPRISE_ID)
  values (IND_ID,IND_ID,'00000000000000000000000000',null,'54','48','Test','Testowy','22222222222','M','AHH12456','Dowód osobisty','Koszykowa 1','Wiklinowa 2','Osoba fizyczna prowadz¹ca dzia³alnoœæ gospodarcz¹','3','EAGLE',SYSDATE,'EAGLE',SYSDATE,'4');

  Insert into APP_PBE.INDIVIDUAL_CONTACTS (ID,IND_ID,CONTACT_TYPE,CONTACT_DATA,REMARKS,CREATED_USER,CREATED_TIMESTAMP,MODIFIED_USER,MODIFIED_TIMESTAMP)
  values (CONTACT_ID,IND_ID,'EMAIL','test@isolution.pl',null,user,SYSDATE,user,SYSDATE);

  INSERT INTO APP_PBE.INDIVIDUAL_USERS
      ( INU_ID,
        IND_ID,
        VERIFICATION_CODE,
        IS_ACTIVE,
        VERSION,
        CREATED_USER,
        CREATED_TIMESTAMP
      )
    VALUES
      ( INU_ID, IND_ID , '$2a$08$HkA4KS.6FdewNz58U.ZSP.unNWhI5vM5d0phoC79sfoG9YQmYCt3a', 1,
      1, user, sysdate);
  
 
  INSERT INTO APP_PBE.TE_IND_USER_IN_ROLES( INU_ID, TE_ROLE_CODE  )
    VALUES(INU_ID,'IND_TEST_ROLE');
END;
/
