Insert into APP_PBE.INDIVIDUAL_CONTACTS (ID,IND_ID,CONTACT_TYPE,CONTACT_DATA,REMARKS,CREATED_USER,CREATED_TIMESTAMP,MODIFIED_USER,MODIFIED_TIMESTAMP)
values (EAGLE.PK_SEQ.nextval,(SELECT ID FROM APP_PBE.INDIVIDUALS WHERE PESEL = '22222222222'),'VER_EMAIL','test@isolution.pl',null,user,SYSDATE,user,SYSDATE);

