INSERT INTO EAGLE.ADM_USER_GROUPS VALUES('GRF_PBE_TI_TRAININGS', 'Przeglad szkolen', 'A', 'Podgl¹d katalogu szkoleñ');
INSERT INTO EAGLE.ADM_USER_GROUPS VALUES('GRF_PBE_TI_TRAININGS_MOD', 'Edycja szkolen', 'A', 'Edycja danych dotycz¹cych szkoleñ');

INSERT INTO EAGLE.ADM_GROUPS_IN_ROLES VALUES('ADM_ADMINISTRACJA', 'GRF_PBE_TI_TRAININGS');
INSERT INTO EAGLE.ADM_GROUPS_IN_ROLES VALUES('ADM_ADMINISTRACJA', 'GRF_PBE_TI_TRAININGS_MOD');