-- PRIV & ROLE
INSERT INTO APP_PBE.TE_PRIVILEGES (CODE,DESCRIPTION,CONTEXT) VALUES('TI_TEST_PRIV','Przywilej testowy dla instytucji szkoleniowej','TI');
INSERT INTO APP_PBE.TE_ROLES(CODE,DESCRIPTION,CONTEXT)VALUES('TI_TEST_ROLE','Rola testowa dla instytucji szkoleniowej','TI');

INSERT INTO APP_PBE.TE_PRIV_IN_ROLES (TE_PRIV_CODE, TE_ROLE_CODE) VALUES('TI_TEST_PRIV','TI_TEST_ROLE');

-- USER
-- user testowy  
-- login : ti_usr_test
-- pass: ti_usr_test

DECLARE
TI_ID number;
USR_ID number;
BEGIN

TI_ID := EAGLE.TRIN_SEQ.nextval;
USR_ID := EAGLE.TI_USR_SEQ.nextval;

  INSERT INTO APP_PBE.TRAINING_INSTITUTIONS
      (ID, CODE,
      ZIP_CODE_INVOICE, ZIP_CODE_CORR,
      NAME, VAT_REG_NUM, ADDRESS_INVOICE, ADDRESS_CORR, 
      VERSION, CREATED_USER, CREATED_TIMESTAMP, MODIFIED_USER, MODIFIED_TIMESTAMP )
    VALUES
      (TI_ID, 'TEST',
      (SELECT ID FROM EAGLE.ZIP_CODES WHERE ACTIVE =1 AND ROWNUM <= 1), (SELECT ID FROM EAGLE.ZIP_CODES WHERE ACTIVE =1 AND ROWNUM <= 1), 
      'Instutucja dla u¿ytkownika testowego' ,'3554868937', 'adres','adres_kor',
      1, user, sysdate, user,sysdate);
      
  INSERT INTO APP_PBE.TRAINING_INSTITUTION_USERS
      ( ID, TRAINING_ISTITUTION_ID, LOGIN, EMAIL, PASSWORD,
        VERSION,CREATED_USER,CREATED_TIMESTAMP, MODIFIED_USER,MODIFIED_TIMESTAMP
      )
    VALUES
      ( USR_ID, TI_ID, 'ti_usr_test' , 'test@isolution.pl', '$2a$04$gRtEVCc74Um7f28iXspMo.iAA/fZAwWQor1butyONR8lYrl.1Dbk6', 
      1, user, sysdate, user,sysdate);
  
 
  INSERT INTO APP_PBE.TI_USER_IN_ROLES( TI_USER_ID, TE_ROLE_CODE  )
    VALUES(USR_ID,'TI_TEST_ROLE');
END;

