ALTER TABLE ${gryf.schema}.TI_TRAINING_INSTANCES_EXT      MODIFY CERTIFICATE_REMARK VARCHAR2(1000);

ALTER TABLE ${gryf.schema}.TI_TRAINING_INSTANCES_EXT_AUDT MODIFY CERTIFICATE_REMARK VARCHAR2(1000);