
INSERT INTO EAGLE.ADM_GROUPS_IN_ROLES
     VALUES ('ADM_ADMINISTRACJA', 'GRF_PBE_TI_TRAINING_INSTANCES_STATUS_MOD');

INSERT INTO EAGLE.ADM_GROUPS_IN_ROLES
     VALUES ('PBE_TBOK_ADMIN', 'GRF_PBE_TI_TRAINING_INSTANCES_STATUS_MOD');