ALTER TABLE ${gryf.schema}.PBE_PRODUCTS
ADD (GRANT_PROGRAM_ID NUMBER);

ALTER TABLE ${gryf.schema}.PBE_PRODUCTS
ADD CONSTRAINT GRANT_PROGRAM_FK FOREIGN KEY
(
  GRANT_PROGRAM_ID 
)
REFERENCES ${gryf.schema}.GRANT_PROGRAMS
(
  ID 
)
ENABLE;

COMMENT ON COLUMN ${gryf.schema}.PBE_PRODUCTS.GRANT_PROGRAM_ID IS 'Id projektu/programu';

UPDATE ${gryf.schema}.PBE_PRODUCTS SET GRANT_PROGRAM_ID = (SELECT ID FROM ${gryf.schema}.GRANT_PROGRAMS WHERE PROGRAM_CODE ='${program.code.wupkkz}' ) WHERE PRD_ID = 'KZ_BON_EL';
UPDATE ${gryf.schema}.PBE_PRODUCTS SET GRANT_PROGRAM_ID = (SELECT ID FROM ${gryf.schema}.GRANT_PROGRAMS WHERE PROGRAM_CODE ='${program.code.wupkkk}' ) WHERE PRD_ID = 'KK_BON_EL';

ALTER TABLE ${gryf.schema}.PBE_PRODUCTS
MODIFY (GRANT_PROGRAM_ID NOT NULL);


-- uprawnienia
BEGIN
	dbms_output.put_line(SYS.PK_ADMIN.F_GRANT_TO_EAGLE(upper('${gryf.schema}'), 'SRV_EE_IND', 'PBE_PRODUCTS', 'SELECT'));
END;
/