ALTER TABLE APP_PBE.E_REIMBURSEMENTS_AUDIT
ADD (FO_COMMENT VARCHAR2(4000 Byte));


CREATE OR REPLACE TRIGGER APP_PBE.TRG_E_REIMBURSEMENTS_AUDIT
AFTER DELETE OR UPDATE ON APP_PBE.E_REIMBURSEMENTS
REFERENCING NEW AS NEW OLD AS OLD FOR EACH ROW
DECLARE
  v_operation  VARCHAR2(1) := 'U';
  v_user       VARCHAR2(100) := USER;
BEGIN
 IF DELETING THEN v_operation := 'D'; END IF;
 IF USER in ( 'SRV_EE', 'SRV_EE_TI', 'SRV_EE_IND' ) AND NOT DELETING THEN v_user := :NEW.MODIFIED_USER; END IF; -- w przypadku GRYF-a jest pula po??cze? na u?ytkowniku SRV_EE
  INSERT INTO APP_PBE.E_REIMBURSEMENTS_AUDIT (
    ID,
    TYPE_ID,
    TI_TR_INST_ID,
    PRODUCT_INSTANCE_POOL_ID,
    STATUS_ID,
    ARRIVAL_DATE,
    REIMBURSEMENT_DATE,
    RECON_DATE,
    SXO_TI_AMOUNT_DUE_TOTAL,
    SXO_IND_AMOUNT_DUE_TOTAL,
    IND_TI_AMOUNT_DUE_TOTAL,
    IND_OWN_CONTRIBUTION_USED,
    IND_SUBSIDY_VALUE,
    TI_REIMB_ACCOUNT_NUMBER,
    REQUIRED_CORRECTION_DATE,
    VERSION,
    CREATED_USER,
    CREATED_TIMESTAMP,
    MODIFIED_USER,
    MODIFIED_TIMESTAMP,
    EXPIRED_PRODUCTS_NUM,
    REJECTION_REASON_ID,
    REJECTION_DETAILS,
    REJECTION_DATE,
    NAV_EXPORTED,
    NAV_EXPORT_DATE,
    AUDIT_USER,AUDIT_TIMESTAMP,AUDIT_OPERATION,
    FO_COMMENT)
  VALUES (
    :OLD.ID,
    :OLD.TYPE_ID,
    :OLD.TI_TR_INST_ID,
    :OLD.PRODUCT_INSTANCE_POOL_ID,
    :OLD.STATUS_ID,
    :OLD.ARRIVAL_DATE,
    :OLD.REIMBURSEMENT_DATE,
    :OLD.RECON_DATE,
    :OLD.SXO_TI_AMOUNT_DUE_TOTAL,
    :OLD.SXO_IND_AMOUNT_DUE_TOTAL,
    :OLD.IND_TI_AMOUNT_DUE_TOTAL,
    :OLD.IND_OWN_CONTRIBUTION_USED,
    :OLD.IND_SUBSIDY_VALUE,
    :OLD.TI_REIMB_ACCOUNT_NUMBER,
    :OLD.REQUIRED_CORRECTION_DATE,
    :OLD.VERSION,
    :OLD.CREATED_USER,
    :OLD.CREATED_TIMESTAMP,
    :OLD.MODIFIED_USER,
    :OLD.MODIFIED_TIMESTAMP,
    :OLD.EXPIRED_PRODUCTS_NUM,
    :OLD.REJECTION_REASON_ID,
    :OLD.REJECTION_DETAILS,
    :OLD.REJECTION_DATE,
    :OLD.NAV_EXPORTED,
    :OLD.NAV_EXPORT_DATE,
    v_user, SYSTIMESTAMP, v_operation,
    :OLD.FO_COMMENT);
EXCEPTION
  WHEN OTHERS THEN
    EAGLE.PK_ERROR.RAISE_ERROR(sqlcode,sqlerrm,'TRG_E_REIMBURSEMENTS_AUDIT');
END TRG_E_REIMBURSEMENTS_AUDIT;
/
