
CREATE OR REPLACE TRIGGER ${gryf.schema}.TRG_TI_TRAININGS_AUDIT
AFTER DELETE OR UPDATE ON ${gryf.schema}.TI_TRAININGS
REFERENCING NEW AS NEW OLD AS OLD FOR EACH ROW
DECLARE
  v_operation  VARCHAR2(1) := 'U';
  v_user       VARCHAR2(100) := USER; 
BEGIN 
IF       DELETING 
      OR :new.EXTERNAL_ID != :old.EXTERNAL_ID
      OR :new.TRAINING_INSTITUTION_ID != :old.TRAINING_INSTITUTION_ID
      OR :new.NAME != :old.NAME
      OR :new.PRICE != :old.PRICE
      OR :new.START_DATE != :old.START_DATE
      OR :new.END_DATE != :old.END_DATE
      OR :new.PLACE != :old.PLACE
      OR :new.HOURS_NUMBER != :old.HOURS_NUMBER
      OR :new.HOUR_PRICE != :old.HOUR_PRICE
      OR :new.TRAINING_CATEGORY_ID != :old.TRAINING_CATEGORY_ID
      OR :new.REIMBURSMENT_CONDITIONS != :old.REIMBURSMENT_CONDITIONS
      OR :new.ACTIVE != :old.ACTIVE
      OR :new.INDIVIDUAL != :old.INDIVIDUAL
      OR :new.DEACTIVATE_USER != :old.DEACTIVATE_USER
      OR :new.DEACTIVATE_DATE != :old.DEACTIVATE_DATE
      OR :new.DEACTIVATE_JOB_ID != :old.DEACTIVATE_JOB_ID
THEN
 IF DELETING THEN v_operation := 'D'; END IF;
 IF USER in ( 'SRV_EE', 'SRV_EE_TI', 'SRV_EE_IND' ) AND NOT DELETING THEN v_user := :NEW.MODIFIED_USER; END IF; -- w przypadku GRYF-a jest pula po31czen na u?ytkowniku SRV_EE
  INSERT INTO ${gryf.schema}.TI_TRAININGS_AUDIT ( 
    ID,
    EXTERNAL_ID,
    TRAINING_INSTITUTION_ID,
    NAME,
    PRICE,
    START_DATE,
    END_DATE,
    PLACE,
    HOURS_NUMBER,
    HOUR_PRICE,
    TRAINING_CATEGORY_ID,
    REIMBURSMENT_CONDITIONS,
    ACTIVE,
    INDIVIDUAL,
    DEACTIVATE_USER,
    DEACTIVATE_DATE,
    DEACTIVATE_JOB_ID,
    VERSION,
    CREATED_USER,
    CREATED_TIMESTAMP,
    MODIFIED_USER,
    MODIFIED_TIMESTAMP,
    AUDIT_USER,AUDIT_TIMESTAMP,AUDIT_OPERATION)
  VALUES (
    :OLD.ID,
    :OLD.EXTERNAL_ID,
    :OLD.TRAINING_INSTITUTION_ID,
    :OLD.NAME,
    :OLD.PRICE,
    :OLD.START_DATE,
    :OLD.END_DATE,
    :OLD.PLACE,
    :OLD.HOURS_NUMBER,
    :OLD.HOUR_PRICE,
    :OLD.TRAINING_CATEGORY_ID,
    :OLD.REIMBURSMENT_CONDITIONS,
    :OLD.ACTIVE,
    :OLD.INDIVIDUAL,
    :OLD.DEACTIVATE_USER,
    :OLD.DEACTIVATE_DATE,
    :OLD.DEACTIVATE_JOB_ID,
    :OLD.VERSION,
    :OLD.CREATED_USER,
    :OLD.CREATED_TIMESTAMP,
    :OLD.MODIFIED_USER,
    :OLD.MODIFIED_TIMESTAMP,
    v_user, SYSTIMESTAMP, v_operation );
END IF;    
EXCEPTION 
  WHEN OTHERS THEN 
    EAGLE.PK_ERROR.RAISE_ERROR(sqlcode,sqlerrm,'TRG_TI_TRAININGS_AUDIT');
END TRG_TI_TRAININGS_AUDIT;
