
ALTER TABLE $ {gryf.schema}.TI_TRAINING_INSTANCES_EXT
ADD (
SUBCATEGORY_NAME VARCHAR2(200 BYTE),
EXAM VARCHAR2(20 BYTE),
CERTIFICATE VARCHAR2(200 BYTE),
STATUS VARCHAR2(40 BYTE),
QUALIFICATION VARCHAR2(200 BYTE),
OTHER_QUALIFICATION VARCHAR2(200 BYTE),
QUALIFICATION_CODE VARCHAR2(200 BYTE),
REGISTRATION_DATE DATE,
MAX_PARTICIPANTS_COUNT NUMBER(10),
PRICE_VALIDATE_TYPE VARCHAR2(20 BYTE)
);

ALTER TABLE $ {gryf.schema}.TI_TRAINING_INSTANCES_EXT_AUDT
ADD (
SUBCATEGORY_NAME VARCHAR2(200 BYTE),
EXAM VARCHAR2(20 BYTE),
CERTIFICATE VARCHAR2(200 BYTE),
STATUS VARCHAR2(40 BYTE),
QUALIFICATION VARCHAR2(200 BYTE),
OTHER_QUALIFICATION VARCHAR2(200 BYTE),
QUALIFICATION_CODE VARCHAR2(200 BYTE),
REGISTRATION_DATE DATE,
MAX_PARTICIPANTS_COUNT NUMBER(10),
PRICE_VALIDATE_TYPE VARCHAR2(20 BYTE)
);

