
CREATE OR REPLACE TRIGGER ${gryf.schema}.TRG_TI_TRAINING_CATEG_PAR_AUD
AFTER DELETE OR UPDATE ON ${gryf.schema}.TI_TRAINING_CATEGORY_PARAMS
REFERENCING NEW AS NEW OLD AS OLD FOR EACH ROW
DECLARE
  v_operation  VARCHAR2(1) := 'U';
  v_user       VARCHAR2(100) := USER; 
BEGIN 
 IF DELETING THEN v_operation := 'D'; END IF;
  INSERT INTO ${gryf.schema}.TI_TRAINING_CATEGORY_PAR_AUDIT ( 
    ID,
    CATEGORY_ID,
    GRANT_PROGRAM_ID,
    PRODUCT_INSTANCE_FOR_HOUR,
    MAX_PRODUCT_INSTANCE,
    INDIVIDUAL_PRODUCT_INSTANCE,
    DATE_FROM,
    DATE_TO,
    AUDIT_USER,AUDIT_TIMESTAMP,AUDIT_OPERATION)
  VALUES (
    :OLD.ID,
    :OLD.CATEGORY_ID,
    :OLD.GRANT_PROGRAM_ID,
    :OLD.PRODUCT_INSTANCE_FOR_HOUR,
    :OLD.MAX_PRODUCT_INSTANCE,
    :OLD.INDIVIDUAL_PRODUCT_INSTANCE,
    :OLD.DATE_FROM,
    :OLD.DATE_TO,
    v_user, SYSTIMESTAMP, v_operation );
EXCEPTION 
  WHEN OTHERS THEN 
    EAGLE.PK_ERROR.RAISE_ERROR(sqlcode,sqlerrm,'TRG_TI_TRAINING_CATEG_PAR_AUD');
END TRG_TI_TRAINING_CATEG_PAR_AUD;