ALTER TABLE ${gryf.schema}.TI_TRAININGS
ADD (INDIVIDUAL  VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL);

COMMENT ON COLUMN 
${gryf.schema}.TI_TRAININGS.INDIVIDUAL IS 
'Flaga czy us³uga jest rozliczana indywidualnie';

ALTER TABLE ${gryf.schema}.TI_TRAININGS_AUDIT
ADD (INDIVIDUAL  VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL);
