ALTER TABLE ${gryf.schema}.TI_TRAINING_CATEGORY_PARAMS
ADD (INDIVIDUAL_PRODUCT_INSTANCE NUMBER(10));

COMMENT ON COLUMN 
${gryf.schema}.TI_TRAINING_CATEGORY_PARAMS.INDIVIDUAL_PRODUCT_INSTANCE IS 
'Liczba bonów rozliczaj¹ca godzinê dla us³ug indywidualnych';



ALTER TABLE ${gryf.schema}.TI_TRAINING_CATEGORY_PAR_AUDIT
ADD (INDIVIDUAL_PRODUCT_INSTANCE NUMBER(10));
