
ALTER TABLE $ {gryf.schema}.TI_TRAINING_INSTANCES_EXT
DROP (START_DATE_STR, END_DATE_STR, PRICE_STR, HOURS_NUMBER_STR, HOUR_PRICE_STR, ROW_NUM, IMPORT_ID, ORD_SEARCH_STRING);

ALTER TABLE $ {gryf.schema}.TI_TRAINING_INSTANCES_EXT_AUDT
DROP (START_DATE_STR, END_DATE_STR, PRICE_STR, HOURS_NUMBER_STR, HOUR_PRICE_STR, ROW_NUM, IMPORT_ID, ORD_SEARCH_STRING);
