package pl.sodexo.it.gryf.common.enums;

/**
 * Created by tomasz.bilski.ext on 2015-06-18.
 */
public enum Privileges {

    //DICTIONARIES

    GRF_ZIP_CODES,
    GRF_ZIP_CODES_MOD,

    //ENTERPRISE

    GRF_ENTERPRISES,
    GRF_ENTERPRISE_MOD,
    GRF_ENTERPRISE_REPAY_ACC_MOD,

    //INDIVIDUAL

    GRF_INDIVIDUALS,
    GRF_INDIVIDUAL_MOD,
    GRF_INDIVIDUAL_REPAY_ACC_MOD,

    //TRAINING_INSTITUTION

    GRF_TRAINING_INSTITUTIONS,
    GRF_TRAINING_INSTITUTION_MOD,

    //TRAININGS

    GRF_PBE_TI_TRAININGS,
    GRF_PBE_TI_TRAININGS_MOD,

    //TRAINING_INSTANCES

    GRF_PBE_TI_TRAINING_INSTANCES,
    GRF_PBE_TI_TRAINING_INSTANCES_MOD,
    GRF_PBE_TI_TRAINING_INSTANCES_STATUS_MOD,

    //APPLICATION

    GRF_PBE_APPLICATIONS,
    GRF_PBE_APPLICATION_MOD,
    GRF_PBE_APPLICATION_PROC,

    //ORDERS

    GRF_PBE_ORDERS,
    GRF_PBE_ORDERS_MOD,
    GRF_PBE_ORDERS_CREATE,
    GRF_PBE_ORDERS_CONFIRM_PAYMENT,
    GRF_PBE_ORDERS_CREATE_PRODUCTS,
    GRF_PBE_ORDERS_PRINT_DOC,
    GRF_PBE_ORDERS_SEND,
    GRF_PBE_ORDERS_CANCEL,

    //DELIVERIES

    GRF_PBE_DELIVERIES,
    GRF_PBE_DELIVERIES_MOD,
    GRF_PBE_DELIVERIES_REG,
    GRF_PBE_DELIVERIES_ACCEPT,
    GRF_PBE_DELIVERIES_REIMB,
    GRF_PBE_DELIVERIES_CANCEL,

    //REIMBURSEMENT

    GRF_PBE_REIMB,
    GRF_PBE_REIMB_MOD,
    GRF_PBE_REIMB_TI_ACC_MOD,
    GRF_PBE_REIMB_ANON,
    GRF_PBE_REIMB_CORR,
    GRF_PBE_REIMB_PROC,
    GRF_PBE_REIMB_CANCEL,
    GRF_PBE_REIMB_FINISH,

    //ELECTRONIC REIMBURSEMENTS

    GRF_PBE_E_REIMBURSEMENTS,
    GRF_PBE_E_REIMBURSEMENTS_MOD,

    //CONTRACTS

    GRF_PBE_CONTRACTS,
    GRF_PBE_CONTRACTS_MOD,

    //ADMINISTRATION

    GRF_PBE_ASYNCH_JOBS,
    GRF_PBE_DATA_IMPORT_MOD,

    //INDIVIDUAL & TI

    IND_DESKTOP_ROLE,
    TI_MAIN_ROLE
}
