UPDATE ${gryf.schema}.E_REIMBURSEMENTS er set STATUS_ID = 'T_RMS'
WHERE ID = 5096
  AND STATUS_ID = 'G_DOC'
  AND NOT EXISTS (SELECT 1 FROM ${gryf.schema}.E_REIMBURSEMENT_INVOICES eri WHERE eri.E_REIMBURSEMENT_ID = er.ID);
